import { doc, onSnapshot, runTransaction, serverTimestamp, Timestamp, type Unsubscribe } from 'firebase/firestore'
import { useEffect, useState } from 'react'
import { firebaseAuth, firestore } from './firebase'

export type EditLease = { id:string; application:string; recordType:string; recordId:string; ownerEmail:string; ownerName:string; acquiredAt:Timestamp; refreshedAt:Timestamp; expiresAt:Timestamp; takeoverCount:number }
const MINUTES = 8
const key=(application:string,recordType:string,recordId:string)=>`${application}:${recordType}:${recordId}`.replaceAll(/[^a-z0-9:_-]+/gi,'-')

export async function acquireEditLease(application:string,recordType:string,recordId:string,ownerName='Current user'){
 if(!firestore||!firebaseAuth?.currentUser) throw new Error('Sign in before editing a controlled record.')
 const ownerEmail=firebaseAuth.currentUser.email?.toLowerCase()||'';const reference=doc(firestore,'workspaceEditLeases',key(application,recordType,recordId));const now=new Date()
 await runTransaction(firestore,async transaction=>{const current=await transaction.get(reference);const lease=current.exists()?current.data() as EditLease:null;const heldByOther=lease&&lease.ownerEmail!==ownerEmail&&lease.expiresAt?.toDate?.().getTime()>now.getTime();if(heldByOther)throw new Error(`${lease.ownerName||lease.ownerEmail} is currently editing this record.`);transaction.set(reference,{id:reference.id,application,recordType,recordId,ownerEmail,ownerName,acquiredAt:lease?.ownerEmail===ownerEmail?lease.acquiredAt:Timestamp.fromDate(now),refreshedAt:Timestamp.fromDate(now),expiresAt:Timestamp.fromDate(new Date(now.getTime()+MINUTES*60000)),takeoverCount:lease&&lease.ownerEmail!==ownerEmail?(lease.takeoverCount||0)+1:(lease?.takeoverCount||0)},{merge:true})})
}
export async function refreshEditLease(application:string,recordType:string,recordId:string){const ownerEmail=firebaseAuth?.currentUser?.email?.toLowerCase();if(!firestore||!ownerEmail)return;const reference=doc(firestore,'workspaceEditLeases',key(application,recordType,recordId));const now=new Date();await runTransaction(firestore,async transaction=>{const current=await transaction.get(reference);if(!current.exists()||current.data().ownerEmail!==ownerEmail)return;transaction.update(reference,{refreshedAt:Timestamp.fromDate(now),expiresAt:Timestamp.fromDate(new Date(now.getTime()+MINUTES*60000))})})}
export async function releaseEditLease(application:string,recordType:string,recordId:string){const ownerEmail=firebaseAuth?.currentUser?.email?.toLowerCase();if(!firestore||!ownerEmail)return;const reference=doc(firestore,'workspaceEditLeases',key(application,recordType,recordId));await runTransaction(firestore,async transaction=>{const current=await transaction.get(reference);if(current.exists()&&current.data().ownerEmail===ownerEmail)transaction.update(reference,{expiresAt:Timestamp.fromDate(new Date()),releasedAt:serverTimestamp()})})}
export function useEditLease(application:string,recordType:string,recordId:string,ownerName:string){const[lease,setLease]=useState<EditLease|null>(null);const[notice,setNotice]=useState('');const[checking,setChecking]=useState(Boolean(recordId));const email=firebaseAuth?.currentUser?.email?.toLowerCase()||'';useEffect(()=>{setNotice('');setChecking(Boolean(recordId));if(!firestore||!recordId){setLease(null);setChecking(false);return}let unsubscribe:Unsubscribe|undefined;void acquireEditLease(application,recordType,recordId,ownerName).then(()=>{unsubscribe=onSnapshot(doc(firestore!,'workspaceEditLeases',key(application,recordType,recordId)),snapshot=>{setLease(snapshot.exists()?snapshot.data() as EditLease:null);setChecking(false)})}).catch(error=>{setNotice(error instanceof Error?error.message:'This record is currently locked.');setChecking(false)});const timer=window.setInterval(()=>void refreshEditLease(application,recordType,recordId),120000);return()=>{window.clearInterval(timer);if(unsubscribe)unsubscribe();void releaseEditLease(application,recordType,recordId)}},[application,ownerName,recordId,recordType]);const locked=Boolean(lease&&lease.ownerEmail!==email&&lease.expiresAt?.toDate?.().getTime()>Date.now());return{lease,locked,notice,checking,canSave:Boolean(recordId)&&!checking&&!locked&&!notice,clearNotice:()=>setNotice('')}}
