import { GoogleAuthProvider, reauthenticateWithPopup } from 'firebase/auth'
import { doc, setDoc } from 'firebase/firestore'
import { firebaseAuth, firestore } from './firebase'

export type FacilitiesAttachment = { id:string; name:string; contentType:string; size:number; uploadedAt:string; uploadedBy:string; provider:'Google Drive'; driveFileId:string; driveUrl:string; availability:'Pending import' }
export type FacilitiesUploadSession = { accessToken:string }

const custodianEmail='dev@glasscolabs.com'
const allowed=new Set(['pdf','doc','docx','xls','xlsx','csv','txt','jpg','jpeg','png','gif','webp','heic','mp4','mov'])
const safe=(name:string)=>name.replace(/[^a-zA-Z0-9._-]+/g,'_').slice(0,120)||'attachment'
const extension=(name:string)=>name.split('.').pop()?.toLowerCase()||''
const contentType=(file:File)=>file.type||'application/octet-stream'

export function validateFacilitiesAttachments(files:File[]){if(files.length>8)return'Add up to 8 files per request.';if(files.some(file=>file.size>15*1024*1024))return'Each attachment must be 15 MB or smaller.';if(files.reduce((sum,file)=>sum+file.size,0)>50*1024*1024)return'Combined attachments must not exceed 50 MB.';if(files.some(file=>!allowed.has(extension(file.name))))return'One or more attachment types are not allowed.';return''}

export async function beginFacilitiesUpload():Promise<FacilitiesUploadSession>{const user=firebaseAuth?.currentUser;if(!user)throw new Error('Sign in again before attaching files.');if(!user.providerData.some(item=>item.providerId==='google.com'))throw new Error('Use Google Workspace sign-in to attach controlled evidence.');const provider=new GoogleAuthProvider();provider.addScope('https://www.googleapis.com/auth/drive.file');provider.setCustomParameters({hd:'glasscolabs.com',prompt:'select_account consent'});const result=await reauthenticateWithPopup(user,provider);const credential=GoogleAuthProvider.credentialFromResult(result);if(!credential?.accessToken)throw new Error('Google Drive permission was not granted.');return{accessToken:credential.accessToken}}

async function upload(file:File,session:FacilitiesUploadSession,requestId:string,requestCode:string,uploaderEmail:string){const id=crypto.randomUUID(),boundary=`glassco-${crypto.randomUUID()}`,marker=`glassco-connect-facilities:${requestId}:${id}:${uploaderEmail.toLowerCase()}`,metadata=JSON.stringify({name:safe(file.name),mimeType:contentType(file),description:marker,appProperties:{product:'Glassco CONNECT',application:'Facilities Support',requestId,requestCode,intakeId:id}}),head=`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${metadata}\r\n--${boundary}\r\nContent-Type: ${contentType(file)}\r\n\r\n`,tail=`\r\n--${boundary}--`;const response=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id',{method:'POST',headers:{Authorization:`Bearer ${session.accessToken}`,'Content-Type':`multipart/related; boundary=${boundary}`},body:new Blob([head,file,tail],{type:`multipart/related; boundary=${boundary}`})});if(!response.ok)throw new Error(`Google Drive could not accept ${file.name}.`);const created=await response.json() as{id?:string};if(!created.id)throw new Error(`No Drive reference was returned for ${file.name}.`);const permission=await fetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(created.id)}/permissions?sendNotificationEmail=false`,{method:'POST',headers:{Authorization:`Bearer ${session.accessToken}`,'Content-Type':'application/json'},body:JSON.stringify({type:'user',role:'reader',emailAddress:custodianEmail})});if(!permission.ok)throw new Error(`${file.name} uploaded but could not be transferred to controlled custody.`);const uploadedAt=new Date().toISOString();return{id,name:file.name,contentType:contentType(file),size:file.size,uploadedAt,uploadedBy:uploaderEmail.toLowerCase(),provider:'Google Drive' as const,driveFileId:created.id,driveUrl:`https://drive.google.com/open?id=${encodeURIComponent(created.id)}`,availability:'Pending import' as const,marker}}

export async function uploadFacilitiesAttachments(requestId:string,requestCode:string,files:File[],uploaderEmail:string){if(!files.length)return[];const issue=validateFacilitiesAttachments(files);if(issue)throw new Error(issue);if(!firestore)throw new Error('Facilities evidence is not connected.');const session=await beginFacilitiesUpload(),attachments:FacilitiesAttachment[]=[];for(const file of files){const item=await upload(file,session,requestId,requestCode,uploaderEmail);await setDoc(doc(firestore,'facilitiesAttachmentIntakes',item.id),{id:item.id,requestId,requestCode,requesterEmail:uploaderEmail.toLowerCase(),sourceDriveFileId:item.driveFileId,sourceMarker:item.marker,name:item.name,contentType:item.contentType,size:item.size,status:'Queued',createdAt:item.uploadedAt,uploadedAt:item.uploadedAt,uploadedBy:item.uploadedBy});const{marker:_,...attachment}=item;attachments.push(attachment)}return attachments}
