import { GoogleAuthProvider, reauthenticateWithPopup } from 'firebase/auth'
import { firebaseAuth } from './firebase'

export type NcrAttachment={id:string;name:string;type:string;size:number;driveFileId:string;driveUrl:string;uploadedAt:string;uploadedBy:string;provider:'Google Drive'}
const extensions=new Set(['pdf','doc','docx','xls','xlsx','csv','txt','jpg','jpeg','png','webp'])
const extension=(name:string)=>name.split('.').pop()?.toLowerCase()||''
const safe=(name:string)=>name.replace(/[^a-zA-Z0-9._-]+/g,'_').slice(0,140)||'attachment'
export function validateNcrAttachments(files:File[]){if(files.length>10)return'Add up to 10 files.';const large=files.find(file=>file.size>15*1024*1024);if(large)return`${large.name} is larger than 15 MB.`;const invalid=files.find(file=>!extensions.has(extension(file.name)));return invalid?`${invalid.name} is not an allowed business file.`:''}
export async function uploadNcrAttachments(requestId:string,requestCode:string,files:File[],email:string):Promise<NcrAttachment[]>{if(!files.length)return[];const issue=validateNcrAttachments(files);if(issue)throw new Error(issue);const user=firebaseAuth?.currentUser;if(!user)throw new Error('Sign in again before uploading attachments.');if(!user.providerData.some(item=>item.providerId==='google.com'))throw new Error('Google Workspace sign-in is required for secure Drive attachments.');const provider=new GoogleAuthProvider();provider.addScope('https://www.googleapis.com/auth/drive.file');provider.setCustomParameters({hd:'glasscolabs.com',prompt:'select_account consent'});const result=await reauthenticateWithPopup(user,provider),credential=GoogleAuthProvider.credentialFromResult(result);if(!credential?.accessToken)throw new Error('Google Drive permission was not granted.');const uploaded:NcrAttachment[]=[];for(const file of files){const boundary=`glassco-${crypto.randomUUID()}`,metadata=JSON.stringify({name:safe(file.name),mimeType:file.type||'application/octet-stream',description:`Glassco NCR ${requestCode}`,appProperties:{product:'Glassco CONNECT',application:'NCR',requestId,requestCode}}),head=`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${metadata}\r\n--${boundary}\r\nContent-Type: ${file.type||'application/octet-stream'}\r\n\r\n`,tail=`\r\n--${boundary}--`;const response=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,webViewLink',{method:'POST',headers:{Authorization:`Bearer ${credential.accessToken}`,'Content-Type':`multipart/related; boundary=${boundary}`},body:new Blob([head,file,tail],{type:`multipart/related; boundary=${boundary}`})});if(!response.ok)throw new Error(`Google Drive could not accept ${file.name}.`);const created=await response.json() as {id?:string;webViewLink?:string};if(!created.id)throw new Error(`Drive did not return a reference for ${file.name}.`);uploaded.push({id:crypto.randomUUID(),name:file.name,type:file.type||'Business file',size:file.size,driveFileId:created.id,driveUrl:created.webViewLink||`https://drive.google.com/open?id=${created.id}`,uploadedAt:new Date().toISOString(),uploadedBy:email.toLowerCase(),provider:'Google Drive'})}return uploaded}
