import { useEffect, useMemo, useState } from 'react'
import { doc, onSnapshot } from 'firebase/firestore'
import { firestore } from '../../lib/firebase'
import { useLocalStore } from '../../lib/localStore'
import { useSupportStore } from '../../lib/supportStore'
import type { SupportDelivery } from './SupportGovernance'
import './EmailTicketing.css'
export type RatingInvite={id:string;ticketId:string;ticketCode:string;requesterEmail:string;token:string;createdAt:string;expiresAt:string;expiresAtMs?:number;submittedAt?:string;stars?:number;resolved?:boolean;comment?:string;assignee?:string;resolvedBy?:string}
type Config={inboundAlias:string;mailbox:string;sendAs:string;domains:string[];pollMinutes:number;state:'Authorisation required'|'Connected';updatedAt:string;updatedBy:string}
type Mail={id:string;messageId:string;direction:'Inbound'|'Outbound';from:string;to:string;subject:string;ticketCode?:string;status:string;at:string}
type Ticket={id:string;code:string;kind:'Incident';category:string;subcategory:string;title:string;description:string;priority:'Low';impact:'Individual';urgency:'Normal';status:'Open';requesterEmail:string;requesterName:string;assignee:string;firstResponseDueAt:string;resolutionDueAt:string;messages:never[];attachments:string[];createdAt:string;updatedAt:string;history:{at:string;event:string;actor:string}[];source:'Email'}
const defaults:Config={inboundAlias:'itsupport@glasscolabs.com',mailbox:'dev@glasscolabs.com',sendAs:'itsupport@glasscolabs.com',domains:['glasscolabs.com'],pollMinutes:2,state:'Authorisation required',updatedAt:'',updatedBy:''}
const code=(rows:Ticket[])=>`INC-${new Date().getFullYear()}-${String(rows.reduce((n,r)=>Math.max(n,Number(r.code.split('-').at(-1))||0),0)+1).padStart(4,'0')}`
export default function EmailTicketing({identityEmail,onOpenTicket}:{identityEmail:string;onOpenTicket:(id:string)=>void}){const [config,setConfig]=useLocalStore<Config>('connect.support-email-config.v1',defaults);const [mails,setMails]=useLocalStore<Mail[]>('connect.support-mail-events.v1',[]);const [tickets,setTickets]=useSupportStore<Ticket>('supportTickets',identityEmail,true);const [,setDeliveries]=useLocalStore<SupportDelivery[]>('connect.support-deliveries.v1',[]);const [ratings]=useSupportStore<RatingInvite>('supportRatings',identityEmail,true);const [bridgeHealth,setBridgeHealth]=useState<{status?:string;lastSuccessAt?:string;lastFailureAt?:string;error?:string}|null>(null);const [tab,setTab]=useState<'config'|'test'|'history'|'ratings'>('config');const [from,setFrom]=useState('');const [subject,setSubject]=useState('');const [body,setBody]=useState('');const [messageId,setMessageId]=useState('')
 useEffect(()=>{if(!firestore)return;return onSnapshot(doc(firestore,'supportBridgeHealth','gmail'),snapshot=>setBridgeHealth(snapshot.exists()?snapshot.data():null),()=>setBridgeHealth({status:'Unavailable'}))},[])
 const [ratingSearch,setRatingSearch]=useState('');const [ratingTeam,setRatingTeam]=useState('All teams');const [ratingState,setRatingState]=useState<'All'|'Submitted'|'Awaiting'|'Expired'>('All');const [ratingSort,setRatingSort]=useState<'Recent'|'Rating: low to high'|'Rating: high to low'>('Recent')
 const ratingTeams=useMemo(()=>['All teams',...Array.from(new Set(ratings.map(r=>r.assignee||'Unassigned'))).sort()], [ratings])
 const visibleRatings=useMemo(()=>{const now=Date.now(),query=ratingSearch.trim().toLowerCase();return ratings.filter(r=>{const state=r.submittedAt?'Submitted':new Date(r.expiresAt).getTime()<now?'Expired':'Awaiting';return (ratingTeam==='All teams'||(r.assignee||'Unassigned')===ratingTeam)&&(ratingState==='All'||state===ratingState)&&(!query||`${r.ticketCode} ${r.requesterEmail} ${r.assignee||''}`.toLowerCase().includes(query))}).slice().sort((a,b)=>ratingSort==='Recent'?b.createdAt.localeCompare(a.createdAt):ratingSort==='Rating: low to high'?((a.stars??6)-(b.stars??6)):((b.stars??-1)-(a.stars??-1)))},[ratingSearch,ratingSort,ratingState,ratingTeam,ratings])
 function ingest(e:React.FormEvent){e.preventDefault();const mid=messageId.trim()||`manual-${crypto.randomUUID()}`;if(mails.some(m=>m.messageId===mid))return window.alert('Duplicate Gmail message ID blocked.');if(!config.domains.includes(from.split('@')[1]?.toLowerCase()))return window.alert('Sender domain is not authorised.');const now=new Date().toISOString(),ticketCode=code(tickets),id=crypto.randomUUID();const ticket:Ticket={id,code:ticketCode,kind:'Incident',category:'Email & applications',subcategory:'Email-raised request',title:subject,description:body,priority:'Low',impact:'Individual',urgency:'Normal',status:'Open',requesterEmail:from.toLowerCase(),requesterName:from.split('@')[0],assignee:'IT Service Desk',firstResponseDueAt:new Date(Date.now()+4*3600000).toISOString(),resolutionDueAt:new Date(Date.now()+24*3600000).toISOString(),messages:[],attachments:[],createdAt:now,updatedAt:now,source:'Email',history:[{at:now,event:`Created from Gmail ${mid}; automatically routed to IT Service Desk`,actor:config.inboundAlias}]};setTickets(rows=>[...rows,ticket]);setMails(rows=>[...rows,{id:crypto.randomUUID(),messageId:mid,direction:'Inbound',from,to:config.inboundAlias,subject,ticketCode,status:'Processed',at:now},{id:crypto.randomUUID(),messageId:`ack-${mid}`,direction:'Outbound',from:config.sendAs,to:from,subject:`[${ticketCode}] Request received`,ticketCode,status:config.state==='Connected'?'Queued':'Prepared — connector not authorised',at:now}]);setDeliveries(rows=>[...rows,{id:crypto.randomUUID(),ticketId:id,ticketCode,event:'Email acknowledgement',channel:'Email',recipient:from,template:'Ticket created',status:'Prepared',createdAt:now}]);onOpenTicket(id)}
 return <section><div className="support-page-heading"><div><span>BUILD 09B · EMAIL CHANNEL</span><h1>Email ticketing & satisfaction</h1><p>Gmail requests, acknowledgements, status messages and closure ratings.</p></div><em>{bridgeHealth?.status==='Healthy'?'Bridge healthy':bridgeHealth?.status||config.state}</em></div><div className="email-tabs">{([['config','Configuration'],['test','Inbound test'],['history','Mail history'],['ratings','Ratings']] as const).map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='config'&&<section className="support-panel email-config"><header><div><h2>Google Workspace channel</h2><small>Alias messages remain visible in the underlying Gmail inbox.</small></div></header><label>Inbound alias<input value={config.inboundAlias} onChange={e=>setConfig({...config,inboundAlias:e.target.value})}/></label><label>Underlying mailbox<input value={config.mailbox} onChange={e=>setConfig({...config,mailbox:e.target.value})}/></label><label>Send-as identity<input value={config.sendAs} onChange={e=>setConfig({...config,sendAs:e.target.value})}/></label><label>Authorised domains<input value={config.domains.join(', ')} onChange={e=>setConfig({...config,domains:e.target.value.split(',').map(v=>v.trim().toLowerCase())})}/></label><label>Poll interval<input type="number" value={config.pollMinutes} onChange={e=>setConfig({...config,pollMinutes:Number(e.target.value)})}/></label><div className="email-warning"><strong>{bridgeHealth?.status==='Healthy'?'Mailbox bridge is active':'Mailbox verification required'}</strong><span>{bridgeHealth?.status==='Healthy'?`Last successful bridge run: ${bridgeHealth.lastSuccessAt?new Date(bridgeHealth.lastSuccessAt).toLocaleString('en-IN'):'recorded'}. Inbound messages and replies are processed by the controlled Gmail bridge.`:'The bridge has not reported a healthy run yet. Verify the Gmail authorization and send-as alias before relying on inbound email tickets.'}</span></div><button className="support-primary" onClick={()=>setConfig({...config,updatedAt:new Date().toISOString(),updatedBy:identityEmail})}>Save configuration</button></section>}
 {tab==='test'&&<section className="support-panel email-ingest"><header><div><h2>Inbound recovery & connector test</h2><small>Validates parsing, duplicate prevention, routing and acknowledgement preparation.</small></div></header><form onSubmit={ingest}><label>Gmail message ID<input value={messageId} onChange={e=>setMessageId(e.target.value)}/></label><label>From<input type="email" required value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="wide">Subject<input required value={subject} onChange={e=>setSubject(e.target.value)}/></label><label className="wide">Body<textarea required value={body} onChange={e=>setBody(e.target.value)}/></label><button className="support-primary">Process email</button></form></section>}
 {tab==='history'&&<Table heads={['Direction','Subject / ticket','From → To','Status','Time']} rows={[...mails].reverse().map(m=><div key={m.id}><strong>{m.direction}</strong><span>{m.subject}<small>{m.ticketCode||m.messageId}</small></span><span>{m.from} → {m.to}</span><em>{m.status}</em><span>{new Date(m.at).toLocaleString('en-IN')}</span></div>)}/>} 
 {tab==='ratings'&&<><section className="email-rating-filters" aria-label="Rating filters"><label>Search ticket or employee<input value={ratingSearch} onChange={e=>setRatingSearch(e.target.value)} placeholder="Ticket number or employee email"/></label><label>Team / owner<select value={ratingTeam} onChange={e=>setRatingTeam(e.target.value)}>{ratingTeams.map(team=><option key={team}>{team}</option>)}</select></label><label>Invitation status<select value={ratingState} onChange={e=>setRatingState(e.target.value as typeof ratingState)}>{['All','Submitted','Awaiting','Expired'].map(state=><option key={state}>{state}</option>)}</select></label><label>Sort by<select value={ratingSort} onChange={e=>setRatingSort(e.target.value as typeof ratingSort)}>{['Recent','Rating: low to high','Rating: high to low'].map(sort=><option key={sort}>{sort}</option>)}</select></label><span>{visibleRatings.length} of {ratings.length} ratings</span></section><Table heads={['Ticket','Employee','Invitation','Stars','Resolved']} ratings rows={visibleRatings.map(r=><div className="ratings" key={r.id}><strong>{r.ticketCode}</strong><span>{r.requesterEmail}</span><span>{r.submittedAt?'Submitted':new Date(r.expiresAt)<new Date()?'Expired':'Awaiting'}</span><span>{r.stars?`${'★'.repeat(r.stars)}${'☆'.repeat(5-r.stars)}`:'—'}</span><span>{r.resolved===undefined?'—':r.resolved?'Yes':'No'}</span></div>)}/></>}</section>}
function Table({heads,rows,ratings=false}:{heads:string[];rows:React.ReactNode[];ratings?:boolean}){return <section className="support-panel email-table"><div className={`head ${ratings?'ratings':''}`}>{heads.map(h=><span>{h}</span>)}</div>{rows.length?rows:<p>No records yet.</p>}</section>}
