import { useMemo, useState } from 'react'
import Icon, { type IconName } from '../../components/Icon'
import { useLocalStore } from '../../lib/localStore'
import './KnowledgeBase.css'

type ArticleStatus = 'Draft' | 'In review' | 'Published' | 'Archived'
type Article = { id:string; code:string; title:string; category:string; summary:string; content:string; keywords:string[]; status:ArticleStatus; version:number; helpful:number; notHelpful:number; views:number; author:string; reviewer?:string; createdAt:string; updatedAt:string; history:{at:string;event:string;actor:string}[] }
type ResolvedTicket = { id:string; code:string; title:string; category:string; description:string; resolutionSummary?:string; status:string }
const categories = ['Email & applications','Network & connectivity','Device or hardware','Access & security','General guidance']
const categoryIcon:Record<string,IconName>={'Email & applications':'mail','Network & connectivity':'network','Device or hardware':'laptop','Access & security':'assurance','General guidance':'requests'}
const seed:Article[]=[
  {id:'kb-vpn',code:'KB-0001',title:'Connect to the company VPN',category:'Network & connectivity',summary:'Securely connect to Glassco systems while working remotely.',content:'Open the approved VPN client, enter your Glassco business email, complete multi-factor verification, and select the company gateway. If connection fails, capture the error before raising a ticket.',keywords:['vpn','remote','network'],status:'Published',version:1,helpful:0,notHelpful:0,views:0,author:'System seed',reviewer:'IT Head',createdAt:'2026-09-01T09:00:00.000Z',updatedAt:'2026-09-01T09:00:00.000Z',history:[]},
  {id:'kb-outlook',code:'KB-0002',title:'Set up Outlook on a new device',category:'Email & applications',summary:'Configure your authorised Microsoft 365 account.',content:'Install the approved Microsoft Outlook application, choose Add account, enter your Glassco email address, and complete company sign-in. Do not add company mail to an unmanaged shared device.',keywords:['outlook','email','microsoft 365'],status:'Published',version:1,helpful:0,notHelpful:0,views:0,author:'System seed',reviewer:'IT Head',createdAt:'2026-09-01T09:00:00.000Z',updatedAt:'2026-09-01T09:00:00.000Z',history:[]},
  {id:'kb-printer',code:'KB-0003',title:'Add a network printer',category:'Device or hardware',summary:'Install an approved office printer on Windows.',content:'Connect to the office network, open Printers & scanners, select Add device, and choose the printer assigned to your location. Contact IT if the approved device is not visible.',keywords:['printer','windows','office'],status:'Published',version:1,helpful:0,notHelpful:0,views:0,author:'System seed',reviewer:'IT Head',createdAt:'2026-09-01T09:00:00.000Z',updatedAt:'2026-09-01T09:00:00.000Z',history:[]},
]
function nextCode(rows:Article[]){return `KB-${String(rows.reduce((n,row)=>Math.max(n,Number(row.code.split('-').at(-1))||0),0)+1).padStart(4,'0')}`}
export default function KnowledgeBase({identityEmail,isServiceAgent,resolvedTickets,onRaiseTicket}:{identityEmail:string;isServiceAgent:boolean;resolvedTickets:ResolvedTicket[];onRaiseTicket:()=>void}){
  const [articles,setArticles]=useLocalStore<Article[]>('connect.support-knowledge.v1',seed)
  const [search,setSearch]=useState('');const [category,setCategory]=useState('All');const [selectedId,setSelectedId]=useState('');const [manage,setManage]=useState(false);const [showEditor,setShowEditor]=useState(false);const [sourceTicket,setSourceTicket]=useState('')
  const [draft,setDraft]=useState({title:'',category:categories[0],summary:'',content:'',keywords:''})
  const visible=useMemo(()=>articles.filter(a=>(isServiceAgent&&manage)||a.status==='Published').filter(a=>category==='All'||a.category===category).filter(a=>{const q=search.trim().toLowerCase();return !q||[a.code,a.title,a.summary,a.content,a.keywords.join(' ')].some(v=>v.toLowerCase().includes(q))}).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),[articles,category,isServiceAgent,manage,search])
  const selected=articles.find(a=>a.id===selectedId)
  function openArticle(id:string){setSelectedId(id);setArticles(rows=>rows.map(a=>a.id===id?{...a,views:a.views+1}:a))}
  function beginFromTicket(id:string){const ticket=resolvedTickets.find(t=>t.id===id);if(!ticket)return;setSourceTicket(id);setDraft({title:ticket.title,category:categories.includes(ticket.category)?ticket.category:categories[0],summary:`Resolution guidance derived from ${ticket.code}.`,content:`Problem\n${ticket.description}\n\nResolution\n${ticket.resolutionSummary||''}`,keywords:ticket.title.toLowerCase().split(/\s+/).slice(0,5).join(', ')});setShowEditor(true)}
  function saveDraft(e:React.FormEvent){e.preventDefault();const now=new Date().toISOString();const source=resolvedTickets.find(t=>t.id===sourceTicket);const article:Article={id:crypto.randomUUID(),code:nextCode(articles),title:draft.title.trim(),category:draft.category,summary:draft.summary.trim(),content:draft.content.trim(),keywords:draft.keywords.split(',').map(v=>v.trim()).filter(Boolean),status:'Draft',version:1,helpful:0,notHelpful:0,views:0,author:identityEmail,createdAt:now,updatedAt:now,history:[{at:now,event:source?`Draft created from resolved ticket ${source.code}`:'Draft created',actor:identityEmail}]};setArticles(rows=>[...rows,article]);setSelectedId(article.id);setShowEditor(false);setSourceTicket('');setDraft({title:'',category:categories[0],summary:'',content:'',keywords:''})}
  function transition(article:Article,status:ArticleStatus){const now=new Date().toISOString();setArticles(rows=>rows.map(a=>a.id===article.id?{...a,status,version:status==='Published'?a.version+1:a.version,reviewer:status==='Published'?identityEmail:a.reviewer,updatedAt:now,history:[...a.history,{at:now,event:`Status changed to ${status}`,actor:identityEmail}]}:a))}
  function feedback(article:Article,helpful:boolean){setArticles(rows=>rows.map(a=>a.id===article.id?{...a,helpful:a.helpful+Number(helpful),notHelpful:a.notHelpful+Number(!helpful)}:a))}
  return <section className="knowledge-base"><div className="support-page-heading"><div><span>BUILD 06 · SELF-SERVICE KNOWLEDGE</span><h1>IT help centre</h1><p>Find approved guidance before raising a support request.</p></div>{isServiceAgent&&<div className="kb-heading-actions"><button type="button" onClick={()=>setManage(!manage)}>{manage?'Employee view':'Manage articles'}</button><button className="support-primary" type="button" onClick={()=>setShowEditor(true)}>New article</button></div>}</div>
    <div className="kb-search"><Icon name="requests" size={20}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search an issue, application or error"/><select value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div>
    {showEditor&&<form className="support-panel kb-editor" onSubmit={saveDraft}><header><h2>Create controlled article draft</h2><button type="button" onClick={()=>setShowEditor(false)}>Close</button></header>{resolvedTickets.length>0&&<label>Start from resolved ticket<select value={sourceTicket} onChange={e=>beginFromTicket(e.target.value)}><option value="">No linked ticket</option>{resolvedTickets.map(t=><option value={t.id} key={t.id}>{t.code} · {t.title}</option>)}</select></label>}<label>Article title<input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Category<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Employee summary<input required value={draft.summary} onChange={e=>setDraft({...draft,summary:e.target.value})}/></label><label className="wide">Approved guidance<textarea required value={draft.content} onChange={e=>setDraft({...draft,content:e.target.value})}/></label><label className="wide">Search keywords<input value={draft.keywords} onChange={e=>setDraft({...draft,keywords:e.target.value})} placeholder="vpn, remote, connection"/></label><button className="support-primary" type="submit">Save draft</button></form>}
    <div className="kb-layout"><div className="kb-results"><div className="kb-result-head"><strong>{visible.length} articles</strong>{manage&&<span>{articles.filter(a=>a.status==='In review').length} awaiting review</span>}</div>{visible.map(article=><button className={selectedId===article.id?'selected':''} type="button" key={article.id} onClick={()=>openArticle(article.id)}><span><Icon name={categoryIcon[article.category]||'requests'} size={21}/></span><div><strong>{article.title}</strong><small>{article.code} · {article.category}{manage?` · ${article.status}`:''}</small><p>{article.summary}</p></div><Icon name="chevron" size={17}/></button>)}{!visible.length&&<div className="support-empty">No matching approved guidance. You can raise a ticket for personalised support.</div>}</div>
      <aside className="support-panel kb-article">{selected?<><header><div><span>{selected.code} · VERSION {selected.version}</span><h2>{selected.title}</h2><small>{selected.category} · Updated {new Date(selected.updatedAt).toLocaleDateString('en-IN')}</small></div>{manage&&<em className={`kb-state ${selected.status.toLowerCase().replace(' ','-')}`}>{selected.status}</em>}</header><p className="kb-summary">{selected.summary}</p><div className="kb-content">{selected.content.split('\n').map((line,i)=><p key={i}>{line||<br/>}</p>)}</div>{manage?<><div className="kb-workflow">{selected.status==='Draft'&&<button type="button" onClick={()=>transition(selected,'In review')}>Submit for review</button>}{selected.status==='In review'&&<button className="support-primary" type="button" onClick={()=>transition(selected,'Published')}>Approve & publish</button>}{selected.status==='Published'&&<button type="button" onClick={()=>transition(selected,'Archived')}>Archive</button>}{selected.status==='Archived'&&<button type="button" onClick={()=>transition(selected,'Draft')}>Restore as draft</button>}</div><h3>Version & approval history</h3>{selected.history.slice().reverse().map(h=><div className="support-history" key={h.at+h.event}><i/><div><strong>{h.event}</strong><small>{new Date(h.at).toLocaleString('en-IN')} · {h.actor}</small></div></div>)}</>:<div className="kb-feedback"><span>Did this solve your issue?</span><button type="button" onClick={()=>feedback(selected,true)}>Yes, solved</button><button type="button" onClick={()=>feedback(selected,false)}>No</button><button className="support-primary" type="button" onClick={onRaiseTicket}>Raise a ticket</button></div>}<footer>{selected.views} views · {selected.helpful} helpful · {selected.notHelpful} not helpful</footer></>:<div className="kb-placeholder"><Icon name="requests" size={34}/><strong>Select an article</strong><span>Approved guidance will open here.</span></div>}</aside></div>
  </section>
}
