import {useEffect,useMemo,useState} from 'react'
import Icon from '../../components/Icon'
import TeamsTeamOverview from './TeamsTeamOverview'
import {subscribeFlowMilestones,subscribeFlowProjects,subscribeFlowSignals,subscribeFlowTasks,subscribeFlowTeams,type FlowMilestoneRecord,type FlowProjectRecord,type FlowSignalRecord,type FlowTaskRecord,type FlowTeamRecord} from '../flow/flowStore'
import './TeamsManagerReview.css'
const today=()=>new Date().toISOString().slice(0,10)
export default function TeamsManagerReview({identityEmail,isLeader,onAllocate,onOpenWork,onOpenProjects,onOpenConversations,onOpenSignals}:{identityEmail:string;isLeader:boolean;onAllocate:()=>void;onOpenWork:()=>void;onOpenProjects:()=>void;onOpenConversations:()=>void;onOpenSignals:()=>void}){
 const [tasks,setTasks]=useState<FlowTaskRecord[]>([]),[teams,setTeams]=useState<FlowTeamRecord[]>([]),[projects,setProjects]=useState<FlowProjectRecord[]>([]),[milestones,setMilestones]=useState<FlowMilestoneRecord[]>([]),[signals,setSignals]=useState<FlowSignalRecord[]>([])
 useEffect(()=>{const a=subscribeFlowTasks(setTasks),b=subscribeFlowTeams(setTeams),c=subscribeFlowProjects(setProjects),d=subscribeFlowMilestones(setMilestones),e=subscribeFlowSignals(setSignals);return()=>{a();b();c();d();e()}},[])
 const managed=teams.filter(team=>isLeader||team.managerEmail===identityEmail),teamIds=new Set(managed.map(team=>team.id)),departmentIds=new Set(managed.map(team=>team.departmentId)),open=tasks.filter(task=>teamIds.has(task.teamId||'')&&task.status!=='Closed'),overdue=open.filter(task=>task.dueDate<today()),blocked=open.filter(task=>task.status==='Blocked'),requests=open.filter(task=>task.title.startsWith('Allocation request:')),openSignals=signals.filter(signal=>teamIds.has(signal.teamId)&&signal.status==='Open'),projectIds=new Set(projects.filter(project=>departmentIds.has(project.departmentId)).map(project=>project.id)),riskMilestones=milestones.filter(item=>projectIds.has(item.projectId)&&item.status!=='Complete'&&(item.status==='Blocked'||item.dueDate<today()))
 const capacity=useMemo(()=>managed.map(team=>{const members=Array.from(new Set([team.managerEmail,...team.memberEmails]));return members.map(email=>({email,team:team.name,count:open.filter(task=>task.teamId===team.id&&task.ownerEmail===email).length}))}).flat().sort((a,b)=>b.count-a.count).slice(0,5),[managed,open])
 return <div className="teams-manager-review"><section className="manager-review-head"><div><small>MANAGER DAILY REVIEW</small><h1>Control delivery in ten minutes</h1><p>Review only the work that requires a decision, reassignment or intervention today.</p></div><button className="teams-primary" onClick={onAllocate}><Icon name="plus" size={16}/>Allocate work</button></section><section className="manager-review-kpis"><button onClick={onAllocate}><b>{requests.length}</b><span>Allocation requests</span><small>Awaiting manager review</small></button><button onClick={onOpenWork} className={overdue.length?'risk':''}><b>{overdue.length}</b><span>Overdue work</span><small>Needs a date or plan</small></button><button onClick={onOpenSignals} className={blocked.length||openSignals.length?'risk':''}><b>{blocked.length+openSignals.length}</b><span>Open blockers</span><small>Tasks and escalations</small></button><button onClick={onOpenProjects} className={riskMilestones.length?'risk':''}><b>{riskMilestones.length}</b><span>Project risks</span><small>Late or blocked milestones</small></button></section><section className="manager-review-grid"><section><header><div><small>REVIEW QUEUE</small><h2>What needs your decision</h2></div><button onClick={onAllocate}>Open inbox <Icon name="arrow" size={14}/></button></header>{[...requests,...blocked,...overdue.filter(task=>task.status!=='Blocked')].slice(0,6).map(task=><article key={task.id}><div><b>{task.title.replace(/^Allocation request:\s*/i,'')}</b><small>{task.ownerEmail} · Due {task.dueDate}</small></div><em className={task.title.startsWith('Allocation request:')?'request':task.status==='Blocked'?'blocked':'overdue'}>{task.title.startsWith('Allocation request:')?'Review':task.status==='Blocked'?'Blocked':'Overdue'}</em></article>)}{!requests.length&&!blocked.length&&!overdue.length&&<p>Nothing requires an immediate manager decision.</p>}</section><section><header><div><small>CAPACITY WATCH</small><h2>Where to rebalance work</h2></div><button onClick={onOpenWork}>Open board <Icon name="arrow" size={14}/></button></header>{capacity.map(item=><article key={`${item.team}-${item.email}`}><div><b>{item.email}</b><small>{item.team}</small></div><strong className={item.count>5?'risk':''}>{item.count} open</strong></article>)}{!capacity.length&&<p>No active team work is assigned yet.</p>}</section></section><TeamsTeamOverview onAllocate={onAllocate} onOpenWork={onOpenWork} onOpenProjects={onOpenProjects} onOpenConversations={onOpenConversations} onOpenSignals={onOpenSignals}/></div>
}
