import {useEffect,useMemo,useState} from 'react'
import Icon from '../../components/Icon'
import {saveFlowSignal,subscribeFlowSignals,subscribeFlowTeams,type FlowSignalRecord,type FlowTeamRecord} from '../flow/flowStore'
import './TeamsSignals.css'

export default function TeamsSignals({identityEmail,isLeader,onNotice}:{identityEmail:string;isLeader:boolean;onNotice:(text:string)=>void}){
 const[teams,setTeams]=useState<FlowTeamRecord[]>([]),[signals,setSignals]=useState<FlowSignalRecord[]>([]),[teamId,setTeamId]=useState(''),[kind,setKind]=useState<FlowSignalRecord['kind']>('Blocker'),[title,setTitle]=useState(''),[detail,setDetail]=useState(''),[dueDate,setDueDate]=useState(''),[severity,setSeverity]=useState<NonNullable<FlowSignalRecord['severity']>>('Medium')
 useEffect(()=>{const a=subscribeFlowTeams(setTeams),b=subscribeFlowSignals(setSignals);return()=>{a();b()}},[])
 const visibleTeams=teams.filter(team=>isLeader||team.managerEmail===identityEmail||team.memberEmails.includes(identityEmail)),team=visibleTeams.find(item=>item.id===teamId)||visibleTeams[0],visible=useMemo(()=>signals.filter(item=>item.teamId===team?.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),[signals,team?.id])
 const create=async()=>{if(!team||!title.trim()||!detail.trim()){onNotice('Enter a clear title and context before recording a decision or blocker.');return}const now=new Date().toISOString(),record:FlowSignalRecord={id:crypto.randomUUID(),teamId:team.id,kind,title:title.trim(),detail:detail.trim(),requesterEmail:identityEmail,managerEmail:team.managerEmail,participantEmails:Array.from(new Set([identityEmail,team.managerEmail,...team.memberEmails])),status:'Open',dueDate:dueDate||undefined,severity:kind==='Blocker'?severity:undefined,createdAt:now,updatedAt:now};try{await saveFlowSignal(record,identityEmail,`${kind} recorded`);setTitle('');setDetail('');setDueDate('');onNotice(`${kind} recorded and visible to the team manager.`)}catch{onNotice('The item could not be saved.')}}
 const resolve=async(signal:FlowSignalRecord)=>{const resolution=window.prompt(`How was this ${signal.kind.toLowerCase()} resolved or confirmed?`);if(!resolution?.trim()){onNotice('A resolution note is required to close a governed item.');return}try{await saveFlowSignal({...signal,status:'Resolved',resolution:resolution.trim(),updatedAt:new Date().toISOString()},identityEmail,`${signal.kind} resolved`);onNotice(`${signal.kind} resolved with a recorded outcome.`)}catch{onNotice('The resolution could not be saved.')}}
 if(!team)return <section className="signals-empty"><Icon name="allocation" size={28}/><h2>No delivery team is available</h2><p>Create a team before recording decisions or blockers.</p></section>
 return <section className="signals-workspace"><header><div><small>DECISIONS & BLOCKERS</small><h1>Make delivery risks and decisions visible</h1><p>Capture the issue, accountable owner and expected resolution—not just a chat message.</p></div><label>Team<select value={team.id} onChange={event=>setTeamId(event.target.value)}>{visibleTeams.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></header><section className="signal-form"><label>Record type<select value={kind} onChange={event=>setKind(event.target.value as FlowSignalRecord['kind'])}><option>Blocker</option><option>Decision</option><option>Dependency</option></select></label><label>Title<input value={title} onChange={event=>setTitle(event.target.value)} placeholder="What needs a decision or action?"/></label><label>Context<textarea value={detail} onChange={event=>setDetail(event.target.value)} placeholder="State impact, required decision or the next action."/></label><div><label>Target resolution<input type="date" value={dueDate} onChange={event=>setDueDate(event.target.value)}/></label>{kind==='Blocker'&&<label>Severity<select value={severity} onChange={event=>setSeverity(event.target.value as NonNullable<FlowSignalRecord['severity']>)}><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></label>}<button className="teams-primary" onClick={()=>void create()}>Record {kind}</button></div></section><section className="signal-list"><header><div><small>TEAM REGISTER</small><h2>{visible.filter(item=>item.status==='Open').length} open items</h2></div></header>{visible.map(item=><article key={item.id}><div><em className={`${item.kind.toLowerCase()} ${item.severity?.toLowerCase()||''}`}>{item.kind}{item.severity?` · ${item.severity}`:''}</em><b>{item.title}</b><p>{item.detail}</p><small>Owner: {item.managerEmail}{item.dueDate?` · Target: ${item.dueDate}`:''}</small>{item.resolution&&<span>Resolution: {item.resolution}</span>}</div><strong className={item.status.toLowerCase()}>{item.status}</strong>{item.status==='Open'&&<button onClick={()=>void resolve(item)}>Resolve</button>}</article>)}{!visible.length&&<p className="signals-none">No decisions or blockers have been recorded for this team.</p>}</section></section>
}
