import {useEffect,useMemo,useState} from 'react'
import Icon from '../../components/Icon'
import {saveFlowCheckIn,subscribeFlowCheckIns,subscribeFlowTeams,type FlowCheckInRecord,type FlowTeamRecord} from '../flow/flowStore'
import './TeamsCheckIn.css'
const weekStart=()=>{const date=new Date(),day=date.getDay(),offset=(day+6)%7;date.setDate(date.getDate()-offset);return date.toISOString().slice(0,10)}
export default function TeamsCheckIn({identityEmail,onNotice}:{identityEmail:string;onNotice:(text:string)=>void}){
 const [teams,setTeams]=useState<FlowTeamRecord[]>([]),[checkIns,setCheckIns]=useState<FlowCheckInRecord[]>([]),[teamId,setTeamId]=useState(''),[completed,setCompleted]=useState(''),[nextPriority,setNextPriority]=useState(''),[blocker,setBlocker]=useState(''),[support,setSupport]=useState('')
 useEffect(()=>{const a=subscribeFlowTeams(setTeams),b=subscribeFlowCheckIns(setCheckIns);return()=>{a();b()}},[])
 const myTeams=teams.filter(team=>team.memberEmails.includes(identityEmail)||team.managerEmail===identityEmail),team=myTeams.find(item=>item.id===teamId)||myTeams[0],week=weekStart(),visible=useMemo(()=>team?checkIns.filter(item=>item.teamId===team.id&&item.weekOf===week).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)):[],[checkIns,team?.id,week])
 const save=async()=>{if(!team||!nextPriority.trim()){onNotice('Select a team and enter your next priority before saving.');return};const now=new Date().toISOString();try{await saveFlowCheckIn({id:`CHECKIN-${team.id}-${identityEmail.replace(/[^a-z0-9]/gi,'-')}-${week}`,teamId:team.id,authorEmail:identityEmail,participantEmails:team.memberEmails,completed:completed.trim(),nextPriority:nextPriority.trim(),blocker:blocker.trim(),supportNeeded:support.trim(),status:blocker.trim()?'At risk':'On track',weekOf:week,createdAt:now,updatedAt:now},identityEmail);setCompleted('');setNextPriority('');setBlocker('');setSupport('');onNotice('Weekly check-in saved for your team.')}catch{onNotice('The weekly check-in could not be saved.')}}
 return <div className="teams-checkin"><section className="checkin-head"><div><small>WEEKLY TEAM CHECK-IN</small><h1>Progress, blockers and support</h1><p>A focused update for the team manager—without separate reports or chat threads.</p></div><label>Team<select value={team?.id||''} onChange={e=>setTeamId(e.target.value)}>{myTeams.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></section>{team?<><section className="checkin-form"><header><div><span>MY UPDATE · WEEK OF {week}</span><h2>Four concise fields</h2></div></header><label>Completed this week<textarea value={completed} onChange={e=>setCompleted(e.target.value)} placeholder="What was completed or materially progressed?"/></label><label>Next priority *<textarea value={nextPriority} onChange={e=>setNextPriority(e.target.value)} placeholder="What will you focus on next?"/></label><label>Blocker<textarea value={blocker} onChange={e=>setBlocker(e.target.value)} placeholder="Leave empty if nothing is blocking you."/></label><label>Support needed<textarea value={support} onChange={e=>setSupport(e.target.value)} placeholder="Decision, resource, information or another team's support."/></label><footer><button className="teams-primary" onClick={()=>void save()}>Save check-in</button></footer></section><section className="checkin-feed"><header><div><small>TEAM UPDATES</small><h2>This week’s check-ins</h2></div><span>{visible.length} submitted</span></header>{visible.map(item=>{const health=item.status||(item.blocker?'At risk':'On track');return <article key={item.id}><div className="checkin-avatar">{item.authorEmail.slice(0,1).toUpperCase()}</div><div><b>{item.authorEmail}</b><small>Next: {item.nextPriority}</small>{item.blocker&&<p><strong>Blocker:</strong> {item.blocker}</p>}{item.supportNeeded&&<p><strong>Support:</strong> {item.supportNeeded}</p>}</div><em className={health.toLowerCase().replaceAll(' ','-')}>{health}</em></article>})}{!visible.length&&<div className="checkin-empty"><Icon name="history" size={27}/><b>No check-ins submitted this week.</b><span>Start with your own concise update above.</span></div>}</section></>:<section className="checkin-empty"><Icon name="masters" size={27}/><b>You are not assigned to a team yet.</b><span>A team manager must first add you to a delivery team.</span></section>}</div>
}
