import {useEffect,useMemo,useState} from 'react'
import Icon from '../../components/Icon'
import TeamsCycles from './TeamsCycles'
import {saveFlowTask,subscribeFlowMilestones,subscribeFlowProjects,subscribeFlowTeams,type FlowMilestoneRecord,type FlowProjectRecord,type FlowTaskRecord,type FlowTeamRecord} from '../flow/flowStore'
import './TeamsSprintPlanner.css'

const today=()=>new Date().toISOString().slice(0,10)
export default function TeamsSprintPlanner({identityEmail,isLeader,onNotice}:{identityEmail:string;isLeader:boolean;onNotice:(text:string)=>void}){
 const [teams,setTeams]=useState<FlowTeamRecord[]>([]),[projects,setProjects]=useState<FlowProjectRecord[]>([]),[milestones,setMilestones]=useState<FlowMilestoneRecord[]>([])
 const [teamId,setTeamId]=useState(''),[projectId,setProjectId]=useState(''),[milestoneId,setMilestoneId]=useState(''),[ownerEmail,setOwnerEmail]=useState(''),[dueDate,setDueDate]=useState(today()),[title,setTitle]=useState('')
 useEffect(()=>{const a=subscribeFlowTeams(setTeams),b=subscribeFlowProjects(setProjects),c=subscribeFlowMilestones(setMilestones);return()=>{a();b();c()}},[])
 const visibleTeams=teams.filter(team=>isLeader||team.managerEmail===identityEmail||team.memberEmails.includes(identityEmail)),team=visibleTeams.find(item=>item.id===teamId)||visibleTeams[0]
 const visibleProjects=useMemo(()=>projects.filter(project=>isLeader||project.ownerEmail===identityEmail||project.participantEmails.includes(identityEmail)),[projects,identityEmail,isLeader])
 const selectedProject=visibleProjects.find(project=>project.id===projectId)||visibleProjects[0]
 const availableMilestones=useMemo(()=>milestones.filter(item=>item.projectId===selectedProject?.id&&item.status!=='Complete').sort((a,b)=>a.dueDate.localeCompare(b.dueDate)),[milestones,selectedProject?.id])
 const selectedMilestone=availableMilestones.find(item=>item.id===milestoneId)||availableMilestones[0]
 useEffect(()=>{if(selectedMilestone){setTitle(value=>value||selectedMilestone.title);setDueDate(selectedMilestone.dueDate)}},[selectedMilestone?.id])
 const create=async()=>{if(!team||!selectedProject||!selectedMilestone||!ownerEmail||!title.trim()){onNotice('Choose a team, project milestone, owner and task title first.');return}const now=new Date().toISOString(),task:FlowTaskRecord={id:`TASK-${Date.now()}`,title:title.trim(),description:`Sprint task from ${selectedProject.title}: ${selectedMilestone.title}`,departmentId:team.departmentId,ownerEmail,participantEmails:Array.from(new Set([ownerEmail,team.managerEmail,...team.memberEmails])),status:'Not started',priority:'Medium',dueDate,teamId:team.id,projectId:selectedProject.id,managerEmail:team.managerEmail,workOrigin:'Allocated',createdBy:identityEmail,createdAt:now,updatedAt:now};try{await saveFlowTask(task,identityEmail,'Daily sprint task created');setTitle('');onNotice('Sprint task created and assigned. It is now visible in the member’s allocated task list and team work board.')}catch{onNotice('Sprint task could not be saved.')} }
 return <div className="teams-sprints"><section className="sprint-head"><div><small>DAILY SPRINTS</small><h1>Turn project delivery into today’s work</h1><p>Create a focused, assigned task directly from a project milestone. The task remains linked to its project and appears in the team work board.</p></div></section><section className="sprint-create"><header><div><small>CREATE SPRINT TASK</small><h2>Plan one accountable next step</h2></div><span>Project → milestone → assigned task</span></header><div className="sprint-fields"><label>Team<select value={team?.id||''} onChange={event=>setTeamId(event.target.value)}><option value="">Select team</option>{visibleTeams.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Project<select value={selectedProject?.id||''} onChange={event=>{setProjectId(event.target.value);setMilestoneId('');setTitle('')}}><option value="">Select project</option>{visibleProjects.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Milestone<select value={selectedMilestone?.id||''} onChange={event=>{setMilestoneId(event.target.value);setTitle('')}}><option value="">Select milestone</option>{availableMilestones.map(item=><option key={item.id} value={item.id}>{item.phase?`${item.phase} · `:''}{item.title}</option>)}</select></label><label>Assign to<select value={ownerEmail} onChange={event=>setOwnerEmail(event.target.value)}><option value="">Select team member</option>{team&&Array.from(new Set([team.managerEmail,...team.memberEmails])).map(email=><option key={email} value={email}>{email}</option>)}</select></label><label className="sprint-task-title">Today’s task<input value={title} onChange={event=>setTitle(event.target.value)} placeholder="Specific task to complete today"/></label><label>Expected close<input type="date" min={today()} value={dueDate} onChange={event=>setDueDate(event.target.value)}/></label></div>{selectedMilestone&&<div className="sprint-context"><Icon name="reports" size={16}/><span><b>{selectedMilestone.title}</b>{selectedMilestone.dependency?` · Depends on ${selectedMilestone.dependency}`:''}</span><em>{selectedMilestone.status}</em></div>}<footer><button className="teams-primary" onClick={()=>void create()}><Icon name="plus" size={16}/>Create assigned sprint task</button></footer></section><TeamsCycles identityEmail={identityEmail} isLeader={isLeader} onNotice={onNotice}/></div>
}
