import {useEffect,useState} from 'react'
import Icon from '../../components/Icon'
import TeamsSprintPlanner from './TeamsSprintPlanner'
import {saveFlowSprintMom,saveFlowTask,subscribeFlowCycles,subscribeFlowTeams,type FlowCycleRecord,type FlowSprintMomRecord,type FlowTaskRecord,type FlowTeamRecord} from '../flow/flowStore'
import './TeamsSprintMom.css'
const today=()=>new Date().toISOString().slice(0,10)
export default function TeamsSprintMom({identityEmail,isLeader,onNotice}:{identityEmail:string;isLeader:boolean;onNotice:(text:string)=>void}){
 const[teams,setTeams]=useState<FlowTeamRecord[]>([]),[cycles,setCycles]=useState<FlowCycleRecord[]>([]),[teamId,setTeamId]=useState(''),[completed,setCompleted]=useState(''),[decisions,setDecisions]=useState(''),[blockers,setBlockers]=useState(''),[carry,setCarry]=useState(''),[next,setNext]=useState(''),[action,setAction]=useState(''),[owner,setOwner]=useState(''),[due,setDue]=useState(today())
 useEffect(()=>{const a=subscribeFlowTeams(setTeams),b=subscribeFlowCycles(setCycles);return()=>{a();b()}},[])
 const visible=teams.filter(team=>isLeader||team.managerEmail===identityEmail||team.memberEmails.includes(identityEmail)),team=visible.find(item=>item.id===teamId)||visible[0],cycle=cycles.find(item=>item.teamId===team?.id&&item.status==='Active')||cycles.find(item=>item.teamId===team?.id),members=team?Array.from(new Set([team.managerEmail,...team.memberEmails])):[]
 const save=async()=>{if(!team||!next.trim()){onNotice('Select a team and record next sprint priorities.');return}const now=new Date().toISOString(),participants=members;try{const mom:FlowSprintMomRecord={id:`MOM-${Date.now()}`,teamId:team.id,cycleId:cycle?.id,authorEmail:identityEmail,participantEmails:participants,completed:completed.trim(),decisions:decisions.trim(),blockers:blockers.trim(),carryForward:carry.trim(),nextPriorities:next.trim(),createdAt:now};await saveFlowSprintMom(mom,identityEmail);if(action.trim()&&owner){const task:FlowTaskRecord={id:`TASK-${Date.now()}`,title:action.trim(),description:`Sprint MoM action · ${cycle?.name||'No active cycle'}`,departmentId:team.departmentId,ownerEmail:owner,participantEmails:participants,status:'Not started',priority:'Medium',dueDate:due,teamId:team.id,cycleId:cycle?.id,managerEmail:team.managerEmail,workOrigin:'Allocated',createdBy:identityEmail,createdAt:now,updatedAt:now};await saveFlowTask(task,identityEmail,'Sprint MoM action created')}setCompleted('');setDecisions('');setBlockers('');setCarry('');setNext('');setAction('');onNotice(action.trim()&&owner?'Sprint MoM saved and action created.':'Sprint MoM saved.')}catch{onNotice('Sprint MoM could not be saved.')}}
 return <div className="teams-sprint-mom"><section className="mom-head"><div><small>SPRINT MOM</small><h1>Capture the sprint outcome</h1><p>Keep decisions, carry-forward work and next priorities with the delivery cycle—not in scattered notes.</p></div><label>Team<select value={team?.id||''} onChange={event=>setTeamId(event.target.value)}><option value="">Select team</option>{visible.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></section><section className="mom-form"><header><div><small>MINUTES OF MEETING</small><h2>{cycle?.name||'No active delivery cycle'}</h2></div><span>{cycle?`${cycle.startDate} to ${cycle.endDate}`:'Start a delivery cycle to attach this MoM.'}</span></header><div className="mom-fields"><label>Completed<textarea value={completed} onChange={e=>setCompleted(e.target.value)} placeholder="Key progress since the last sprint"/></label><label>Decisions made<textarea value={decisions} onChange={e=>setDecisions(e.target.value)} placeholder="What was agreed or approved?"/></label><label>Blockers / dependencies<textarea value={blockers} onChange={e=>setBlockers(e.target.value)} placeholder="What needs follow-through?"/></label><label>Carry-forward work<textarea value={carry} onChange={e=>setCarry(e.target.value)} placeholder="What did not finish and why?"/></label><label className="mom-next">Next sprint priorities *<textarea value={next} onChange={e=>setNext(e.target.value)} placeholder="The committed focus for the next sprint"/></label></div><div className="mom-action"><b>Convert an agreed action into a real task <small>optional</small></b><input value={action} onChange={e=>setAction(e.target.value)} placeholder="Action agreed in this MoM"/><select value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Owner</option>{members.map(email=><option key={email} value={email}>{email}</option>)}</select><input type="date" value={due} onChange={e=>setDue(e.target.value)}/></div><footer><button className="teams-primary" onClick={()=>void save()}><Icon name="check" size={16}/>Save sprint MoM</button></footer></section><TeamsSprintPlanner identityEmail={identityEmail} isLeader={isLeader} onNotice={onNotice}/></div>
}
