import {useEffect,useMemo,useState} from 'react'
import Icon from '../../components/Icon'
import {useLocalStore} from '../../lib/localStore'
import {subscribeFlowCycles,subscribeFlowProjects,subscribeFlowTasks,subscribeFlowTeams,type FlowCycleRecord,type FlowProjectRecord,type FlowTaskRecord,type FlowTeamRecord} from '../flow/flowStore'
import './TeamsTeamOverview.css'
import './TeamsTeamOverviewCommand.css'
import './TeamsTeamOverviewRefinement.css'
type User={id:string;name:string;email?:string;status?:string}
type Department={id:string;name:string}
export default function TeamsTeamOverview({onAllocate,onOpenWork,onOpenProjects,onOpenConversations,onOpenSignals}:{onAllocate:()=>void;onOpenWork:()=>void;onOpenProjects:()=>void;onOpenConversations:()=>void;onOpenSignals:()=>void}){
 const[teams,setTeams]=useState<FlowTeamRecord[]>([]),[tasks,setTasks]=useState<FlowTaskRecord[]>([]),[projects,setProjects]=useState<FlowProjectRecord[]>([]),[cycles,setCycles]=useState<FlowCycleRecord[]>([]),[teamId,setTeamId]=useState('')
 const[users]=useLocalStore<User[]>('itms.users.v1',[]),[departments]=useLocalStore<Department[]>('itms.departments.v1',[])
 useEffect(()=>{const a=subscribeFlowTeams(setTeams),b=subscribeFlowTasks(setTasks),c=subscribeFlowProjects(setProjects),d=subscribeFlowCycles(setCycles);return()=>{a();b();c();d()}},[])
 const active=teams.filter(team=>team.status==='Active'),team=active.find(item=>item.id===teamId)||active[0],person=(email:string)=>users.find(user=>user.email===email)?.name||email,department=(id:string)=>departments.find(item=>item.id===id)?.name||'Department'
 const work=useMemo(()=>team?tasks.filter(task=>task.teamId===team.id):[],[tasks,team?.id]),open=work.filter(item=>item.status!=='Closed'),today=new Date().toISOString().slice(0,10),attention=[...open.filter(item=>item.status==='Blocked'),...open.filter(item=>item.dueDate<today)],cycle=cycles.filter(item=>item.teamId===team?.id).sort((a,b)=>b.startDate.localeCompare(a.startDate))[0],linkedProjects=projects.filter(project=>team&&project.departmentId===team.departmentId&&project.status!=='Complete')
 if(!team)return <section className="team-overview-empty"><Icon name="allocation" size={28}/><h2>No delivery team is available yet</h2><p>Create a governed team from the Teams directory before assigning work.</p></section>
 return <section className="team-overview"><header className="team-overview-head"><div><span>TEAM WORKSPACE · {department(team.departmentId).toUpperCase()}</span><h1>{team.name}</h1><p>Manager: <b>{person(team.managerEmail)}</b> · {team.memberEmails.length} members · {cycle?cycle.name:'No active cycle'}</p></div><div><select value={team.id} onChange={event=>setTeamId(event.target.value)}>{active.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button onClick={onAllocate}><Icon name="plus" size={16}/>Allocate work</button></div></header><section className="team-workspace-launches"><button onClick={onOpenConversations}><Icon name="mail" size={18}/><span><b>Team conversations</b><small>Updates, mentions and quick coordination</small></span><Icon name="arrow" size={14}/></button><button onClick={onOpenWork}><Icon name="dashboard" size={18}/><span><b>Formal work board</b><small>Owned work, due dates and review</small></span><Icon name="arrow" size={14}/></button><button onClick={onOpenSignals}><Icon name="alerts" size={18}/><span><b>Decisions & blockers</b><small>Escalations needing a response</small></span><Icon name="arrow" size={14}/></button></section>
 <section className="team-overview-kpis"><article><small>Open work</small><b>{open.length}</b><span>Across this team</span></article><article><small>Due this week</small><b>{open.filter(item=>item.dueDate<=new Date(Date.now()+7*86400000).toISOString().slice(0,10)).length}</b><span>Requires planned action</span></article><article className={attention.length?'attention':''}><small>Needs attention</small><b>{attention.length}</b><span>Blocked or overdue</span></article><article><small>Capacity</small><b>{open.length>team.memberEmails.length*4?'Review':'Balanced'}</b><span>{team.memberEmails.length} delivery members</span></article></section>
 <div className="team-overview-grid"><section className="team-overview-priorities"><header><div><span>PRIORITY WORK</span><h2>What needs action now</h2></div><button onClick={onAllocate}>Add work <Icon name="arrow" size={14}/></button></header>{open.filter(item=>item.priority==='High'||item.status==='Blocked'||item.dueDate<=new Date(Date.now()+7*86400000).toISOString().slice(0,10)).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,6).map(item=><article key={item.id}><div><b>{item.title}</b><small>{person(item.ownerEmail)} · Due {item.dueDate}</small></div><em className={item.status.toLowerCase().replaceAll(' ','-')}>{item.status}</em></article>)}{!open.length&&<p>No open delivery work has been allocated yet.</p>}</section><aside className="team-overview-brief"><span>TEAM BRIEF</span><h2>Cycle and delivery context</h2><dl><div><dt>Current cycle</dt><dd>{cycle?cycle.name:'Not planned'}</dd></div><div><dt>Cycle dates</dt><dd>{cycle?cycle.startDate+' – '+cycle.endDate:'Set a delivery cycle'}</dd></div><div><dt>Active projects</dt><dd>{linkedProjects.length}</dd></div><div><dt>Unresolved exceptions</dt><dd className={attention.length?'issue':''}>{attention.length||'None'}</dd></div></dl><button onClick={onAllocate}>Allocate a work item <Icon name="arrow" size={14}/></button></aside></div>
 <section className="team-overview-projects"><header><div><span>PROJECT DELIVERY</span><h2>Projects this team is contributing to</h2></div><button onClick={onOpenProjects}>Open projects <Icon name="arrow" size={14}/></button></header>{linkedProjects.slice(0,4).map(project=><article key={project.id}><div><b>{project.title}</b><small>Owner: {person(project.ownerEmail)} · Target {project.targetDate}</small></div><span><i><b style={{width:project.progress+'%'}}/></i>{project.progress}%</span><em className={project.status.toLowerCase().replaceAll(' ','-')}>{project.status}</em></article>)}{!linkedProjects.length&&<p>No active department projects are linked to this team yet.</p>}</section><section className="team-overview-members"><header><div><span>TEAM CAPACITY</span><h2>Ownership at a glance</h2></div><button onClick={onOpenWork}>Inspect workload <Icon name="arrow" size={14}/></button></header>{team.memberEmails.map(email=>{const owned=open.filter(item=>item.ownerEmail===email);return <article key={email}><i>{person(email).slice(0,1).toUpperCase()}</i><div><b>{person(email)}</b><small>{email===team.managerEmail?'Team manager':'Team member'}</small></div><span>{owned.length} open work</span><em className={owned.length>5?'review':''}>{owned.length>5?'Review workload':'Available'}</em></article>})}</section>
 </section>
}
