import {useEffect,useMemo,useState} from 'react'
import Icon from '../../components/Icon'
import {useLocalStore} from '../../lib/localStore'
import {subscribeFlowProjects,subscribeFlowSignals,subscribeFlowTasks,subscribeFlowTeams,type FlowProjectRecord,type FlowSignalRecord,type FlowTaskRecord,type FlowTeamRecord} from '../flow/flowStore'
import './TeamsGlobalSearch.css'
type User={id:string;name:string;email?:string};type Asset={id?:string;assetId?:string;inventoryCode?:string;serialNumber?:string;name?:string;model?:string;status?:string}
type Result={id:string;kind:string;title:string;detail:string;open:()=>void}
export default function TeamsGlobalSearch({onOpenPeople,onOpenTeam,onOpenWork,onOpenProjects,onOpenSignals}:{onOpenPeople:()=>void;onOpenTeam:()=>void;onOpenWork:()=>void;onOpenProjects:()=>void;onOpenSignals:()=>void}){
 const[query,setQuery]=useState(''),[active,setActive]=useState(false),[users]=useLocalStore<User[]>('itms.users.v1',[]),[assets]=useLocalStore<Asset[]>('itms.assets.v1',[]),[tasks,setTasks]=useState<FlowTaskRecord[]>([]),[teams,setTeams]=useState<FlowTeamRecord[]>([]),[projects,setProjects]=useState<FlowProjectRecord[]>([]),[signals,setSignals]=useState<FlowSignalRecord[]>([])
 useEffect(()=>{const a=subscribeFlowTasks(setTasks),b=subscribeFlowTeams(setTeams),c=subscribeFlowProjects(setProjects),d=subscribeFlowSignals(setSignals);return()=>{a();b();c();d()}},[])
 const results=useMemo<Result[]>(()=>{const q=query.trim().toLowerCase();if(!q)return[];return[...users.map(item=>({id:`person:${item.id}`,kind:'Person',title:item.name,detail:item.email||'Employee',open:onOpenPeople})),...teams.map(item=>({id:`team:${item.id}`,kind:'Team',title:item.name,detail:`Manager: ${item.managerEmail}`,open:onOpenTeam})),...tasks.map(item=>({id:`task:${item.id}`,kind:'Work item',title:item.title,detail:`${item.status} · ${item.ownerEmail}`,open:onOpenWork})),...projects.map(item=>({id:`project:${item.id}`,kind:'Project',title:item.title,detail:`${item.status} · target ${item.targetDate}`,open:onOpenProjects})),...signals.map(item=>({id:`signal:${item.id}`,kind:item.kind,title:item.title,detail:`${item.status} · ${item.managerEmail}`,open:onOpenSignals})),...assets.map(item=>({id:`asset:${item.id||item.assetId||item.inventoryCode}`,kind:'ITMS asset',title:item.inventoryCode||item.assetId||item.name||'Asset',detail:`${item.model||item.serialNumber||'Asset record'} · ${item.status||'Active'}`,open:()=>window.location.assign('/?app=itms')}))].filter(item=>`${item.title} ${item.detail} ${item.kind}`.toLowerCase().includes(q)).slice(0,8)},[query,users,assets,tasks,teams,projects,signals,onOpenPeople,onOpenTeam,onOpenWork,onOpenProjects,onOpenSignals])
 const choose=(result:Result)=>{result.open();setQuery('');setActive(false)}
 return <div className="teams-command-search"><label><Icon name="search" size={17}/><input value={query} onFocus={()=>setActive(true)} onChange={event=>{setQuery(event.target.value);setActive(true)}} placeholder="Search people, work, projects or assets"/></label>{active&&query.trim()&&<section>{results.map(result=><button key={result.id} onMouseDown={event=>event.preventDefault()} onClick={()=>choose(result)}><i><Icon name={result.kind==='Person'?'masters':result.kind==='ITMS asset'?'inventory':result.kind==='Project'?'reports':result.kind==='Blocker'?'alerts':'history'} size={15}/></i><span><small>{result.kind}</small><b>{result.title}</b><em>{result.detail}</em></span><Icon name="arrow" size={14}/></button>)}{!results.length&&<p>No matching people, work, projects, decisions or assets.</p>}</section>}</div>
}
