import {useEffect,useMemo,useState} from 'react'
import Icon from '../../components/Icon'
import TeamsMyWork from './TeamsMyWork'
import {saveFlowSignal,subscribeFlowTasks,subscribeFlowTeams,type FlowTaskRecord,type FlowTeamRecord} from '../flow/flowStore'
import './TeamsMyFocus.css'
const today=()=>new Date().toISOString().slice(0,10)
export default function TeamsMyFocus({identityName,identityEmail,onAllocate,onNotice}:{identityName:string;identityEmail:string;onAllocate:()=>void;onNotice:(text:string)=>void}){
 const [tasks,setTasks]=useState<FlowTaskRecord[]>([]),[teams,setTeams]=useState<FlowTeamRecord[]>([])
 useEffect(()=>{const a=subscribeFlowTasks(setTasks),b=subscribeFlowTeams(setTeams);return()=>{a();b()}},[])
 const mine=useMemo(()=>tasks.filter(task=>task.ownerEmail===identityEmail&&task.status!=='Closed').sort((a,b)=>a.dueDate.localeCompare(b.dueDate)),[tasks,identityEmail]),todayTasks=mine.filter(task=>task.dueDate===today()),overdue=mine.filter(task=>task.dueDate<today()),review=mine.filter(task=>task.status==='Awaiting review'),blocked=mine.filter(task=>task.status==='Blocked'),focus=useMemo(()=>[...overdue,...blocked,...todayTasks.filter(task=>!overdue.includes(task)&&!blocked.includes(task)),...review].slice(0,5),[overdue,blocked,todayTasks,review])
 const capacity=mine.length>7?'Overloaded':mine.length>4?'Watch load':'Balanced',teamFor=(task:FlowTaskRecord)=>teams.find(team=>team.id===task.teamId)
 const escalate=async(task:FlowTaskRecord)=>{const team=teamFor(task);if(!team){onNotice('This personal task has no team manager to escalate to.');return}const detail=window.prompt('Describe the risk, dependency or decision you need from the manager.');if(!detail?.trim())return;const now=new Date().toISOString();try{await saveFlowSignal({id:crypto.randomUUID(),teamId:team.id,kind:'Blocker',title:task.title,detail:detail.trim(),requesterEmail:identityEmail,managerEmail:team.managerEmail,ownerEmail:team.managerEmail,participantEmails:Array.from(new Set([identityEmail,team.managerEmail,...team.memberEmails])),status:'Open',dueDate:task.dueDate,severity:task.priority==='High'?'High':'Medium',sourceRecordId:task.id,createdAt:now,updatedAt:now},identityEmail,'Task escalated from My tasks');onNotice('Task risk raised for manager action.')}catch{onNotice('The task could not be escalated.')}}
 return <div className="teams-my-focus"><section className="myfocus-head"><div><small>MY DAILY FOCUS</small><h1>Make today manageable</h1><p>Start with what is due, blocked or waiting for review—then work through your full task list below.</p></div><span className={capacity.toLowerCase().replace(' ','-')}>{capacity} · {mine.length} open</span></section><section className="myfocus-kpis"><article className={overdue.length?'risk':''}><b>{overdue.length}</b><span>Overdue</span></article><article><b>{todayTasks.length}</b><span>Due today</span></article><article><b>{review.length}</b><span>Waiting for review</span></article><article className={blocked.length?'risk':''}><b>{blocked.length}</b><span>Blocked</span></article></section><section className="myfocus-list"><header><div><small>PRIORITY QUEUE</small><h2>Start here</h2></div><span>{focus.length} items</span></header>{focus.map(task=><article key={task.id}><div><em className={task.status.toLowerCase().replaceAll(' ','-')}>{task.status}</em><b>{task.title}</b><small>Due {task.dueDate} · {task.priority} priority</small></div><button onClick={()=>void escalate(task)}>Raise risk <Icon name="arrow" size={13}/></button></article>)}{!focus.length&&<p>You have no due, blocked or review work right now. Use your personal plan to shape the next priority.</p>}</section><TeamsMyWork identityName={identityName} identityEmail={identityEmail} onAllocate={onAllocate} onNotice={onNotice}/></div>
}
