import {useEffect,useMemo,useState} from 'react'
import Icon from '../../components/Icon'
import {saveFlowMilestone,subscribeFlowMilestones,subscribeFlowProjects,type FlowMilestoneRecord,type FlowProjectRecord} from '../flow/flowStore'
import './TeamsPhaseControl.css'
const today=()=>new Date().toISOString().slice(0,10)
const defaults=['Discovery','Build','Review','Rollout']
export default function TeamsPhaseControl({identityEmail,isLeader,onNotice}:{identityEmail:string;isLeader:boolean;onNotice:(text:string)=>void}){
 const [projects,setProjects]=useState<FlowProjectRecord[]>([]),[milestones,setMilestones]=useState<FlowMilestoneRecord[]>([]),[projectId,setProjectId]=useState(''),[phase,setPhase]=useState('Discovery'),[title,setTitle]=useState(''),[owner,setOwner]=useState(''),[dueDate,setDueDate]=useState('')
 useEffect(()=>{const a=subscribeFlowProjects(setProjects),b=subscribeFlowMilestones(setMilestones);return()=>{a();b()}},[])
 const visible=projects.filter(project=>isLeader||project.ownerEmail===identityEmail||project.participantEmails.includes(identityEmail)),project=visible.find(item=>item.id===projectId)||visible[0],projectMilestones=useMemo(()=>milestones.filter(item=>item.projectId===project?.id).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)),[milestones,project?.id]),participants=project?Array.from(new Set([project.ownerEmail,...project.participantEmails])):[],phases=Array.from(new Set([...defaults,...projectMilestones.map(item=>item.phase||'Delivery')]))
 const create=async()=>{if(!project||!title.trim()||!owner||!dueDate){onNotice('Choose a project, phase owner, milestone title and target date.');return}const now=new Date().toISOString(),record:FlowMilestoneRecord={id:`MS-${Date.now()}`,projectId:project.id,phase:phase.trim()||'Delivery',phaseOwnerEmail:owner,ownerEmail:owner,participantEmails:Array.from(new Set([owner,...participants])),title:title.trim(),dueDate,status:'Not started',createdAt:now,updatedAt:now};try{await saveFlowMilestone(record,identityEmail,'Phase milestone created');setTitle('');setDueDate('');onNotice('Phase milestone created with an accountable phase owner.')}catch{onNotice('The phase milestone could not be saved.')}}
 return <div className="teams-phase-control"><section className="phase-head"><div><small>PROJECT PHASE CONTROL</small><h1>Own each stage of delivery</h1><p>Group milestones by phase, name one phase owner, and see the real completion position before a project is marked healthy.</p></div><label>Project<select value={project?.id||''} onChange={event=>setProjectId(event.target.value)}><option value="">Select project</option>{visible.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label></section>{project?<><section className="phase-form"><label>Phase<input list="phase-list" value={phase} onChange={event=>setPhase(event.target.value)} placeholder="Discovery"/><datalist id="phase-list">{defaults.map(item=><option key={item} value={item}/>)}</datalist></label><label>Phase owner<select value={owner} onChange={event=>setOwner(event.target.value)}><option value="">Select accountable owner</option>{participants.map(email=><option key={email} value={email}>{email}</option>)}</select></label><label>Milestone<input value={title} onChange={event=>setTitle(event.target.value)} placeholder="Clear delivery point"/></label><label>Target date<input type="date" min={today()} value={dueDate} onChange={event=>setDueDate(event.target.value)}/></label><button className="teams-primary" onClick={()=>void create()}><Icon name="plus" size={16}/>Add phase milestone</button></section><section className="phase-summary">{phases.map(name=>{const items=projectMilestones.filter(item=>(item.phase||'Delivery')===name),completed=items.filter(item=>item.status==='Complete').length,blocked=items.some(item=>item.status==='Blocked'),phaseOwner=items.find(item=>item.phaseOwnerEmail)?.phaseOwnerEmail||items[0]?.ownerEmail||'Not assigned',percent=items.length?Math.round(completed/items.length*100):0;return <article key={name}><header><div><small>PHASE</small><h2>{name}</h2></div><em className={blocked?'blocked':percent===100?'complete':''}>{blocked?'Blocked':percent===100?'Complete':`${percent}% complete`}</em></header><p><b>Owner:</b> {phaseOwner}</p><div className="phase-progress"><i style={{width:`${percent}%`}}/></div><span>{completed} of {items.length} milestones complete</span><ul>{items.map(item=><li key={item.id}><b>{item.title}</b><small>{item.ownerEmail} · {item.dueDate} · {item.status}</small></li>)}{!items.length&&<li className="phase-empty">No milestones in this phase yet.</li>}</ul></article>})}</section></>:<section className="phase-empty-state"><Icon name="reports" size={28}/><b>No project available</b><span>Create a department project first, then organise its milestones into phases.</span></section>}</div>
}
