import {useEffect,useMemo,useState} from 'react'
import Icon from '../../components/Icon'
import TeamsSignals from './TeamsSignals'
import {saveFlowSignal,subscribeFlowSignals,subscribeFlowTeams,type FlowSignalRecord,type FlowTeamRecord} from '../flow/flowStore'
import './TeamsEscalationBoard.css'
const today=()=>new Date().toISOString().slice(0,10)
export default function TeamsEscalationBoard({identityEmail,isLeader,onNotice}:{identityEmail:string;isLeader:boolean;onNotice:(text:string)=>void}){
 const [signals,setSignals]=useState<FlowSignalRecord[]>([]),[teams,setTeams]=useState<FlowTeamRecord[]>([]),[selectedId,setSelectedId]=useState(''),[owner,setOwner]=useState(''),[dueDate,setDueDate]=useState(''),[resolution,setResolution]=useState('')
 useEffect(()=>{const a=subscribeFlowSignals(setSignals),b=subscribeFlowTeams(setTeams);return()=>{a();b()}},[])
 const open=useMemo(()=>signals.filter(item=>item.status==='Open'&&(isLeader||item.managerEmail===identityEmail||item.requesterEmail===identityEmail)).sort((a,b)=>(a.dueDate||'9999').localeCompare(b.dueDate||'9999')),[signals,identityEmail,isLeader]),signal=open.find(item=>item.id===selectedId)||open[0],team=teams.find(item=>item.id===signal?.teamId),eligible=team?Array.from(new Set([team.managerEmail,...team.memberEmails])):[]
 useEffect(()=>{if(signal){setOwner(signal.ownerEmail||signal.managerEmail);setDueDate(signal.dueDate||today());setResolution('')}},[signal?.id])
 const saveOwner=async()=>{if(!signal||!owner){onNotice('Choose an accountable owner before saving.');return}try{await saveFlowSignal({...signal,ownerEmail:owner,dueDate:dueDate||undefined,updatedAt:new Date().toISOString()},identityEmail,'Escalation owner and target updated');setSelectedId('');onNotice('Owner and target resolution date updated.')}catch{onNotice('The escalation assignment could not be saved.')}}
 const resolve=async()=>{if(!signal||!resolution.trim()){onNotice('Record the decision or resolution before closing this item.');return}try{await saveFlowSignal({...signal,ownerEmail:owner||signal.ownerEmail||signal.managerEmail,dueDate:dueDate||undefined,status:'Resolved',resolution:resolution.trim(),updatedAt:new Date().toISOString()},identityEmail,`${signal.kind} resolved with outcome`);setSelectedId('');onNotice('Escalation resolved with a recorded outcome.')}catch{onNotice('The resolution could not be saved.')}}
 return <div className="teams-escalations"><section className="escalation-head"><div><small>ESCALATION CONTROL</small><h1>Close blockers and decisions with accountability</h1><p>Every open item has one owner, a target date, and a recorded outcome before it can be resolved.</p></div><span>{open.length} open</span></section><section className="escalation-layout"><section className="escalation-list"><header><small>OPEN ITEMS</small><h2>Needs a decision or follow-through</h2></header>{open.map(item=><button key={item.id} onClick={()=>setSelectedId(item.id)} className={item.id===signal?.id?'selected':''}><div><em className={item.kind.toLowerCase()}>{item.kind}{item.severity?` · ${item.severity}`:''}</em><b>{item.title}</b><small>Owner: {item.ownerEmail||item.managerEmail} · {item.dueDate||'No target set'}</small></div></button>)}{!open.length&&<p>No open escalations. New blockers, dependencies and decisions will appear here.</p>}</section><section className="escalation-action">{signal&&team?<><header><div><small>TAKE OWNERSHIP</small><h2>{signal.title}</h2></div></header><p>{signal.detail}</p><div className="escalation-fields"><label>Accountable owner<select value={owner} onChange={event=>setOwner(event.target.value)}>{eligible.map(email=><option key={email} value={email}>{email}</option>)}</select></label><label>Target resolution<input type="date" min={today()} value={dueDate} onChange={event=>setDueDate(event.target.value)}/></label><label className="escalation-resolution">Decision / resolution note<textarea value={resolution} onChange={event=>setResolution(event.target.value)} placeholder="What was decided, changed or completed?"/></label></div><footer><button onClick={()=>void saveOwner()}>Save owner & target</button><button className="teams-primary" onClick={()=>void resolve()}><Icon name="check" size={16}/>Resolve with outcome</button></footer></>:<div className="escalation-empty"><Icon name="check" size={28}/><b>Select an open escalation</b><span>Assign its accountable owner and close it with an auditable outcome.</span></div>}</section></section><TeamsSignals identityEmail={identityEmail} isLeader={isLeader} onNotice={onNotice}/></div>
}
