import {useEffect,useMemo,useState} from 'react'
import Icon from '../../components/Icon'
import FlowActionRegister from '../flow/FlowActionRegister'
import {saveFlowTask,subscribeFlowProjects,subscribeFlowTasks,subscribeFlowTeams,type FlowProjectRecord,type FlowTaskRecord,type FlowTeamRecord} from '../flow/flowStore'
import './TeamsAllocationInbox.css'

const today=()=>new Date().toISOString().slice(0,10)
const requestTitle=(title:string)=>title.replace(/^Allocation request:\s*/i,'')
export default function TeamsAllocationInbox({identityEmail,isLeader,onNotice}:{identityEmail:string;isLeader:boolean;onNotice:(text:string)=>void}){
 const [tasks,setTasks]=useState<FlowTaskRecord[]>([]),[teams,setTeams]=useState<FlowTeamRecord[]>([]),[projects,setProjects]=useState<FlowProjectRecord[]>([]),[selectedId,setSelectedId]=useState(''),[ownerEmail,setOwnerEmail]=useState(''),[dueDate,setDueDate]=useState(today()),[priority,setPriority]=useState<FlowTaskRecord['priority']>('Medium'),[projectId,setProjectId]=useState(''),[note,setNote]=useState('')
 useEffect(()=>{const a=subscribeFlowTasks(setTasks),b=subscribeFlowTeams(setTeams),c=subscribeFlowProjects(setProjects);return()=>{a();b();c()}},[])
 const requests=useMemo(()=>tasks.filter(task=>task.title.startsWith('Allocation request:')&&(isLeader||task.managerEmail===identityEmail||task.ownerEmail===identityEmail)).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)),[tasks,identityEmail,isLeader])
 const request=requests.find(item=>item.id===selectedId)||requests[0],team=teams.find(item=>item.id===request?.teamId),eligible=team?Array.from(new Set([team.managerEmail,...team.memberEmails])):[]
 useEffect(()=>{if(request){setOwnerEmail('');setDueDate(request.dueDate||today());setPriority(request.priority);setProjectId(request.projectId||'');setNote('')}},[request?.id])
 const assign=async()=>{if(!request||!team||!ownerEmail){onNotice('Choose a named team member before assigning this request.');return}try{await saveFlowTask({...request,title:requestTitle(request.title),description:[request.description,note.trim()&&`Manager note: ${note.trim()}`].filter(Boolean).join('\n'),ownerEmail,projectId:projectId||undefined,dueDate,priority,status:'Not started',workOrigin:'Allocated',updatedAt:new Date().toISOString()},identityEmail,'Allocation request approved and assigned');setSelectedId('');onNotice('Request approved and assigned. It is now in the member’s Allocated to me list.')}catch{onNotice('The allocation could not be saved.')}}
 const returnForClarification=async()=>{if(!request||!note.trim()){onNotice('Add a short clarification note before returning this request.');return}try{await saveFlowTask({...request,title:requestTitle(request.title),ownerEmail:request.createdBy,description:[request.description,`Manager clarification requested: ${note.trim()}`].filter(Boolean).join('\n'),status:'Blocked',workOrigin:'Allocated',updatedAt:new Date().toISOString()},identityEmail,'Allocation request returned for clarification');setSelectedId('');onNotice('Request returned to the sender with your clarification note.')}catch{onNotice('The request could not be returned.')}}
 return <div className="teams-allocation-inbox"><section className="allocation-head"><div><small>MANAGER ALLOCATION INBOX</small><h1>Review and allocate next-day plans</h1><p>Make a clear decision on submitted work before it becomes a team commitment.</p></div><span>{requests.length} awaiting review</span></section><section className="allocation-layout"><section className="allocation-requests"><header><div><small>SUBMITTED PLANS</small><h2>Requests awaiting a decision</h2></div></header>{requests.map(item=><button key={item.id} className={item.id===request?.id?'selected':''} onClick={()=>setSelectedId(item.id)}><div><b>{requestTitle(item.title)}</b><small>Submitted by {item.createdBy} · {item.teamId||'No team'}</small></div><time>{item.createdAt.slice(0,10)}</time></button>)}{!requests.length&&<p>No allocation requests are waiting. Submitted next-day plans will appear here.</p>}</section><section className="allocation-decision">{request&&team?<><header><div><small>REVIEW REQUEST</small><h2>{requestTitle(request.title)}</h2><p>Submitted by {request.createdBy}</p></div></header><div className="allocation-description">{request.description?.replace(/^Submitted by.*?\n?/,'')||'No additional detail was provided.'}</div><div className="allocation-fields"><label>Assign to<select value={ownerEmail} onChange={event=>setOwnerEmail(event.target.value)}><option value="">Select team member</option>{eligible.map(email=><option key={email} value={email}>{email}</option>)}</select></label><label>Expected close<input type="date" min={today()} value={dueDate} onChange={event=>setDueDate(event.target.value)}/></label><label>Priority<select value={priority} onChange={event=>setPriority(event.target.value as FlowTaskRecord['priority'])}><option>High</option><option>Medium</option><option>Low</option></select></label><label>Project link <small>optional</small><select value={projectId} onChange={event=>setProjectId(event.target.value)}><option value="">Routine team work</option>{projects.filter(project=>project.departmentId===team.departmentId).map(project=><option key={project.id} value={project.id}>{project.title}</option>)}</select></label><label className="allocation-note">Manager note <small>required if returning</small><textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Add context, priority guidance or clarification required."/></label></div><footer><button onClick={()=>void returnForClarification()}>Return for clarification</button><button className="teams-primary" onClick={()=>void assign()}><Icon name="check" size={16}/>Approve & assign</button></footer></>:<div className="allocation-empty"><Icon name="allocation" size={28}/><b>Select an allocation request</b><span>Its owner, date, priority and project link will be set here.</span></div>}</section></section><FlowActionRegister identityEmail={identityEmail} isLeader={isLeader} onNotice={onNotice}/></div>
}
