import {useEffect,useState} from 'react'
import Icon from '../../components/Icon'
import TeamsCheckIn from './TeamsCheckIn'
import {saveFlowCheckIn,saveFlowSignal,saveFlowTask,subscribeFlowTeams,type FlowCheckInRecord,type FlowSignalRecord,type FlowTaskRecord,type FlowTeamRecord} from '../flow/flowStore'
import './TeamsDailyUpdate.css'

const today=()=>new Date().toISOString().slice(0,10)
const weekStart=()=>{const date=new Date(),offset=(date.getDay()+6)%7;date.setDate(date.getDate()-offset);return date.toISOString().slice(0,10)}
export default function TeamsDailyUpdate({identityEmail,onNotice}:{identityEmail:string;onNotice:(text:string)=>void}){
 const [teams,setTeams]=useState<FlowTeamRecord[]>([]),[teamId,setTeamId]=useState(''),[completed,setCompleted]=useState(''),[plan,setPlan]=useState(''),[blocker,setBlocker]=useState(''),[mode,setMode]=useState<'personal'|'manager'|'blocker'>('personal')
 useEffect(()=>subscribeFlowTeams(setTeams),[])
 const myTeams=teams.filter(team=>team.memberEmails.includes(identityEmail)||team.managerEmail===identityEmail),team=myTeams.find(item=>item.id===teamId)||myTeams[0]
 const save=async()=>{if(!team||!plan.trim()){onNotice('Select a team and enter tomorrow’s plan first.');return}const now=new Date().toISOString(),participants=Array.from(new Set([team.managerEmail,...team.memberEmails]));try{const checkIn:FlowCheckInRecord={id:`DAILY-${team.id}-${identityEmail.replace(/[^a-z0-9]/gi,'-')}-${today()}`,teamId:team.id,authorEmail:identityEmail,participantEmails:participants,completed:completed.trim(),nextPriority:plan.trim(),blocker:blocker.trim(),supportNeeded:'',status:blocker.trim()?'At risk':'On track',weekOf:weekStart(),createdAt:now,updatedAt:now};await saveFlowCheckIn(checkIn,identityEmail,'Daily progress update saved');if(mode==='personal'){const task:FlowTaskRecord={id:`TASK-${Date.now()}`,title:plan.trim(),description:'Personal next-day plan',departmentId:team.departmentId,ownerEmail:identityEmail,participantEmails:participants,status:'Not started',priority:'Medium',dueDate:today(),teamId:team.id,managerEmail:team.managerEmail,workOrigin:'Personal plan',createdBy:identityEmail,createdAt:now,updatedAt:now};await saveFlowTask(task,identityEmail,'Personal next-day task created');onNotice('Daily update saved and tomorrow’s plan added to My day plan.')}else if(mode==='manager'){const task:FlowTaskRecord={id:`TASK-${Date.now()}`,title:`Allocation request: ${plan.trim()}`,description:`Submitted by ${identityEmail} as a next-day allocation request.`,departmentId:team.departmentId,ownerEmail:team.managerEmail,participantEmails:participants,status:'Not started',priority:'Medium',dueDate:today(),teamId:team.id,managerEmail:team.managerEmail,workOrigin:'Allocated',createdBy:identityEmail,createdAt:now,updatedAt:now};await saveFlowTask(task,identityEmail,'Next-day plan submitted for manager allocation');onNotice('Daily update saved and plan submitted to the manager for allocation.')}else{const signal:FlowSignalRecord={id:`SIGNAL-${Date.now()}`,teamId:team.id,kind:'Blocker',title:plan.trim(),detail:blocker.trim()||'Next-day plan cannot proceed without support.',requesterEmail:identityEmail,managerEmail:team.managerEmail,participantEmails:participants,status:'Open',severity:'Medium',createdAt:now,updatedAt:now};await saveFlowSignal(signal,identityEmail,'Daily blocker raised');onNotice('Daily update saved and blocker raised for the manager.')}setCompleted('');setPlan('');setBlocker('')}catch{onNotice('The daily update could not be saved. Please try again.')}}
 return <div className="teams-daily-update"><section className="daily-head"><small>DAILY CLOSE-OUT</small><h1>Progress today, a clear plan for tomorrow</h1><p>Keep day-to-day work practical. Decide whether tomorrow’s plan remains yours, needs manager allocation, or requires a blocker to be resolved.</p></section><section className="daily-form"><header><div><small>MY DAILY UPDATE</small><h2>Close the loop</h2></div><label>Team<select value={team?.id||''} onChange={event=>setTeamId(event.target.value)}><option value="">Select team</option>{myTeams.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></header><div className="daily-fields"><label>Progress today<textarea value={completed} onChange={event=>setCompleted(event.target.value)} placeholder="What moved forward or was completed?"/></label><label>Tomorrow’s plan *<textarea value={plan} onChange={event=>setPlan(event.target.value)} placeholder="State one clear, achievable next step."/></label><label>Blocker or support needed <small>optional</small><textarea value={blocker} onChange={event=>setBlocker(event.target.value)} placeholder="What could prevent the plan from moving?"/></label></div><fieldset><legend>Where should tomorrow’s plan go?</legend><label><input type="radio" checked={mode==='personal'} onChange={()=>setMode('personal')}/><span><b>My day plan</b><small>Create a personal task in my own task list.</small></span></label><label><input type="radio" checked={mode==='manager'} onChange={()=>setMode('manager')}/><span><b>Manager allocation</b><small>Send it to the manager for review and formal assignment.</small></span></label><label><input type="radio" checked={mode==='blocker'} onChange={()=>setMode('blocker')}/><span><b>Raise a blocker</b><small>Create a visible blocker for the team manager.</small></span></label></fieldset><footer><button className="teams-primary" onClick={()=>void save()}><Icon name="check" size={16}/>Save daily update</button></footer></section><TeamsCheckIn identityEmail={identityEmail} onNotice={onNotice}/></div>
}
