import {useEffect,useMemo,useState} from 'react'
import Icon from '../../components/Icon'
import {useLocalStore} from '../../lib/localStore'
import {subscribeFlowCheckIns,subscribeFlowProjects,subscribeFlowTasks,subscribeFlowTeams,type FlowCheckInRecord,type FlowProjectRecord,type FlowTaskRecord,type FlowTeamRecord} from '../flow/flowStore'
import './TeamsPeople.css'
import './TeamsPeopleOverrides.css'
type User={id:string;employeeCode?:string;name:string;email?:string;departmentId?:string;status?:string;designation?:string;jobTitle?:string;reportsToId?:string;managerId?:string}
type Department={id:string;name:string;status?:string}
export default function TeamsPeople({identityEmail}:{identityEmail:string}){
 const[users]=useLocalStore<User[]>('itms.users.v1',[]),[departments]=useLocalStore<Department[]>('itms.departments.v1',[])
 const[teams,setTeams]=useState<FlowTeamRecord[]>([]),[tasks,setTasks]=useState<FlowTaskRecord[]>([]),[projects,setProjects]=useState<FlowProjectRecord[]>([]),[checkIns,setCheckIns]=useState<FlowCheckInRecord[]>([]),[query,setQuery]=useState(''),[departmentId,setDepartmentId]=useState('all'),[selected,setSelected]=useState<User|null>(null)
 useEffect(()=>{const a=subscribeFlowTeams(setTeams),b=subscribeFlowTasks(setTasks),c=subscribeFlowProjects(setProjects),d=subscribeFlowCheckIns(setCheckIns);return()=>{a();b();c();d()}},[])
 const people=users.filter(user=>user.status!=='Inactive'&&user.email),department=(id?:string)=>departments.find(item=>item.id===id)?.name||'Not mapped'
 const manager=(user:User)=>people.find(person=>person.id===(user.reportsToId||user.managerId))?.name||'Not mapped'
 const visible=useMemo(()=>people.filter(user=>{const text=(user.name+' '+(user.email||'')+' '+(user.designation||user.jobTitle||'')).toLowerCase();return text.includes(query.toLowerCase())&&(departmentId==='all'||user.departmentId===departmentId)}),[people,query,departmentId])
 const work=(email?:string)=>tasks.filter(task=>task.ownerEmail===email&&task.status!=='Closed')
 const teamNames=(email?:string)=>teams.filter(team=>team.status==='Active'&&(team.managerEmail===email||team.memberEmails.includes(email||''))).map(team=>team.name)
 const selectedWork=work(selected?.email),selectedProjects=projects.filter(project=>project.ownerEmail===selected?.email||project.participantEmails?.includes(selected?.email||'')),selectedChecks=checkIns.filter(check=>check.authorEmail===selected?.email).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))
 return <section className="teams-people">
  <header className="people-head"><div><span>ITMS-LINKED PEOPLE DIRECTORY</span><h1>People, ownership and capacity</h1><p>Employee identity and reporting line remain governed in ITMS. Teams adds delivery participation and workload visibility.</p></div><div className="people-current"><i>{identityEmail.slice(0,1).toUpperCase()}</i><span>Signed in as<br/><b>{identityEmail}</b></span></div></header>
  <section className="people-tools"><label><Icon name="empty" size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search name, employee ID, email or designation"/></label><select value={departmentId} onChange={event=>setDepartmentId(event.target.value)}><option value="all">All departments</option>{departments.filter(item=>item.status!=='Inactive').map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><span>{visible.length} people</span></section>
  <section className="people-grid">{visible.map(person=>{const load=work(person.email),joined=teamNames(person.email);return <button className="person-card" key={person.id} onClick={()=>setSelected(person)}><i>{person.name.slice(0,1).toUpperCase()}</i><div className="person-card-title"><b>{person.employeeCode?person.employeeCode+' · ':''}{person.name}</b><small>{person.designation||person.jobTitle||'Employee'}</small></div><span className="person-department">{department(person.departmentId)}</span><div className="person-card-stats"><span><b>{joined.length}</b> teams</span><span><b>{load.length}</b> open work</span></div><em className={load.length>5?'review':'balanced'}>{load.length>5?'Review workload':'Balanced'}</em><Icon name="arrow" size={15}/></button>})}</section>
  {!visible.length&&<div className="people-empty"><Icon name="masters" size={27}/><b>No employees match this view.</b><span>Employee records come directly from the ITMS User Master.</span></div>}
  {selected&&<div className="people-scrim" onMouseDown={()=>setSelected(null)}><aside className="people-profile" onMouseDown={event=>event.stopPropagation()}><header><button onClick={()=>setSelected(null)}>×</button><i>{selected.name.slice(0,1).toUpperCase()}</i><span>EMPLOYEE WORK PROFILE</span><h2>{selected.name}</h2><p>{selected.designation||selected.jobTitle||'Employee'} · {department(selected.departmentId)}</p><small>{selected.email} · Reports to {manager(selected)}</small></header><div className="profile-kpis"><article><small>Open work</small><b>{selectedWork.length}</b></article><article><small>Teams</small><b>{teamNames(selected.email).length}</b></article><article><small>Projects</small><b>{selectedProjects.length}</b></article></div><section><h3>Currently assigned</h3>{selectedWork.length?selectedWork.slice(0,6).map(task=><article className="profile-row" key={task.id}><div><b>{task.title}</b><small>{task.status} · Due {task.dueDate}</small></div><em className={task.priority.toLowerCase()}>{task.priority}</em></article>):<p className="profile-empty">No open work is assigned.</p>}</section><section><h3>Team membership</h3>{teamNames(selected.email).length?<div className="profile-pills">{teamNames(selected.email).map(team=><span key={team}>{team}</span>)}</div>:<p className="profile-empty">Not yet added to a delivery team.</p>}</section><section><h3>Projects and recent check-ins</h3>{selectedProjects.slice(0,3).map(project=><article className="profile-row" key={project.id}><div><b>{project.title}</b><small>{project.status} · Target {project.targetDate}</small></div></article>)}{selectedChecks[0]&&<article className="profile-checkin"><b>Latest check-in</b><p>{selectedChecks[0].nextPriority}</p></article>}{!selectedProjects.length&&!selectedChecks.length&&<p className="profile-empty">No projects or check-ins are available yet.</p>}</section></aside></div>}
 </section>
}
