import {useEffect,useMemo,useState} from 'react'
import Icon from '../../components/Icon'
import {useLocalStore} from '../../lib/localStore'
import {subscribeFlowProjects,subscribeFlowSignals,subscribeFlowTasks,type FlowProjectRecord,type FlowSignalRecord,type FlowTaskRecord} from '../flow/flowStore'
import './TeamsAttentionInbox.css'
import './TeamsAttentionRefinement.css'
type ChannelMessage={id:string;body:string;authorEmail:string;channel:string;replyTo?:string}
type Attention={id:string;kind:'Task'|'Review'|'Blocker'|'Decision'|'Project'|'Mention';title:string;detail:string;priority:'Critical'|'High'|'Medium';lane:'Overdue'|'Today'|'Waiting for you'|'Later';open:()=>void}
const lanes:Attention['lane'][]=['Overdue','Today','Waiting for you','Later']
export default function TeamsAttentionInbox({identityEmail,onOpenWork,onOpenSignals,onOpenProjects,onOpenConversations}:{identityEmail:string;onOpenWork:()=>void;onOpenSignals:()=>void;onOpenProjects:()=>void;onOpenConversations:()=>void}){
 const[tasks,setTasks]=useState<FlowTaskRecord[]>([]),[signals,setSignals]=useState<FlowSignalRecord[]>([]),[projects,setProjects]=useState<FlowProjectRecord[]>([]),[messages]=useLocalStore<ChannelMessage[]>('teams.channel-messages.v1',[]),[read,setRead]=useState<string[]>([]),[snoozed,setSnoozed]=useState<string[]>([])
 useEffect(()=>{const a=subscribeFlowTasks(setTasks),b=subscribeFlowSignals(setSignals),c=subscribeFlowProjects(setProjects);return()=>{a();b();c()}},[])
 const today=new Date().toISOString().slice(0,10),items=useMemo<Attention[]>(()=>[
 ...tasks.filter(task=>task.ownerEmail===identityEmail&&task.status!=='Closed').map(task=>({id:`task:${task.id}`,kind:(task.status==='Awaiting review'?'Review':'Task') as Attention['kind'],title:task.title,detail:task.status==='Awaiting review'?'Review is waiting for your confirmation':`Due ${task.dueDate} · ${task.status}`,priority:(task.status==='Blocked'||task.dueDate<today?'High':task.priority) as Attention['priority'],lane:(task.dueDate<today?'Overdue':task.dueDate===today?'Today':task.status==='Awaiting review'?'Waiting for you':'Later') as Attention['lane'],open:onOpenWork})),
 ...signals.filter(item=>item.status==='Open'&&(item.managerEmail===identityEmail||item.requesterEmail===identityEmail||item.participantEmails.includes(identityEmail))).map(item=>({id:`signal:${item.id}`,kind:(item.kind==='Decision'?'Decision':'Blocker') as Attention['kind'],title:item.title,detail:item.kind==='Decision'?'Decision needs your confirmation':`${item.severity||'Medium'} impact · ${item.dueDate?`target ${item.dueDate}`:'set a target date'}`,priority:(item.severity==='Critical'||item.severity==='High'?'High':'Medium') as Attention['priority'],lane:(item.dueDate&&item.dueDate<today?'Overdue':item.kind==='Decision'?'Waiting for you':'Today') as Attention['lane'],open:onOpenSignals})),
 ...projects.filter(item=>item.ownerEmail===identityEmail&&item.status!=='On track'&&item.status!=='Complete').map(item=>({id:`project:${item.id}`,kind:'Project' as const,title:item.title,detail:`Project is ${item.status.toLowerCase()} · target ${item.targetDate}`,priority:item.status==='At risk'?'High':'Medium' as Attention['priority'],lane:'Later' as Attention['lane'],open:onOpenProjects})),
 ...messages.filter(item=>!item.replyTo&&item.authorEmail!==identityEmail&&item.body.toLowerCase().includes('@'+identityEmail.split('@')[0].toLowerCase())).map(item=>({id:`mention:${item.id}`,kind:'Mention' as Attention['kind'],title:`Mention in #${item.channel}`,detail:`${item.authorEmail}: ${item.body.slice(0,110)}`,priority:'Medium' as Attention['priority'],lane:'Waiting for you' as Attention['lane'],open:onOpenConversations}))
 ].sort((a,b)=>({Critical:0,High:1,Medium:2}[a.priority]-{Critical:0,High:1,Medium:2}[b.priority])),[tasks,signals,projects,messages,identityEmail,today,onOpenWork,onOpenSignals,onOpenProjects,onOpenConversations])
 const visible=items.filter(item=>!read.includes(item.id)&&!snoozed.includes(item.id)),urgent=visible.filter(item=>item.lane==='Overdue'||item.lane==='Today')
 return <section className="attention-inbox"><header><div><small>MY ATTENTION</small><h1>Your next best actions</h1><p>Focus on what needs a decision, update or follow-through today.</p></div><button onClick={()=>setRead(items.map(item=>item.id))}>Mark all read</button></header><section className="attention-focus"><div><b>{urgent.length}</b><span>actions for today</span></div><p>{urgent.length?'Start with the overdue and time-sensitive work below.':'You have no urgent actions. Review items waiting for you or plan upcoming work.'}</p><button onClick={onOpenWork}>Open my work <Icon name="arrow" size={14}/></button></section><section className="attention-kpis"><article><b>{visible.filter(item=>item.lane==='Overdue').length}</b><span>Overdue</span></article><article><b>{visible.filter(item=>item.lane==='Waiting for you').length}</b><span>Waiting for you</span></article><article><b>{visible.filter(item=>item.kind==='Blocker'||item.kind==='Decision').length}</b><span>Decisions & blockers</span></article></section><section className="attention-lanes">{lanes.map(lane=>{const group=visible.filter(item=>item.lane===lane);return <section key={lane}><header><h2>{lane}</h2><span>{group.length}</span></header>{group.map(item=><article key={item.id}><i className={item.kind.toLowerCase()}><Icon name={item.kind==='Project'?'reports':item.kind==='Blocker'?'alerts':item.kind==='Decision'?'check':'history'} size={17}/></i><div><em className={item.priority.toLowerCase()}>{item.priority}</em><b>{item.title}</b><p>{item.detail}</p></div><button onClick={item.open}>Open <Icon name="arrow" size={14}/></button><button className="attention-snooze" onClick={()=>setSnoozed(current=>[...current,item.id])}>Snooze</button></article>)}{!group.length&&<p className="attention-none">Nothing here.</p>}</section>})}</section>{!visible.length&&<div className="attention-empty"><Icon name="check" size={28}/><b>You are up to date.</b><span>No task, decision, blocker or project risk currently requires your attention.</span></div>}</section>
}
