import {useEffect,useMemo,useState} from 'react'
import Icon from '../../components/Icon'
import {saveFlowMilestone,subscribeFlowMilestones,subscribeFlowProjects,type FlowMilestoneRecord,type FlowProjectRecord} from '../flow/flowStore'
import './TeamsProjects.css'

const today=()=>new Date().toISOString().slice(0,10)
const statusClass=(status:string)=>status.toLowerCase().replaceAll(' ','-')

export default function TeamsProjects({identityEmail,onNotice}:{identityEmail:string;onNotice:(text:string)=>void}){
 const [projects,setProjects]=useState<FlowProjectRecord[]>([]),[milestones,setMilestones]=useState<FlowMilestoneRecord[]>([]),[selectedId,setSelectedId]=useState('')
 const [phase,setPhase]=useState(''),[title,setTitle]=useState(''),[dueDate,setDueDate]=useState(''),[dependency,setDependency]=useState('')
 useEffect(()=>subscribeFlowProjects(setProjects),[]);useEffect(()=>subscribeFlowMilestones(setMilestones),[])
 const ordered=useMemo(()=>[...projects].sort((a,b)=>a.targetDate.localeCompare(b.targetDate)),[projects])
 useEffect(()=>{if(!selectedId&&ordered[0])setSelectedId(ordered[0].id)},[ordered,selectedId])
 const project=ordered.find(row=>row.id===selectedId), projectMilestones=useMemo(()=>milestones.filter(row=>row.projectId===selectedId).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)),[milestones,selectedId])
 const addMilestone=async()=>{if(!project)return;if(!title.trim()||!dueDate){onNotice('Enter a milestone title and target date first.');return}const now=new Date().toISOString();const record:FlowMilestoneRecord={id:`MS-${Date.now()}`,projectId:project.id,phase:phase.trim()||'Delivery',title:title.trim(),ownerEmail:identityEmail,participantEmails:Array.from(new Set([identityEmail,...(project.participantEmails||[])])),dueDate,status:'Not started',dependency:dependency.trim(),createdAt:now,updatedAt:now};try{await saveFlowMilestone(record,identityEmail,'Phase milestone created');setPhase('');setTitle('');setDueDate('');setDependency('');onNotice('Phase milestone added to the project.')}catch{onNotice('Milestone could not be saved. Please try again.')}}
 const advance=async(item:FlowMilestoneRecord)=>{const status=item.status==='Not started'?'In progress':item.status==='In progress'?'Complete':item.status==='Blocked'?'In progress':'Complete';try{await saveFlowMilestone({...item,status,updatedAt:new Date().toISOString()},identityEmail,`Milestone updated to ${status}`);onNotice(`Milestone marked ${status}.`)}catch{onNotice('Milestone update could not be saved.')}}
 return <div className="teams-projects"><section className="teams-project-head"><small>PROJECT DELIVERY</small><h1>Projects and milestones</h1><p>Keep strategic delivery visible with simple owner, date and dependency control.</p></section><div className="teams-project-layout"><section className="teams-project-list"><header><div><small>PROJECT PORTFOLIO</small><h2>Active projects</h2></div><span>{ordered.length} total</span></header>{ordered.map(row=><button key={row.id} className={row.id===selectedId?'selected':''} onClick={()=>setSelectedId(row.id)}><div><b>{row.title}</b><small>Due {row.targetDate} · {row.departmentId}</small></div><em className={statusClass(row.status)}>{row.status}</em><span className="project-progress"><i style={{width:`${row.progress}%`}}/><small>{row.progress}%</small></span></button>)}{!ordered.length&&<div className="teams-project-empty"><Icon name="package" size={27}/><b>No projects have been published yet.</b><span>Leadership projects will appear here once created.</span></div>}</section>{project&&<section className="teams-milestones"><header><div><small>SELECTED PROJECT</small><h2>{project.title}</h2><p>Owner: {project.ownerEmail} · Target: {project.targetDate}</p></div><em className={statusClass(project.status)}>{project.status}</em></header><div className="teams-milestone-add"><div><label>Milestone</label><input value={title} onChange={event=>setTitle(event.target.value)} placeholder="e.g. Complete vendor evaluation"/></div><div><label>Target date</label><input type="date" min={today()} value={dueDate} onChange={event=>setDueDate(event.target.value)}/></div><div><label>Depends on <small>optional</small></label><input value={dependency} onChange={event=>setDependency(event.target.value)} placeholder="Previous milestone or decision"/></div><button className="teams-primary" onClick={()=>void addMilestone()}><Icon name="plus" size={16}/>Add milestone</button></div><div className="teams-milestone-list"><div className="teams-milestone-labels"><span>Milestone</span><span>Owner / target</span><span>Status</span><span/></div>{projectMilestones.map((item,index)=><article key={item.id}><span className="milestone-number">{index+1}</span><div><b>{item.title}</b>{item.dependency&&<small>Depends on: {item.dependency}</small>}</div><div><small>{item.ownerEmail}</small><time>{item.dueDate}</time></div><em className={statusClass(item.status)}>{item.status}</em><button disabled={item.status==='Complete'} onClick={()=>void advance(item)}>{item.status==='Complete'?'Complete':'Update'} <Icon name="arrow" size={13}/></button></article>)}{!projectMilestones.length&&<div className="teams-milestone-empty"><Icon name="empty" size={24}/><b>No milestones yet</b><span>Break this project into its next accountable delivery points.</span></div>}</div></section>}</div></div>
}
