import { useMemo, useState } from "react";
import "./NcrAdmin.css";
import "./NcrAdminOverrides.css";
import NcrGovernance from "./NcrGovernance";

export type NcrUser={id:string;employeeCode?:string;name:string;email:string;status?:string};
export type NcrProcessGroup={id:string;code:string;name:string;memberUserIds:string[];status:"Active"|"Inactive"};
export type NcrCategory={id:string;code:string;name:string;status:"Active"|"Inactive"};
export type NcrCapability={userId:string;canRaise:boolean;canApprove:boolean;canPurchase:boolean;status:"Active"|"Inactive"};
export type NcrVendor={id:string;code:string;name:string;email:string;phone:string;gstin:string;paymentTerms:string;status:"Active"|"Inactive"};
export type NcrMasterData={groups:NcrProcessGroup[];categories:NcrCategory[];capabilities:NcrCapability[];vendors?:NcrVendor[];delegations?:{id:string;primaryUserId:string;backupUserId:string;from:string;to:string;reason:string;status:"Active"|"Inactive"}[];budgets?:{id:string;costCentre:string;financialYear:string;amount:number;status:"Active"|"Inactive"}[];reportOwners?:{id:string;reportType:string;ownerUserId:string;dayOfMonth:number;status:"Active"|"Inactive"}[]};
export const defaultNcrMasterData:NcrMasterData={groups:[],categories:["Laboratory consumables","Office supplies","Maintenance consumables","IT consumables","Housekeeping & hygiene","Safety & PPE","Packaging materials","Other"].map((name,index)=>({id:`ncr-category-${index+1}`,code:`CAT-${String(index+1).padStart(2,"0")}`,name,status:"Active"})),capabilities:[],vendors:[]};

export default function NcrAdmin({users,value,onChange}:{users:NcrUser[];value:NcrMasterData;onChange:(next:NcrMasterData)=>void}){
 const [tab,setTab]=useState<"groups"|"roles"|"categories"|"vendors"|"controls">("groups");const [search,setSearch]=useState("");const [group,setGroup]=useState<NcrProcessGroup|null>(null);const [category,setCategory]=useState<NcrCategory|null>(null);const[vendor,setVendor]=useState<NcrVendor|null>(null);const term=search.trim().toLowerCase();
 const filteredUsers=useMemo(()=>users.filter(user=>user.status==="Active"&&(!term||`${user.employeeCode} ${user.name} ${user.email}`.toLowerCase().includes(term))).sort((a,b)=>a.name.localeCompare(b.name)),[term,users]);
 const saveGroup=()=>{if(!group?.code.trim()||!group.name.trim())return;const row={...group,id:group.id||crypto.randomUUID(),code:group.code.trim().toUpperCase(),name:group.name.trim()};onChange({...value,groups:value.groups.some(item=>item.id===row.id)?value.groups.map(item=>item.id===row.id?row:item):[...value.groups,row]});setGroup(null)};
 const saveCategory=()=>{if(!category?.code.trim()||!category.name.trim())return;const row={...category,id:category.id||crypto.randomUUID(),code:category.code.trim().toUpperCase(),name:category.name.trim()};onChange({...value,categories:value.categories.some(item=>item.id===row.id)?value.categories.map(item=>item.id===row.id?row:item):[...value.categories,row]});setCategory(null)};
 const saveVendor=()=>{if(!vendor?.code.trim()||!vendor.name.trim())return;const vendors=value.vendors||[];const row={...vendor,id:vendor.id||crypto.randomUUID(),code:vendor.code.trim().toUpperCase(),name:vendor.name.trim()};onChange({...value,vendors:vendors.some(item=>item.id===row.id)?vendors.map(item=>item.id===row.id?row:item):[...vendors,row]});setVendor(null)};
 const capability=(id:string)=>value.capabilities.find(row=>row.userId===id)||{userId:id,canRaise:false,canApprove:false,canPurchase:false,status:"Active" as const};
 const updateCapability=(row:NcrCapability)=>onChange({...value,capabilities:value.capabilities.some(item=>item.userId===row.userId)?value.capabilities.map(item=>item.userId===row.userId?row:item):[...value.capabilities,row]});
 return <section className="ncr-admin"><header><div><strong>NCR administration & masters</strong><small>Controlled configuration for groups, capabilities, categories, vendors and governance</small></div></header><nav><button className={tab==="groups"?"active":""} onClick={()=>setTab("groups")}>Process groups</button><button className={tab==="roles"?"active":""} onClick={()=>setTab("roles")}>Raiser & approver roles</button><button className={tab==="categories"?"active":""} onClick={()=>setTab("categories")}>Item categories</button><button className={tab==="vendors"?"active":""} onClick={()=>setTab("vendors")}>Vendors</button><button className={tab==="controls"?"active":""} onClick={()=>setTab("controls")}>Operational controls</button></nav>
 {tab==="groups"&&<><div className="ncr-admin-tools"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search group or member"/><button className="ncr-primary" onClick={()=>setGroup({id:"",code:"",name:"",memberUserIds:[],status:"Active"})}>＋ Add group</button></div>{group&&<div className="ncr-admin-form"><label>Group code<input value={group.code} onChange={e=>setGroup({...group,code:e.target.value})}/></label><label>Group name<input value={group.name} onChange={e=>setGroup({...group,name:e.target.value})}/></label><label>Status<select value={group.status} onChange={e=>setGroup({...group,status:e.target.value as "Active"|"Inactive"})}><option>Active</option><option>Inactive</option></select></label><fieldset><legend>Members — search by typing above</legend>{filteredUsers.map(user=><label key={user.id}><input type="checkbox" checked={group.memberUserIds.includes(user.id)} onChange={e=>setGroup({...group,memberUserIds:e.target.checked?[...group.memberUserIds,user.id]:group.memberUserIds.filter(id=>id!==user.id)})}/><strong>{user.employeeCode} · {user.name}</strong><small>{user.email}</small></label>)}</fieldset><footer><button onClick={()=>setGroup(null)}>Cancel</button><button className="ncr-primary" onClick={saveGroup}>Save group</button></footer></div>}<div className="ncr-admin-list">{value.groups.filter(row=>!term||`${row.code} ${row.name} ${row.memberUserIds.map(id=>users.find(u=>u.id===id)?.name).join(" ")}`.toLowerCase().includes(term)).map(row=><article key={row.id}><span><strong>{row.code} · {row.name}</strong><small>{row.memberUserIds.length} members</small></span><b>{row.status}</b><span><button onClick={()=>setGroup(row)}>Edit</button><button onClick={()=>onChange({...value,groups:value.groups.map(item=>item.id===row.id?{...item,status:item.status==="Active"?"Inactive":"Active"}:item)})}>{row.status==="Active"?"Disable":"Enable"}</button><button className="danger" onClick={()=>onChange({...value,groups:value.groups.filter(item=>item.id!==row.id)})}>Remove</button></span></article>)}</div></>}
 {tab==="roles"&&<><div className="ncr-admin-tools"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Type employee name, ID or email"/></div><div className="ncr-role-table"><header><span>User</span><span>Can raise</span><span>Can approve</span><span>Purchase role</span><span>Status</span></header>{filteredUsers.map(user=>{const row=capability(user.id);return <article key={user.id}><span><strong>{user.employeeCode} · {user.name}</strong><small>{user.email}</small></span>{(["canRaise","canApprove","canPurchase"] as const).map(key=><label key={key}><input type="checkbox" checked={row[key]} onChange={e=>updateCapability({...row,[key]:e.target.checked})}/></label>)}<select value={row.status} onChange={e=>updateCapability({...row,status:e.target.value as "Active"|"Inactive"})}><option>Active</option><option>Inactive</option></select></article>})}</div></>}
 {tab==="categories"&&<><div className="ncr-admin-tools"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search category code or name"/><button className="ncr-primary" onClick={()=>setCategory({id:"",code:"",name:"",status:"Active"})}>＋ Add category</button></div>{category&&<div className="ncr-admin-form compact"><label>Category code<input value={category.code} onChange={e=>setCategory({...category,code:e.target.value})}/></label><label>Category name<input value={category.name} onChange={e=>setCategory({...category,name:e.target.value})}/></label><label>Status<select value={category.status} onChange={e=>setCategory({...category,status:e.target.value as "Active"|"Inactive"})}><option>Active</option><option>Inactive</option></select></label><footer><button onClick={()=>setCategory(null)}>Cancel</button><button className="ncr-primary" onClick={saveCategory}>Save category</button></footer></div>}<div className="ncr-admin-list">{value.categories.filter(row=>!term||`${row.code} ${row.name}`.toLowerCase().includes(term)).map(row=><article key={row.id}><span><strong>{row.code} · {row.name}</strong></span><b>{row.status}</b><span><button onClick={()=>setCategory(row)}>Edit</button><button onClick={()=>onChange({...value,categories:value.categories.map(item=>item.id===row.id?{...item,status:item.status==="Active"?"Inactive":"Active"}:item)})}>{row.status==="Active"?"Disable":"Enable"}</button><button className="danger" onClick={()=>onChange({...value,categories:value.categories.filter(item=>item.id!==row.id)})}>Remove</button></span></article>)}</div></>}
 {tab==="vendors"&&<><div className="ncr-admin-tools"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search vendor code, name, GSTIN, email or phone"/><button className="ncr-primary" onClick={()=>setVendor({id:"",code:"",name:"",email:"",phone:"",gstin:"",paymentTerms:"",status:"Active"})}>＋ Add vendor</button></div>{vendor&&<div className="ncr-admin-form ncr-vendor-form"><label>Vendor code<input value={vendor.code} onChange={e=>setVendor({...vendor,code:e.target.value})}/></label><label>Vendor name<input value={vendor.name} onChange={e=>setVendor({...vendor,name:e.target.value})}/></label><label>GSTIN<input value={vendor.gstin} onChange={e=>setVendor({...vendor,gstin:e.target.value.toUpperCase()})}/></label><label>Email<input type="email" value={vendor.email} onChange={e=>setVendor({...vendor,email:e.target.value})}/></label><label>Phone<input value={vendor.phone} onChange={e=>setVendor({...vendor,phone:e.target.value})}/></label><label>Payment terms<input value={vendor.paymentTerms} onChange={e=>setVendor({...vendor,paymentTerms:e.target.value})}/></label><label>Status<select value={vendor.status} onChange={e=>setVendor({...vendor,status:e.target.value as "Active"|"Inactive"})}><option>Active</option><option>Inactive</option></select></label><footer><button onClick={()=>setVendor(null)}>Cancel</button><button className="ncr-primary" onClick={saveVendor}>Save vendor</button></footer></div>}<div className="ncr-admin-list">{(value.vendors||[]).filter(row=>!term||`${row.code} ${row.name} ${row.gstin} ${row.email} ${row.phone}`.toLowerCase().includes(term)).map(row=><article key={row.id}><span><strong>{row.code} · {row.name}</strong><small>{row.gstin||"GSTIN not recorded"} · {row.email||row.phone||"No contact"}</small></span><b>{row.status}</b><span><button onClick={()=>setVendor(row)}>Edit</button><button onClick={()=>onChange({...value,vendors:(value.vendors||[]).map(item=>item.id===row.id?{...item,status:item.status==="Active"?"Inactive":"Active"}:item)})}>{row.status==="Active"?"Disable":"Enable"}</button><button className="danger" onClick={()=>onChange({...value,vendors:(value.vendors||[]).filter(item=>item.id!==row.id)})}>Remove</button></span></article>)}</div></>}
 {tab==="controls"&&<NcrGovernance users={users} value={value} onChange={onChange}/>} 
 </section>
}
