import { useMemo, useState } from "react";
import "./NcrApprovalMappings.css";
import "./NcrApprovalSearch.css";

export type MappingUser = { id: string; employeeCode?: string; name: string; email: string; groupId?: string; status?: string };
export type MappingGroup = { id: string; code?: string; name: string; status?: string; memberUserIds?: string[] };
export type NcrApprovalMapping = { id: string; name: string; raiserGroupIds: string[]; raiserGroupId?: string; raiserUserIds: string[]; category: string; approverUserId: string; priceLimit: number; status: "Active" | "Inactive"; updatedAt: string };

const empty = (): NcrApprovalMapping => ({ id: "", name: "", raiserGroupIds: [], raiserUserIds: [], category: "All categories", approverUserId: "", priceLimit: 0, status: "Active", updatedAt: "" });
const groupIds = (row: NcrApprovalMapping) => row.raiserGroupIds?.length ? row.raiserGroupIds : row.raiserGroupId ? [row.raiserGroupId] : [];
const matches = (user: MappingUser, term: string) => `${user.employeeCode || ""} ${user.name} ${user.email}`.toLowerCase().includes(term);

export default function NcrApprovalMappings({ users, groups, categories, mappings, approverUserIds, onChange, onRoleAssignment }: { users: MappingUser[]; groups: MappingGroup[]; categories: string[]; mappings: NcrApprovalMapping[]; approverUserIds?: string[]; onChange: (next: NcrApprovalMapping[]) => void; onRoleAssignment?: (raiserUserIds: string[], approverUserId: string) => void }) {
  const [form, setForm] = useState(empty()); const [open, setOpen] = useState(false); const [search, setSearch] = useState(""); const [raiserSearch, setRaiserSearch] = useState(""); const [approverSearch, setApproverSearch] = useState(""); const [error,setError]=useState("");
  const selectedGroups = groupIds(form);
  const eligible = useMemo(() => { const memberIds=new Set(groups.filter((group)=>selectedGroups.includes(group.id)).flatMap((group)=>group.memberUserIds||[])); return users.filter((user) => user.status === "Active" && (selectedGroups.includes(user.groupId || "") || memberIds.has(user.id)) && matches(user, raiserSearch.trim().toLowerCase())).sort((a, b) => a.name.localeCompare(b.name)); }, [groups, raiserSearch, selectedGroups.join("|"), users]);
  const approvers = useMemo(() => users.filter((user) => user.status === "Active" && (!approverUserIds?.length || approverUserIds.includes(user.id)) && matches(user, approverSearch.trim().toLowerCase())).sort((a, b) => a.name.localeCompare(b.name)).slice(0, 30), [approverSearch, approverUserIds, users]);
  const visible = useMemo(() => { const term = search.trim().toLowerCase(); return mappings.filter((row) => !term || `${row.name} ${groupIds(row).map((id) => groups.find((g) => g.id === id)?.name).join(" ")} ${row.category} ${users.find((u) => u.id === row.approverUserId)?.name}`.toLowerCase().includes(term)); }, [groups, mappings, search, users]);
  const selectedApprover = users.find((user) => user.id === form.approverUserId);
  function toggleGroup(id: string) { const next = selectedGroups.includes(id) ? selectedGroups.filter((item) => item !== id) : [...selectedGroups, id]; setForm({ ...form, raiserGroupIds: next, raiserGroupId: undefined, raiserUserIds: form.raiserUserIds.filter((userId) => users.some((user) => user.id === userId && next.includes(user.groupId || ""))) }); }
  function save() { if (!selectedGroups.length || !form.raiserUserIds.length || !form.approverUserId || !form.category || form.priceLimit <= 0) { setError("Select a department/process group, at least one named raiser, an approver, category and a positive INR limit."); return; } setError(""); const row = { ...form, raiserGroupIds: selectedGroups, raiserGroupId: undefined, id: form.id || crypto.randomUUID(), name: form.name.trim() || `${form.category} approval`, updatedAt: new Date().toISOString() }; onChange(form.id ? mappings.map((item) => item.id === form.id ? row : item) : [...mappings, row]); onRoleAssignment?.(form.raiserUserIds, form.approverUserId); setForm(empty()); setOpen(false); setRaiserSearch(""); setApproverSearch(""); }
  function edit(row: NcrApprovalMapping) { setForm({ ...row, raiserGroupIds: groupIds(row) }); setApproverSearch(users.find((user) => user.id === row.approverUserId)?.name || ""); setOpen(true); }
  return <section className="ncr-map"><header><div><strong>Approval mapping</strong><small>Department/process groups narrow the employee pool; only named raisers receive permission</small></div><button className="ncr-primary" onClick={() => { setForm(empty()); setApproverSearch(""); setRaiserSearch(""); setOpen(true); }}>＋ Add mapping</button></header>
    {open && <div className="ncr-map-form"><label>Mapping name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="e.g. IT and Maintenance consumables" /></label><label>Consumable category *<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}><option>All categories</option>{categories.map((category) => <option key={category}>{category}</option>)}</select></label><label>Price limit (INR) *<input type="number" min="1" value={form.priceLimit || ""} onChange={(e) => setForm({ ...form, priceLimit: Number(e.target.value) })} placeholder="Maximum approval value" /></label>
      <fieldset className="ncr-map-groups"><legend>Department / process groups *</legend><div>{groups.filter((g) => g.status === "Active").map((g) => <label key={g.id}><input type="checkbox" checked={selectedGroups.includes(g.id)} onChange={() => toggleGroup(g.id)} />{g.code} · {g.name}</label>)}</div></fieldset>
      <fieldset className="ncr-map-approver"><legend>Approver *</legend><input value={approverSearch} onChange={(e) => { setApproverSearch(e.target.value); setForm({ ...form, approverUserId: "" }); }} placeholder="Type name, employee ID or email" autoComplete="off" />{selectedApprover && <div className="ncr-selected-person"><strong>{selectedApprover.employeeCode} · {selectedApprover.name}</strong><small>{selectedApprover.email}</small><button onClick={() => { setForm({ ...form, approverUserId: "" }); setApproverSearch(""); }}>Change</button></div>}{!selectedApprover && approverSearch && <div className="ncr-typeahead">{approvers.map((user) => <button key={user.id} onClick={() => { setForm({ ...form, approverUserId: user.id }); setApproverSearch(user.name); }}><strong>{user.employeeCode} · {user.name}</strong><small>{user.email}</small></button>)}{!approvers.length && <span>No matching users</span>}</div>}</fieldset>
      <label>Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as "Active" | "Inactive" })}><option>Active</option><option>Inactive</option></select></label>
      <fieldset className="ncr-map-raisers"><legend>Authorised raisers from selected groups *</legend><input value={raiserSearch} onChange={(e) => setRaiserSearch(e.target.value)} placeholder="Type name, employee ID or email — results filter instantly" /><small>Select at least one named employee. Group membership alone never grants permission to raise requests.</small><div className="ncr-map-select">{eligible.map((user) => <label key={user.id}><input type="checkbox" checked={form.raiserUserIds.includes(user.id)} onChange={(e) => setForm({ ...form, raiserUserIds: e.target.checked ? [...form.raiserUserIds, user.id] : form.raiserUserIds.filter((id) => id !== user.id) })} /><strong>{user.employeeCode} · {user.name}</strong><small>{user.email}</small></label>)}</div></fieldset>
      {error&&<p className="ncr-map-error" role="alert">{error}</p>}<footer><button onClick={() => { setOpen(false); setForm(empty()); setError(""); }}>Cancel</button><button className="ncr-primary" onClick={save}>Save mapping</button></footer></div>}
    <div className="ncr-map-search"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search group, user, category or approver" /><span>{visible.length} mappings</span></div><div className="ncr-map-table"><header><span>Raiser groups / users</span><span>Category</span><span>Approver</span><span>Limit</span><span>Status</span><span>Actions</span></header>{visible.map((row) => { const names = groupIds(row).map((id) => groups.find((g) => g.id === id)?.name || "Unknown group"); const approver = users.find((u) => u.id === row.approverUserId); return <article key={row.id}><span><strong>{names.join(" · ")}</strong><small>{row.raiserUserIds.length ? `${row.raiserUserIds.length} authorised raiser${row.raiserUserIds.length === 1 ? "" : "s"}` : "No authorised raiser — mapping inactive in practice"}</small></span><span>{row.category}</span><span><strong>{approver?.name || "Missing user"}</strong><small>{approver?.email}</small></span><span>₹{row.priceLimit.toLocaleString("en-IN")}</span><b>{row.status}</b><span><button onClick={() => edit(row)}>Edit</button><button className="danger" onClick={() => onChange(mappings.filter((item) => item.id !== row.id))}>Remove</button></span></article>; })}{!visible.length && <p>No approval mappings found.</p>}</div>
  </section>;
}
