import { useState } from "react";
import type { NcrMasterData,NcrUser } from "./NcrAdmin";
import "./NcrGovernance.css";
export default function NcrGovernance({users,value,onChange}:{users:NcrUser[];value:NcrMasterData;onChange:(next:NcrMasterData)=>void}){
 const[section,setSection]=useState<"delegation"|"budget"|"reports">("delegation"),[form,setForm]=useState<Record<string,string>>({});const active=users.filter(user=>user.status==="Active");
 const saveDelegation=()=>{if(!form.primaryUserId||!form.backupUserId||!form.from||!form.to||!form.reason)return;onChange({...value,delegations:[...(value.delegations||[]),{id:crypto.randomUUID(),primaryUserId:form.primaryUserId,backupUserId:form.backupUserId,from:form.from,to:form.to,reason:form.reason,status:"Active"}]});setForm({})};
 const saveBudget=()=>{if(!form.costCentre||Number(form.amount)<=0||!form.financialYear)return;onChange({...value,budgets:[...(value.budgets||[]),{id:crypto.randomUUID(),costCentre:form.costCentre.trim(),financialYear:form.financialYear,amount:Number(form.amount),status:"Active"}]});setForm({})};
 const saveOwner=()=>{if(!form.reportType||!form.ownerUserId||!form.dayOfMonth)return;onChange({...value,reportOwners:[...(value.reportOwners||[]),{id:crypto.randomUUID(),reportType:form.reportType,ownerUserId:form.ownerUserId,dayOfMonth:Number(form.dayOfMonth),status:"Active"}]});setForm({})};
 const person=(id:string)=>users.find(user=>user.id===id);
 return <section className="ncr-governance"><nav>{(["delegation","budget","reports"] as const).map(tab=><button className={section===tab?"active":""} onClick={()=>{setSection(tab);setForm({})}} key={tab}>{tab==="delegation"?"Approval delegation":tab==="budget"?"Budget controls":"KPI ownership"}</button>)}</nav>
 {section==="delegation"&&<><div className="ncr-governance-form"><label>Primary approver<select value={form.primaryUserId||""} onChange={e=>setForm({...form,primaryUserId:e.target.value})}><option value="">Select</option>{active.map(user=><option value={user.id} key={user.id}>{user.name} · {user.email}</option>)}</select></label><label>Backup approver<select value={form.backupUserId||""} onChange={e=>setForm({...form,backupUserId:e.target.value})}><option value="">Select</option>{active.filter(user=>user.id!==form.primaryUserId).map(user=><option value={user.id} key={user.id}>{user.name} · {user.email}</option>)}</select></label><label>From<input type="date" value={form.from||""} onChange={e=>setForm({...form,from:e.target.value})}/></label><label>To<input type="date" min={form.from} value={form.to||""} onChange={e=>setForm({...form,to:e.target.value})}/></label><label className="wide">Reason<input value={form.reason||""} onChange={e=>setForm({...form,reason:e.target.value})}/></label><button onClick={saveDelegation}>Add delegation</button></div><div className="ncr-governance-list">{(value.delegations||[]).map(row=><article key={row.id}><span><strong>{person(row.primaryUserId)?.name} → {person(row.backupUserId)?.name}</strong><small>{row.from} to {row.to} · {row.reason}</small></span><b>{new Date(row.to)<new Date()?"Expired":row.status}</b><button onClick={()=>onChange({...value,delegations:(value.delegations||[]).filter(item=>item.id!==row.id)})}>Remove</button></article>)}</div></>}
 {section==="budget"&&<><div className="ncr-governance-form"><label>Cost centre<input value={form.costCentre||""} onChange={e=>setForm({...form,costCentre:e.target.value})}/></label><label>Financial year<input placeholder="2026-27" value={form.financialYear||""} onChange={e=>setForm({...form,financialYear:e.target.value})}/></label><label>Budget ceiling (INR)<input type="number" min="1" value={form.amount||""} onChange={e=>setForm({...form,amount:e.target.value})}/></label><button onClick={saveBudget}>Add budget</button></div><div className="ncr-governance-list">{(value.budgets||[]).map(row=><article key={row.id}><span><strong>{row.costCentre} · ₹{row.amount.toLocaleString("en-IN")}</strong><small>Financial year {row.financialYear}</small></span><b>{row.status}</b><button onClick={()=>onChange({...value,budgets:(value.budgets||[]).filter(item=>item.id!==row.id)})}>Remove</button></article>)}</div></>}
 {section==="reports"&&<><div className="ncr-governance-form"><label>Report<select value={form.reportType||""} onChange={e=>setForm({...form,reportType:e.target.value})}><option value="">Select</option><option>Requester KPI</option><option>Approver KPI</option><option>Purchase KPI</option><option>Department KPI</option><option>Administrator KPI</option></select></label><label>Owner<select value={form.ownerUserId||""} onChange={e=>setForm({...form,ownerUserId:e.target.value})}><option value="">Select</option>{active.map(user=><option value={user.id} key={user.id}>{user.name} · {user.email}</option>)}</select></label><label>Monthly day<input type="number" min="1" max="28" value={form.dayOfMonth||""} onChange={e=>setForm({...form,dayOfMonth:e.target.value})}/></label><button onClick={saveOwner}>Assign owner</button></div><div className="ncr-governance-list">{(value.reportOwners||[]).map(row=><article key={row.id}><span><strong>{row.reportType}</strong><small>{person(row.ownerUserId)?.name} · monthly on day {row.dayOfMonth}</small></span><b>{row.status}</b><button onClick={()=>onChange({...value,reportOwners:(value.reportOwners||[]).filter(item=>item.id!==row.id)})}>Remove</button></article>)}</div></>}
 </section>
}
