import { useMemo } from 'react'
import Icon, { type IconName } from '../../components/Icon'
import { deriveCustody, type CustodyMovement } from '../../lib/custodyLifecycle'
import { useLocalStore } from '../../lib/localStore'
import type { MaintenanceRecord } from '../maintenance/MaintenanceWorkspace'
import type { DisposalRecord, VerificationRecord } from '../assurance/AssuranceWorkspace'
import type { RetirementRecord } from '../retirement/RetirementWorkspace'
import './CommandDashboard.css'

type Asset={id:string;assetId:string;modelId:string;purchaseDate:string;stockStatus:string;cost:number}
type Model={id:string;brand:string;name:string;warrantyMonths:string}
type Allocation={id:string;code:string;userId:string;assetIds:string[];allocationDate:string;state:string;requestedAt:string}
type Incident={id:string;code:string;assetId:string;type:string;status:string;reportedAt:string}
type Lifecycle={id:string;code:string;kind:string;state:string;createdAt:string}
type Activity={id:string;at:string;title:string;detail:string;module:string}
const today=()=>new Date().toISOString().slice(0,10)
const addMonths=(date:string,months:number)=>{const value=new Date(`${date}T00:00:00`);value.setMonth(value.getMonth()+months);return value.toISOString().slice(0,10)}
const addDays=(date:string,days:number)=>{const value=new Date(`${date}T00:00:00`);value.setDate(value.getDate()+days);return value.toISOString().slice(0,10)}
const CURRENT_DATE=today()

export default function CommandDashboard({onNavigate}:{onNavigate:(section:string)=>void}){
  const [assets]=useLocalStore<Asset[]>('itms.assets.v1',[]);const [models]=useLocalStore<Model[]>('itms.asset-models.v1',[]);const [allocations]=useLocalStore<Allocation[]>('itms.allocations.v1',[]);const [movements]=useLocalStore<CustodyMovement[]>('itms.custody-movements.v1',[]);const [maintenance]=useLocalStore<MaintenanceRecord[]>('itms.asset-maintenance.v1',[]);const [incidents]=useLocalStore<Incident[]>('itms.asset-incidents.v1',[]);const [verifications]=useLocalStore<VerificationRecord[]>('itms.asset-verifications.v1',[]);const [disposals]=useLocalStore<DisposalRecord[]>('itms.asset-disposals.v1',[]);const [retirements]=useLocalStore<RetirementRecord[]>('itms.asset-retirements.v1',[]);const [lifecycle]=useLocalStore<Lifecycle[]>('itms.employee-lifecycle.v1',[])
  const custody=useMemo(()=>deriveCustody(allocations,movements,assets),[allocations,assets,movements]);const pendingAllocations=allocations.filter((item)=>item.state.startsWith('Pending')).length;const overdue=maintenance.filter((item)=>item.state==='Scheduled'&&item.dueDate<CURRENT_DATE).length;const dueSoon=maintenance.filter((item)=>item.state==='Scheduled'&&item.dueDate>=CURRENT_DATE&&item.dueDate<=addDays(CURRENT_DATE,30)).length;const openIncidents=incidents.filter((item)=>item.status==='Open').length;const exceptions=verifications.filter((item)=>item.result!=='Verified').length;const pendingDisposals=disposals.filter((item)=>item.state.startsWith('Pending')).length;const pendingRetirements=retirements.filter((item)=>!['Completed','Cancelled'].includes(item.state)).length;const awaitingSignatures=lifecycle.filter((item)=>item.state!=='Completed').length;const warrantySoon=assets.filter((asset)=>{const months=Number(models.find((item)=>item.id===asset.modelId)?.warrantyMonths||0);if(!months)return false;const expiry=addMonths(asset.purchaseDate,months);return expiry>=CURRENT_DATE&&expiry<=addDays(CURRENT_DATE,90)}).length
  const activity:Activity[]=[...allocations.map((item)=>({id:`a-${item.id}`,at:item.requestedAt,title:item.code,detail:`Allocation · ${item.state}`,module:'Allocation & Custody'})),...maintenance.map((item)=>({id:`m-${item.id}`,at:item.completedAt||item.createdAt,title:item.code,detail:`${item.activity} · ${item.state}`,module:'Maintenance & Inspection'})),...verifications.map((item)=>({id:`v-${item.id}`,at:item.createdAt,title:item.code,detail:`Physical verification · ${item.result}`,module:'Assurance & Controls'})),...disposals.map((item)=>({id:`d-${item.id}`,at:item.headAt||item.managerAt||item.requestedAt,title:item.code,detail:`Disposal · ${item.state}`,module:'Assurance & Controls'})),...retirements.map((item)=>({id:`r-${item.id}`,at:item.completedAt||item.headAt||item.managerAt||item.requestedAt,title:item.code,detail:`${item.route} · ${item.assetIds?.length||Number(Boolean(item.assetId))} assets · ${item.state}`,module:'Asset Retirement & Circularity'})),...lifecycle.map((item)=>({id:`l-${item.id}`,at:item.createdAt,title:item.code,detail:`${item.kind} · ${item.state}`,module:'Allocation & Custody'}))].sort((a,b)=>b.at.localeCompare(a.at)).slice(0,8)
  const cards:{title:string;value:number;detail:string;module:string;icon:IconName;tone:string}[]=[{title:'Assets in custody',value:custody.size,detail:`${assets.filter((item)=>item.stockStatus==='In stock').length} available in stock`,module:'Asset Inventory',icon:'allocation',tone:'blue'},{title:'Pending allocations',value:pendingAllocations,detail:'Manager or IT Head action',module:'Allocation & Custody',icon:'allocation',tone:pendingAllocations?'amber':'green'},{title:'Maintenance overdue',value:overdue,detail:`${dueSoon} due within 30 days`,module:'Maintenance & Inspection',icon:'maintenance',tone:overdue?'red':'green'},{title:'Open asset incidents',value:openIncidents,detail:'Repair, loss or damage cases',module:'Shared Masters',icon:'support',tone:openIncidents?'red':'green'},{title:'Verification exceptions',value:exceptions,detail:'Missing, damaged or mismatch',module:'Assurance & Controls',icon:'assurance',tone:exceptions?'red':'green'},{title:'Retirement actions',value:pendingRetirements+pendingDisposals,detail:`${pendingDisposals} legacy disposal approvals · batches awaiting action`,module:'Asset Retirement & Circularity',icon:'assurance',tone:pendingRetirements||pendingDisposals?'amber':'green'},{title:'Awaiting signatures',value:awaitingSignatures,detail:'Onboarding/offboarding forms',module:'Allocation & Custody',icon:'masters',tone:awaitingSignatures?'amber':'green'},{title:'Warranty expiring',value:warrantySoon,detail:'Within the next 90 days',module:'Asset Inventory',icon:'inventory',tone:warrantySoon?'amber':'green'}]
  return <><section className="page-heading"><div><span className="eyebrow">GCCP-ITMS-BUILD-15</span><h1>ITMS Command Dashboard</h1><p>Priorities, lifecycle health and direct action from one operational view.</p></div><span className="phase">LIVE CONTROL CENTRE</span></section><section className="command-cards">{cards.map((card)=><button type="button" className={`command-card ${card.tone}`} onClick={()=>onNavigate(card.module)} key={card.title}><span><Icon name={card.icon} size={22}/></span><div><small>{card.title}</small><strong>{card.value}</strong><p>{card.detail}</p></div><Icon name="arrow" size={18}/></button>)}</section><section className="dashboard-columns"><section className="master-panel priority-panel"><div className="operation-heading"><div><span className="eyebrow">ACTION QUEUE</span><h2>What needs attention</h2></div></div>{cards.filter((item)=>item.value>0&&item.title!=='Assets in custody').map((item)=><button type="button" onClick={()=>onNavigate(item.module)} key={item.title}><i className={item.tone}></i><span><strong>{item.title}</strong><small>{item.detail}</small></span><b>{item.value}</b><Icon name="chevron" size={16}/></button>)}{!cards.some((item)=>item.value>0&&item.title!=='Assets in custody')&&<div className="dashboard-clear"><Icon name="check" size={18}/> No current exceptions or overdue actions.</div>}</section><section className="master-panel activity-panel"><div className="operation-heading"><div><span className="eyebrow">RECENT CONTROLLED ACTIVITY</span><h2>Latest lifecycle events</h2></div></div>{activity.map((item)=><button type="button" onClick={()=>onNavigate(item.module)} key={item.id}><i></i><span><strong>{item.title}</strong><small>{item.detail}</small></span><time>{new Date(item.at).toLocaleDateString('en-IN')}</time></button>)}{!activity.length&&<div className="dashboard-clear">No lifecycle activity recorded yet.</div>}</section></section><section className="dashboard-footer"><span>Portfolio acquisition value</span><strong>₹{assets.reduce((sum,item)=>sum+item.cost,0).toLocaleString('en-IN')}</strong><button type="button" onClick={()=>onNavigate('Reports & Analytics')}>Open Reports &amp; Analytics <Icon name="arrow" size={16}/></button></section></>
}
