import { useEffect, useMemo, useState, type ChangeEvent } from 'react'
import { sendPasswordResetEmail } from 'firebase/auth'
import Icon, { type IconName } from '../../components/Icon'
import { firebaseAuth } from '../../lib/firebase'
import { applicationIsAvailable, type ApplicationAvailability, type GlasscoApplicationId } from '../../lib/applicationAccess'
import { useLocalStore } from '../../lib/localStore'
import { useSupportStore } from '../../lib/supportStore'
import { subscribeUserNotifications, type UserNotification } from '../../lib/userNotifications'
import { saveUserSelfCare, subscribeUserSelfCare, type UserSelfCareProfile } from '../../lib/userSelfCare'

type PlatformApp={id:string;name:string;description:string;shortName:string;icon:IconName;state:'authorized'|'no-access'|'planned'}
type Ticket={id:string;requesterEmail:string;status:string}
type User={id:string;email:string}
type Allocation={id:string;userId:string;assetIds:string[];state:string}
const applications:PlatformApp[]=[
  {id:'itms',name:'IT Asset Management',description:'Inventory, custody, maintenance and lifecycle control.',shortName:'ITMS',icon:'inventory',state:'authorized'},
  {id:'support',name:'IT Support Desk',description:'Employee tickets, support coordination and service communication.',shortName:'ITSD',icon:'support',state:'authorized'},
  {id:'requests',name:'Consumable Purchase Requests',description:'Raise, approve, purchase and receive consumable requirements.',shortName:'NCR',icon:'requests',state:'authorized'},
  {id:'sales-service',name:'Sales & Service Tickets',description:'Sales and customer-service coordination.',shortName:'SST',icon:'service',state:'planned'},
  {id:'visitors',name:'Visitor Management',description:'Visitor approvals and controlled entry.',shortName:'VMS',icon:'visitor',state:'planned'},
]
const blankProfile=(email:string):UserSelfCareProfile=>({email:email.toLowerCase(),photoDataUrl:'',notificationEmail:true,notificationInApp:true,density:'Compact',updatedAt:''})

export default function SmartAppLauncher({onOpen,identityEmail,identityName,authorizedAppIds,applicationAvailability,accessSummary}:{onOpen:(appId:string,target?:string)=>void;identityEmail:string;identityName:string;authorizedAppIds:GlasscoApplicationId[];applicationAvailability:ApplicationAvailability;accessSummary:string}){
  const [accountOpen,setAccountOpen]=useState(false);const [accountMessage,setAccountMessage]=useState('');const [profile,setProfile]=useState<UserSelfCareProfile>(blankProfile(identityEmail));const [personalNotices,setPersonalNotices]=useState<UserNotification[]>([])
  const [tickets]=useSupportStore<Ticket>('supportTickets',identityEmail,false);const [users]=useLocalStore<User[]>('itms.users.v1',[]);const [allocations]=useLocalStore<Allocation[]>('itms.allocations.v1',[])
  useEffect(()=>subscribeUserSelfCare(identityEmail,value=>{if(value)setProfile(value)}),[identityEmail]);useEffect(()=>subscribeUserNotifications(identityEmail,setPersonalNotices),[identityEmail])
  const liveApplications=applications.filter(app=>app.state==='planned'||applicationIsAvailable(app.id as GlasscoApplicationId,identityEmail,applicationAvailability)).map(app=>app.state==='planned'?app:{...app,state:authorizedAppIds.includes(app.id as GlasscoApplicationId)?'authorized' as const:'no-access' as const})
  const authorized=liveApplications.filter(app=>app.state==='authorized'),planned=liveApplications.filter(app=>app.state==='planned')
  const openTickets=tickets.filter(item=>item.requesterEmail?.toLowerCase()===identityEmail.toLowerCase()&&!['Resolved','Closed'].includes(item.status)).length
  const user=users.find(item=>item.email?.toLowerCase()===identityEmail.toLowerCase());const assetCount=user?allocations.filter(item=>item.userId===user.id&&item.state==='Active custody').reduce((total,item)=>total+(item.assetIds?.length||0),0):0
  const unread=personalNotices.filter(item=>!item.readAt).length;const recent=useMemo(()=>personalNotices.slice(0,5),[personalNotices]);const hour=new Date().getHours();const greeting=hour<12?'Good morning':hour<17?'Good afternoon':'Good evening';const initials=identityName.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase()
  async function storeProfile(next:UserSelfCareProfile){setProfile(next);try{await saveUserSelfCare({...next,updatedAt:new Date().toISOString()});setAccountMessage('Account preferences saved.')}catch{setAccountMessage('Preferences could not be saved. Please retry.')}}
  function choosePhoto(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/')||file.size>650000){setAccountMessage('Choose a JPG, PNG or WebP image smaller than 650 KB.');return}const reader=new FileReader();reader.onload=()=>void storeProfile({...profile,photoDataUrl:String(reader.result||'')});reader.readAsDataURL(file)}
  async function resetPassword(){if(!firebaseAuth){setAccountMessage('Password management is available on the live secure sign-in service.');return}try{await sendPasswordResetEmail(firebaseAuth,identityEmail);setAccountMessage('Password-reset link sent to your business email.')}catch{setAccountMessage('Google Workspace SSO users change their password through Google Account security.')}}
  return <main className={`launcher-main smart-launcher density-${profile.density.toLowerCase()}`}>
    <section className="launcher-hero smart-hero"><div className="launcher-hero-copy"><span className="launcher-kicker">GLASSCO CONNECT · TODAY</span><h1>{greeting}, {identityName}.</h1><p>Your secure workspace for people, assets and service operations.</p><div className="launcher-trust-row"><span><Icon name="assurance" size={16}/>Controlled workspace</span><span>{new Date().toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long'})}</span></div></div><button type="button" className="identity-card" onClick={()=>setAccountOpen(true)}><span className="identity-avatar">{profile.photoDataUrl?<img src={profile.photoDataUrl} alt="Profile"/>:initials}</span><div><small>Signed in as</small><strong>{identityName}</strong><span>{identityEmail}</span></div><span className="identity-status">MY ACCOUNT</span></button></section>
    <section className="today-strip"><button onClick={()=>authorizedAppIds.includes('support')&&onOpen('support')}><Icon name="support" size={19}/><span>Open tickets<strong>{openTickets}</strong></span></button><button onClick={()=>authorizedAppIds.includes('support')&&onOpen('support')}><Icon name="bell" size={19}/><span>Unread updates<strong>{unread}</strong></span></button><button onClick={()=>authorizedAppIds.includes('support')&&onOpen('support')}><Icon name="laptop" size={19}/><span>My IT assets<strong>{assetCount}</strong></span></button><button onClick={()=>setAccountOpen(true)}><Icon name="assurance" size={19}/><span>My access<strong>{authorized.length} apps</strong></span></button></section>
    <div className="launcher-content-grid"><section className="authorized-section"><div className="section-title"><div><span className="section-kicker">YOUR WORKSPACE</span><h2>Applications</h2></div><span>{authorized.length} available</span></div><div className="authorized-grid">{authorized.map(app=><button className="authorized-app" type="button" key={app.id} onClick={()=>onOpen(app.id)}><span className="app-monogram"><Icon name={app.icon} size={25}/></span><span className="app-copy"><small className="app-code">{app.shortName}</small><strong>{app.name}</strong><small>{app.description}</small></span><span className="open-app-label">Open <Icon name="arrow" size={18}/></span></button>)}</div></section>
      <section className="launcher-side"><article className="quick-actions"><div className="section-title"><div><span className="section-kicker">QUICK ACTIONS</span><h2>Start here</h2></div></div>{authorizedAppIds.includes('support')&&<button onClick={()=>onOpen('support')}><Icon name="plus" size={17}/>Raise or track a ticket</button>}{authorizedAppIds.includes('requests')&&<button onClick={()=>onOpen('requests')}><Icon name="requests" size={17}/>Raise a purchase request</button>}{authorizedAppIds.includes('itms')&&<button onClick={()=>onOpen('itms','Operations Centre')}><Icon name="reports" size={17}/>Search ITMS records</button>}<button onClick={()=>setAccountOpen(true)}><Icon name="assurance" size={17}/>Manage my account</button></article><article className="recent-activity"><div className="section-title"><div><span className="section-kicker">RECENT ACTIVITY</span><h2>Your updates</h2></div></div>{recent.map(item=><div key={item.id}><i/><span><strong>{item.title}</strong><small>{item.message}</small></span></div>)}{!recent.length&&<p>No recent personal updates.</p>}</article></section></div>
    <details className="roadmap-compact"><summary><span><span className="section-kicker">PLATFORM ROADMAP</span><strong>More from Glassco Connect</strong></span><small>{planned.length} planned applications</small></summary><div>{planned.map(app=><span key={app.id}><Icon name={app.icon} size={18}/><b>{app.shortName}</b>{app.name}<small>Planned</small></span>)}</div></details>
    <footer className="launcher-footer"><span><Icon name="assurance" size={16}/>Controlled company platform</span><span>Application access is centrally governed.</span></footer>
    {accountOpen&&<div className="account-overlay" onMouseDown={event=>{if(event.target===event.currentTarget)setAccountOpen(false)}}><section className="account-panel" role="dialog" aria-modal="true" aria-label="My account"><header><div><span className="section-kicker">SELF SERVICE</span><h2>My account</h2></div><button onClick={()=>setAccountOpen(false)} aria-label="Close"><Icon name="close" size={19}/></button></header><div className="account-profile"><span className="account-photo">{profile.photoDataUrl?<img src={profile.photoDataUrl} alt="Profile"/>:initials}</span><div><strong>{identityName}</strong><span>{identityEmail}</span><label>Change photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={choosePhoto}/></label>{profile.photoDataUrl&&<button onClick={()=>void storeProfile({...profile,photoDataUrl:''})}>Remove photo</button>}</div></div><div className="account-section"><h3>Identity &amp; access</h3><label>Name<input readOnly value={identityName}/></label><label>Business email<input readOnly value={identityEmail}/></label><p>{accessSummary}</p><small>Identity, role and application access are controlled by User Master and your administrator.</small></div><div className="account-section"><h3>Security</h3><button className="account-primary" onClick={()=>void resetPassword()}>Send password-reset link</button><small>Google Workspace SSO users manage their password through Google Account security.</small></div><div className="account-section account-preferences"><h3>Preferences</h3><label><input type="checkbox" checked={profile.notificationInApp} onChange={event=>void storeProfile({...profile,notificationInApp:event.target.checked})}/>In-app notifications</label><label><input type="checkbox" checked={profile.notificationEmail} onChange={event=>void storeProfile({...profile,notificationEmail:event.target.checked})}/>Email notifications</label><label>Display density<select value={profile.density} onChange={event=>void storeProfile({...profile,density:event.target.value as UserSelfCareProfile['density']})}><option>Compact</option><option>Comfortable</option></select></label></div>{accountMessage&&<div className="account-message">{accountMessage}</div>}<footer><button onClick={()=>setAccountOpen(false)}>Done</button></footer></section></div>}
  </main>
}
