import {useEffect,useMemo,useState} from 'react'
import Icon from '../../components/Icon'
import {saveFlowGoal,saveFlowProject,subscribeFlowGoals,subscribeFlowProjects,subscribeFlowTasks,subscribeFlowTeams,type FlowGoalRecord,type FlowProjectRecord,type FlowTaskRecord,type FlowTeamRecord} from './flowStore'
import './FlowDepartmentWorkspace.css'

const departmentId='information-technology'
const newId=(prefix:string)=>`${prefix}-${Date.now().toString(36).toUpperCase()}`
const stamp=()=>new Date().toISOString()

export default function FlowDepartmentWorkspace({identityEmail,isLeader,onNotice,onOpen}:{identityEmail:string;isLeader:boolean;onNotice:(text:string)=>void;onOpen:(section:string)=>void}){
 const [goals,setGoals]=useState<FlowGoalRecord[]>([]); const [projects,setProjects]=useState<FlowProjectRecord[]>([])
 const [tasks,setTasks]=useState<FlowTaskRecord[]>([]); const [teams,setTeams]=useState<FlowTeamRecord[]>([])
 const [showGoal,setShowGoal]=useState(false); const [showProject,setShowProject]=useState(false)
 const [goalTitle,setGoalTitle]=useState(''); const [goalOutcome,setGoalOutcome]=useState(''); const [projectTitle,setProjectTitle]=useState('')
 useEffect(()=>{const a=subscribeFlowGoals(setGoals),b=subscribeFlowProjects(setProjects),c=subscribeFlowTasks(setTasks),d=subscribeFlowTeams(setTeams);return()=>{a();b();c();d()}},[])
 const ownedTasks=useMemo(()=>tasks.filter(x=>x.departmentId===departmentId),[tasks])
 const openActions=ownedTasks.filter(x=>x.status!=='Closed').length
 const atRisk=projects.filter(x=>x.status==='At risk'||x.status==='On hold').length+ownedTasks.filter(x=>x.status==='Blocked').length
 const addGoal=async()=>{if(!goalTitle.trim()||!goalOutcome.trim()){onNotice('Add a goal name and measurable outcome before saving.');return};const now=stamp();await saveFlowGoal({id:newId('GOAL'),title:goalTitle.trim(),outcome:goalOutcome.trim(),departmentId,ownerEmail:identityEmail,participantEmails:[identityEmail],status:'On track',progress:0,targetDate:'2026-12-31',createdBy:identityEmail,createdAt:now,updatedAt:now},identityEmail,'Department goal created');setGoalTitle('');setGoalOutcome('');setShowGoal(false);onNotice('Department goal saved. It is now ready for projects and team actions.')}
 const addProject=async()=>{if(!projectTitle.trim()){onNotice('Add a project or workstream name before saving.');return};const now=stamp();await saveFlowProject({id:newId('PROJ'),title:projectTitle.trim(),departmentId,ownerEmail:identityEmail,participantEmails:[identityEmail],status:'On track',progress:0,targetDate:'2026-12-31',dependency:'',createdBy:identityEmail,createdAt:now,updatedAt:now},identityEmail,'Department project created');setProjectTitle('');setShowProject(false);onNotice('Project saved. Assign team actions from the Action register.')}
 const progress=(n:number)=><div className="dept-progress"><span style={{width:`${n}%`}}/><small>{n}%</small></div>
 return <section className="department-workspace">
   <header className="dept-hero"><div><small>DEPARTMENT OPERATING WORKSPACE</small><h2>Information Technology</h2><p>Goals, delivery, coordination and leadership exceptions in one controlled view.</p></div><div className="dept-actions">{isLeader&&<><button onClick={()=>setShowGoal(v=>!v)}><Icon name="plus" size={16}/>Add goal</button><button className="primary" onClick={()=>setShowProject(v=>!v)}><Icon name="plus" size={16}/>Add project</button></>}<button onClick={()=>onOpen('Leadership review')}>Leadership review <Icon name="arrow" size={15}/></button></div></header>
   {(showGoal||showProject)&&<section className="dept-composer">{showGoal&&<div><b>New annual goal</b><input autoFocus value={goalTitle} onChange={e=>setGoalTitle(e.target.value)} placeholder="Goal name"/><input value={goalOutcome} onChange={e=>setGoalOutcome(e.target.value)} placeholder="Measurable outcome"/><button className="primary" onClick={addGoal}>Save goal</button></div>}{showProject&&<div><b>New project / workstream</b><input autoFocus value={projectTitle} onChange={e=>setProjectTitle(e.target.value)} placeholder="Project or workstream name"/><button className="primary" onClick={addProject}>Save project</button></div>}</section>}
   <section className="dept-metrics"><article><span>Annual goals</span><b>{goals.length}</b><small>owned by the department</small></article><article><span>Active projects</span><b>{projects.filter(x=>x.status!=='Complete').length}</b><small>projects and workstreams</small></article><article><span>Open actions</span><b>{openActions}</b><small>team delivery commitments</small></article><article className={atRisk?'attention':''}><span>Needs attention</span><b>{atRisk}</b><small>risks, blockers or holds</small></article></section>
   <div className="dept-grid">
    <section className="dept-card portfolio"><header><div><small>ANNUAL GOALS & PROJECT PORTFOLIO</small><h3>What the department committed to deliver</h3></div><button onClick={()=>onOpen('Actions')}>Open actions</button></header>{goals.length===0&&projects.length===0?<div className="dept-empty"><b>Start with the department’s annual goals</b><span>Goals create the outcome line; projects and team actions sit beneath them.</span>{isLeader&&<button className="primary" onClick={()=>setShowGoal(true)}>Add first goal</button>}</div>:<div className="dept-table"><div className="dept-head"><span>Goal / project</span><span>Owner</span><span>Health</span><span>Progress</span></div>{goals.map(x=><div className="dept-row" key={x.id}><div><b>{x.title}</b><small>{x.outcome}</small></div><span>Department lead</span><i className={x.status.toLowerCase().replaceAll(' ','-')}>{x.status}</i>{progress(x.progress)}</div>)}{projects.map(x=><div className="dept-row project" key={x.id}><div><b>{x.title}</b><small>{x.dependency||'No recorded dependency'}</small></div><span>Department lead</span><i className={x.status.toLowerCase().replaceAll(' ','-')}>{x.status}</i>{progress(x.progress)}</div>)}</div>}</section>
    <aside className="dept-card review"><header><div><small>LEADERSHIP REVIEW</small><h3>Next review brief</h3></div><button onClick={()=>onOpen('Meetings')}>Open</button></header><dl><div><dt>Previous MoM</dt><dd>{openActions?`${openActions} action${openActions===1?'':'s'} awaiting closure`:'No open Flow actions'}</dd></div><div><dt>Decision needed</dt><dd>{atRisk?'Review blocked work and dependencies':'No decision currently recorded'}</dd></div><div><dt>Risk watch</dt><dd>{atRisk?`${atRisk} item${atRisk===1?'':'s'} need attention`:'No exception recorded'}</dd></div></dl><button className="dept-link" onClick={()=>onOpen('Leadership review')}>Prepare leadership update <Icon name="arrow" size={15}/></button></aside>
   </div>
   <div className="dept-grid bottom">
    <section className="dept-card teams"><header><div><small>TEAM COORDINATION</small><h3>Delivery teams</h3></div><button onClick={()=>onOpen('Team board')}>Team board</button></header><div className="team-cards">{teams.length?teams.map(team=><article key={team.id}><b>{team.name}</b><small>{team.memberEmails.length} member{team.memberEmails.length===1?'':'s'} · {team.managerEmail||'Manager pending'}</small><span>{ownedTasks.filter(x=>x.participantEmails?.some(email=>team.memberEmails.includes(email))).filter(x=>x.status!=='Closed').length} open actions</span></article>):<div className="dept-empty compact"><b>Team memberships will appear here</b><span>Create or map teams in the Team Board once the department structure is confirmed.</span></div>}</div></section>
    <section className="dept-card control"><header><div><small>COORDINATION CONTROL</small><h3>Risks, RACI & budget references</h3></div></header><div className="control-list"><button onClick={()=>onOpen('Actions')}><span>Blocked actions</span><b>{ownedTasks.filter(x=>x.status==='Blocked').length}</b><Icon name="arrow" size={15}/></button><button onClick={()=>onOpen('Leadership review')}><span>RACI and decisions</span><em>Leadership review</em><Icon name="arrow" size={15}/></button><button onClick={()=>onNotice('Budget references will be linked from NCR and Goods Receipt. Flow will not duplicate financial records.')}><span>Budget position</span><em>Linked NCR / GRN</em><Icon name="arrow" size={15}/></button></div></section>
   </div>
  </section>
}
