import { useMemo, useState } from 'react'
import Icon from '../../components/Icon'
import { useLocalStore } from '../../lib/localStore'
import './FlowOrganisationChart.css'
type Department={id:string;name:string;status?:string}
type User={id:string;employeeCode?:string;name:string;email?:string;departmentId?:string;status?:string;designation?:string;reportsToId?:string;managerId?:string}
export default function FlowOrganisationChart({onMap}:{onMap:()=>void}){
 const [users]=useLocalStore<User[]>('itms.users.v1',[]);const [departments]=useLocalStore<Department[]>('itms.departments.v1',[]);const [departmentId,setDepartmentId]=useState('all');
 const people=useMemo(()=>users.filter(user=>user.status!=='Inactive'&&(departmentId==='all'||user.departmentId===departmentId)),[users,departmentId]);const idSet=new Set(people.map(item=>item.id));const managerId=(person:User)=>person.reportsToId||person.managerId||'';const roots=people.filter(person=>!managerId(person)||!idSet.has(managerId(person)));const children=(id:string)=>people.filter(person=>managerId(person)===id);
 const dept=(id?:string)=>departments.find(item=>item.id===id)?.name||'Not mapped';const initials=(name:string)=>name.split(' ').map(value=>value[0]).join('').slice(0,2).toUpperCase();
 function Person({person,depth=0}:{person:User;depth?:number}){const team=children(person.id);return <li className={depth>0?'nested':''}><article><i>{initials(person.name)}</i><div><b>{person.name}</b><small>{person.designation||'Employee'} · {dept(person.departmentId)}</small></div><span>{team.length?`${team.length} direct report${team.length===1?'':'s'}`:'Team member'}</span></article>{team.length>0&&depth<4&&<ul>{team.map(child=><Person key={child.id} person={child} depth={depth+1}/>)}</ul>}</li>}
 return <div className="flow-orgchart"><section className="flow-orgchart-head"><div><span>LIVE ORGANISATION HIERARCHY · ITMS USER MASTER</span><h1>Organisation chart</h1><p>Built automatically from the approved reporting relationships in the central User Master.</p></div><button onClick={onMap}><Icon name="allocation" size={17}/> Manage reporting lines</button></section><section className="flow-orgchart-tools"><label>Department<select value={departmentId} onChange={event=>setDepartmentId(event.target.value)}><option value="all">Whole organisation</option>{departments.filter(item=>item.status!=='Inactive').map(department=><option value={department.id} key={department.id}>{department.name}</option>)}</select></label><div><Icon name="masters" size={18}/><span><b>{people.length}</b> active people in this view</span></div><div><Icon name="allocation" size={18}/><span><b>{roots.length}</b> hierarchy root{roots.length===1?'':'s'}</span></div></section><section className="flow-orgchart-body"><header><div><span>HIERARCHY VIEW</span><h2>{departmentId==='all'?'Organisation structure':dept(departmentId)}</h2></div><button onClick={onMap}>Map exception <Icon name="arrow" size={14}/></button></header>{people.length?<div className="flow-orgtree-wrap"><ul className="flow-orgtree">{roots.map(person=><Person key={person.id} person={person}/>)}</ul></div>:<div className="flow-orgchart-empty"><Icon name="masters" size={28}/><b>No active users are available in this view.</b><span>Update the ITMS User Master, then return here.</span></div>}</section><section className="flow-orgchart-insight"><Icon name="assurance" size={21}/><div><b>How the chart behaves</b><span>Each employee appears only once under their direct reporting manager. If a reporting line is absent or its manager is outside the current filter, the employee appears as a visible root exception.</span></div><button onClick={onMap}>Review unmapped people</button></section></div>
}
