import {useEffect,useMemo,useState} from 'react'
import Icon from '../../components/Icon'
import {useLocalStore} from '../../lib/localStore'
import {saveFlowTeam,subscribeFlowTasks,subscribeFlowTeams,type FlowTaskRecord,type FlowTeamRecord} from './flowStore'
import './FlowTeamBoard.css'
type User={id:string;name:string;email?:string;status?:string;designation?:string};type Department={id:string;name:string;status?:string};type View='Overview'|'Work'|'People'|'Manager'|'Setup'
const lanes=['Not started','In progress','Awaiting review','Blocked'] as const
export default function FlowTeamBoard({identityEmail,isLeader,onNotice,onCreate}:{identityEmail:string;isLeader:boolean;onNotice:(text:string)=>void;onCreate:()=>void}){
 const [teams,setTeams]=useState<FlowTeamRecord[]>([]),[tasks,setTasks]=useState<FlowTaskRecord[]>([]),[teamId,setTeamId]=useState(''),[view,setView]=useState<View>('Overview'),[name,setName]=useState(''),[departmentId,setDepartmentId]=useState(''),[manager,setManager]=useState(identityEmail),[members,setMembers]=useState<string[]>([identityEmail])
 const [users]=useLocalStore<User[]>('itms.users.v1',[]),[departments]=useLocalStore<Department[]>('itms.departments.v1',[])
 useEffect(()=>{const a=subscribeFlowTeams(setTeams),b=subscribeFlowTasks(setTasks);return()=>{a();b()}},[])
 const people=users.filter(user=>user.status!=='Inactive'&&user.email),active=teams.filter(team=>team.status==='Active'),team=active.find(item=>item.id===teamId)||active[0],work=useMemo(()=>team?tasks.filter(task=>task.teamId===team.id):[],[tasks,team?.id]),person=(email:string)=>people.find(item=>item.email===email)?.name||email,dept=(id:string)=>departments.find(item=>item.id===id)?.name||'Department'
 const openWork=work.filter(item=>item.status!=='Closed'),priority=openWork.filter(item=>item.priority==='High'||item.status==='Blocked').sort((a,b)=>a.dueDate.localeCompare(b.dueDate)),attention=[...openWork.filter(item=>item.status==='Blocked'),...openWork.filter(item=>item.dueDate<new Date().toISOString().slice(0,10))]
 const toggle=(email:string)=>setMembers(items=>items.includes(email)?items.filter(item=>item!==email):[...items,email])
 const create=async()=>{if(!name.trim()||!departmentId||!manager||!members.length){onNotice('Select a department, team manager and at least one team member.');return};const now=new Date().toISOString();try{await saveFlowTeam({id:`TEAM-${Date.now().toString(36).toUpperCase()}`,name:name.trim(),departmentId,managerEmail:manager,memberEmails:[...new Set([manager,...members])],description:'',status:'Active',createdBy:identityEmail,createdAt:now,updatedAt:now},identityEmail,'Team created');setName('');setMembers([identityEmail]);onNotice('Team saved. Select it in the Team Workspace to begin allocation.')}catch{onNotice('The team could not be saved. Confirm Flow access and try again.')}}
 if(!active.length)return <div className="flow-team"><section className="flow-team-head"><div><span>TEAM WORKSPACE</span><h1>Create the first team</h1><p>A manager, member group and a shared work space are required before allocation can begin.</p></div></section>{isLeader?<section className="team-setup-card"><label>Team name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Infrastructure operations"/></label><label>Department<select value={departmentId} onChange={e=>setDepartmentId(e.target.value)}><option value="">Select department</option>{departments.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Manager<select value={manager} onChange={e=>setManager(e.target.value)}>{people.map(item=><option value={item.email} key={item.id}>{item.name}</option>)}</select></label><button className="flow-team-primary" onClick={()=>void create()}>Create team</button></section>:<section className="flow-team-empty"><b>No team is available to you yet.</b><span>Ask your department lead to create the team and add you as a member.</span></section>}</div>
 return <div className="flow-team"><section className="flow-team-head jira-head"><div><span>TEAM WORKSPACE · {dept(team!.departmentId).toUpperCase()}</span><h1>{team!.name}</h1><p>Manager: <b>{person(team!.managerEmail)}</b> · {team!.memberEmails.length} members</p></div><div className="flow-team-actions"><select value={team!.id} onChange={e=>setTeamId(e.target.value)}>{active.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select><button className="flow-team-primary" onClick={onCreate}><Icon name="plus" size={17}/> Allocate work</button></div></section><nav className="team-tabs">{(['Overview','Work','People',...(isLeader?['Manager','Setup'] as View[]:[])] as View[]).map(item=><button key={item} className={view===item?'active':''} onClick={()=>setView(item)}>{item}{item==='Work'&&<span>{openWork.length}</span>}{item==='People'&&<span>{team!.memberEmails.length}</span>}{item==='Manager'&&attention.length>0&&<span>{attention.length}</span>}</button>)}</nav>
 {view==='Overview'&&<><section className="team-pulse"><article><small>Due this week</small><b>{openWork.filter(item=>item.dueDate<=new Date(Date.now()+7*86400000).toISOString().slice(0,10)).length}</b></article><article><small>Awaiting review</small><b>{openWork.filter(item=>item.status==='Awaiting review').length}</b></article><article className={attention.length?'alert':''}><small>Needs attention</small><b>{attention.length}</b></article><article><small>Team capacity</small><b>{openWork.length>team!.memberEmails.length*4?'Review':'Balanced'}</b></article></section><div className="team-overview-grid"><section className="team-focus"><header><div><span>PRIORITY WORK</span><h2>What needs action now</h2></div><button onClick={()=>setView('Work')}>All work <Icon name="arrow" size={14}/></button></header>{priority.slice(0,6).map(item=><article key={item.id}><div><b>{item.title}</b><small>{person(item.ownerEmail)} · Due {item.dueDate}</small></div><em className={item.status.toLowerCase().replaceAll(' ','-')}>{item.status}</em></article>)}{!priority.length&&<p>Nothing urgent or blocked. The team is clear.</p>}</section><section className="team-attention"><header><span>MANAGER ATTENTION</span><h2>Exceptions only</h2></header>{attention.length?<>{attention.slice(0,4).map(item=><article key={item.id}><b>{item.status==='Blocked'?'Blocked':'Overdue'}</b><span>{item.title}</span></article>)}</>:<p>No blockers, overdue work or unassigned team actions.</p>}<button onClick={onCreate}>Allocate work <Icon name="arrow" size={14}/></button></section></div></>}
 {view==='Work'&&<section className="flow-board-wrap"><header><div><span>TEAM WORK</span><h2>Active board</h2></div><button onClick={onCreate}>Allocate work</button></header><div className="flow-team-lanes">{lanes.map(lane=><section key={lane} className={'flow-lane '+lane.toLowerCase().replaceAll(' ','-')}><header><b>{lane==='Awaiting review'?'Review':lane}</b><span>{work.filter(item=>item.status===lane).length}</span></header>{work.filter(item=>item.status===lane).map(item=><article key={item.id}><div className="flow-card-tag"><span>{person(item.ownerEmail)}</span></div><b>{item.title}</b><p>Due {item.dueDate}</p><footer><span className={item.priority==='High'?'urgent':''}>{item.priority}</span></footer></article>)}{!work.some(item=>item.status===lane)&&<div className="flow-empty-lane">No work</div>}</section>)}</div></section>}
 {view==='People'&&<section className="team-people"><header><div><span>TEAM MEMBERS</span><h2>Workload and ownership</h2></div><button onClick={onCreate}>Allocate work</button></header>{team!.memberEmails.map(email=>{const owned=openWork.filter(item=>item.ownerEmail===email);return <article key={email}><i>{person(email).slice(0,1).toUpperCase()}</i><div><b>{person(email)}</b><small>{email===team!.managerEmail?'Team manager':'Team member'} · {email}</small></div><span>{owned.length} open</span><em className={owned.length>5?'warning':''}>{owned.length>5?'Review workload':'Available'}</em></article>})}</section>}
 {view==='Manager'&&<><section className="manager-selector"><div><small>MANAGER VIEW</small><b>Delivery health</b><span>{team!.name}</span></div><article><small>Team members</small><b>{team!.memberEmails.length}</b><span>Active delivery group</span></article><article><small>Over capacity</small><b>{team!.memberEmails.filter(email=>openWork.filter(item=>item.ownerEmail===email).length>5).length}</b><span>More than 5 open items</span></article><article><small>Escalations</small><b>{attention.length}</b><span>Blocked or overdue work</span></article></section><div className="manager-grid"><section className="manager-panel"><header><div><span>WORKLOAD BALANCE</span><h2>Ownership by person</h2></div><button onClick={onCreate}><Icon name="plus" size={14}/>Allocate</button></header>{team!.memberEmails.map(email=>{const owned=openWork.filter(item=>item.ownerEmail===email),review=owned.filter(item=>item.status==='Awaiting review').length;return <article key={email}><i>{person(email).slice(0,1).toUpperCase()}</i><div><b>{person(email)}</b><small>{owned.length} open · {review} awaiting review</small></div><span className={owned.length>5?'workload-alert':''}>{owned.length>5?'Review workload':'Balanced'}</span></article>})}</section><section className="manager-panel"><header><div><span>EXCEPTIONS</span><h2>Manager attention only</h2></div><button onClick={onCreate}>Allocate work <Icon name="arrow" size={14}/></button></header>{attention.slice(0,8).map(item=><article className="allocation-row" key={item.id}><div><b>{item.title}</b><small>{person(item.ownerEmail)} · due {item.dueDate}</small></div><em className={item.status.toLowerCase().replaceAll(' ','-')}>{item.status==='Blocked'?'Blocked':item.dueDate<new Date().toISOString().slice(0,10)?'Overdue':item.status}</em></article>)}{!attention.length&&<p className="manager-note">No blocked or overdue work. This team’s delivery is currently on track.</p>}</section></div></>}
 {view==='Setup'&&<section className="team-setup-card"><header><div><span>TEAM SETUP</span><h2>Add another delivery group</h2></div></header><label>Team name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Team name"/></label><label>Department<select value={departmentId} onChange={e=>setDepartmentId(e.target.value)}><option value="">Select department</option>{departments.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Manager<select value={manager} onChange={e=>setManager(e.target.value)}>{people.map(item=><option value={item.email} key={item.id}>{item.name}</option>)}</select></label><div className="team-member-checks">{people.map(item=><label key={item.id}><input type="checkbox" checked={members.includes(item.email!)} onChange={()=>toggle(item.email!)}/>{item.name}</label>)}</div><button className="flow-team-primary" onClick={()=>void create()}>Save team</button></section>}</div>
}
