import Icon from '../../components/Icon'
import './FlowDataLibrary.css'
type Doc={name:string;meta:string;type:string;owner:string;status:string;updated:string}
const docs:Doc[]=[
 {name:'Leadership review deck',meta:'September 2026 · Monthly leadership review',type:'PPTX',owner:'Executive Office',status:'Approved',updated:'22 Sep'},
 {name:'Infrastructure resilience report',meta:'September 2026 · Information Technology',type:'PDF',owner:'IT Infrastructure',status:'In review',updated:'21 Sep'},
 {name:'Asset refresh evidence pack',meta:'Project · ITMS linked records',type:'XLSX',owner:'IT Operations',status:'Controlled',updated:'20 Sep'},
 {name:'Department action tracker',meta:'September 2026 · Team delivery',type:'XLSX',owner:'Information Technology',status:'Working copy',updated:'19 Sep'},
]
export default function FlowDataLibrary({onUpload,onOpen}:{onUpload:()=>void;onOpen:(section:'Meetings'|'Leadership review'|'Team board')=>void}){
 return <div className="flow-library"><section className="flow-library-head"><div><span>GOVERNED DATA LIBRARY</span><h1>Documents and evidence</h1><p>Controlled originals, grouped by department, period, meeting and project.</p></div><button onClick={onUpload}><Icon name="plus" size={17}/> Add document</button></section><section className="flow-library-filters"><button className="active">All records <b>24</b></button><button>Organisation</button><button>Information Technology</button><button>September 2026</button><button>Meeting material</button><div><Icon name="empty" size={17}/><input placeholder="Search documents, projects or owners"/></div></section><div className="flow-library-grid"><aside><header><span>LIBRARY PATH</span><b>Browse controlled records</b></header><button className="selected"><Icon name="dashboard" size={17}/> All library</button><button><Icon name="masters" size={17}/> Organisation</button><button><Icon name="inventory" size={17}/> Departments</button><button><Icon name="history" size={17}/> Meetings & MoM</button><button><Icon name="package" size={17}/> Projects</button><hr/><small>GROUP BY</small><button>Month <Icon name="chevron" size={14}/></button><button>Document type <Icon name="chevron" size={14}/></button></aside><section className="flow-library-table"><header><div><span>LIBRARY VIEW</span><h2>September 2026 · Information Technology</h2></div><button onClick={()=>onOpen('Meetings')}>Meeting board <Icon name="arrow" size={14}/></button></header><div className="flow-doc-head"><span>Name</span><span>Owner</span><span>Status</span><span>Updated</span><span/></div>{docs.map(doc=><article key={doc.name}><div className={'flow-doc-icon '+doc.type.toLowerCase()}>{doc.type}</div><div className="flow-doc-name"><b>{doc.name}</b><small>{doc.meta}</small></div><span className="flow-doc-owner">{doc.owner}</span><em className={doc.status.toLowerCase().replaceAll(' ','-')}>{doc.status}</em><time>{doc.updated}</time><button onClick={()=>onOpen(doc.type==='PPTX'?'Meetings':doc.status==='In review'?'Leadership review':'Team board')}>Open <Icon name="arrow" size={14}/></button></article>)}</section></div><section className="flow-library-note"><Icon name="assurance" size={21}/><div><b>Originals remain controlled.</b><span>Shared meeting copies, comments and action references never replace the approved source document.</span></div><button onClick={onUpload}>Manage access</button></section></div>
}
