import { useState } from 'react'
import Icon from '../../components/Icon'
import ReportsPanel from './ReportsPanel'
import FlowMyWork from './FlowMyWork'
import FlowTeamBoard from './FlowTeamBoard'
import FlowLeadershipReview from './FlowLeadershipReview'
import FlowMeetings from './FlowMeetings'
import FlowCalendar from './FlowCalendar'
import FlowDataLibrary from './FlowDataLibrary'
import FlowExecutiveReports from './FlowExecutiveReports'
import FlowControlCentre from './FlowControlCentre'
import FlowReportingMap from './FlowReportingMap'
import FlowOrganisationVisibilityChart from './FlowOrganisationVisibilityChart'
import FlowActionRegister from './FlowActionRegister'
import FlowDepartmentWorkspace from './FlowDepartmentWorkspace'
import './FlowWorkspace.css'

type Stage='Not started'|'In progress'|'Awaiting review'|'Blocked'
type Task={id:string;title:string;area:string;due:string;priority:string;stage:Stage;source:string}
const work:Task[]=[
 {id:'ACT-1043',title:'Close Q4 safety audit gaps',area:'Facilities Management',due:'28 Sep',priority:'High',stage:'In progress',source:'Facilities'},
 {id:'MOM-208',title:'Submit department leadership update',area:'Information Technology',due:'25 Sep',priority:'High',stage:'Awaiting review',source:'Flow'},
 {id:'ACT-1047',title:'Confirm laptop-refresh dependency',area:'Information Technology',due:'30 Sep',priority:'Medium',stage:'Not started',source:'ITMS'},
 {id:'NCR-61',title:'Review consumables approval variance',area:'Procurement',due:'02 Oct',priority:'Low',stage:'Blocked',source:'NCR'},
]
const tabs=['My Work','Department workspace','Actions','Leadership review','Meetings','Calendar','Data Library','Reports','Organisation','Reporting map','Control Centre'] as const

export default function FlowWorkspace({identityName,identityEmail,isLeader,isAdministrator,onExit}:{identityName:string;identityEmail:string;isLeader:boolean;isAdministrator:boolean;onExit:()=>void}){
 const [tab,setTab]=useState<string>('My Work')
 const [tasks,setTasks]=useState(work)
 const [notice,setNotice]=useState('')
 const update=(id:string)=>{setTasks(rows=>rows.map(x=>x.id===id?{...x,stage:x.stage==='Not started'?'In progress':x.stage==='In progress'?'Awaiting review':x.stage==='Awaiting review'?'Blocked':'In progress'}:x));setNotice('Progress saved and recorded in the action trail.')}
 const list=<div className="flow-table">{tasks.map(x=><article key={x.id}><div><b>{x.title}</b><small>{x.id} · {x.area}</small></div><span>Due {x.due}</span><em>{x.source}</em><i className={x.stage.toLowerCase().replaceAll(' ','-')}>{x.stage}</i><button onClick={()=>update(x.id)}>Update</button></article>)}</div>
 const board=<div className="kanban">{(['Not started','In progress','Awaiting review','Blocked'] as Stage[]).map(stage=><section key={stage}><header><b>{stage==='Awaiting review'?'Review':stage}</b><span>{tasks.filter(x=>x.stage===stage).length}</span></header>{tasks.filter(x=>x.stage===stage).map(x=><article key={x.id}><small>{x.priority} · {x.source}</small><b>{x.title}</b><p>{x.id} · Due {x.due}</p><button onClick={()=>update(x.id)}>Move <Icon name="arrow" size={14}/></button></article>)}</section>)}</div>
 const meeting=<section className="flow-card"><header><div><small>LEADERSHIP MEETING</small><h2>Monthly leadership review</h2></div><button className="primary" onClick={()=>setNotice('MoM action created and linked to the leadership review.')}>Create MoM action</button></header><div className="meeting-grid"><article><h3>Agenda</h3><ol><li>Previous MoM action closure</li><li>Department goals and exceptions</li><li>Cross-functional dependencies</li><li>Executive decisions required</li></ol></article><article><h3>Roll call</h3><p><b>8 of 10 present</b></p><p className="flow-good">● Priya Sharma · Present<br/>● James Carter · Present</p><p className="flow-warn">● Anita Verma · Awaiting</p></article><article><h3>Previous MoM</h3><p>2 actions are complete. One Facilities action remains in progress.</p><button onClick={()=>setTab('Leadership review')}>Open review <Icon name="arrow" size={14}/></button></article></div></section>
 const leadership=<section className="flow-card"><header><div><small>DEPARTMENT LEADERSHIP REVIEW</small><h2>Information Technology</h2></div><button className="primary" onClick={()=>setNotice('Leadership review remarks saved to the controlled action trail.')}>Add leadership remark</button></header><div className="leadership-grid"><article><h3>Goal review</h3><p><b>Infrastructure resilience programme</b><br/><small>In progress · Target 30 Sep</small></p><p><b>Asset verification closure</b><br/><small>On track · Target 27 Sep</small></p></article><article><h3>Previous MoM</h3><p>3 of 4 actions closed. One action needs leadership direction.</p><button onClick={()=>setTab('Meetings')}>View MoM action <Icon name="arrow" size={14}/></button></article><article><h3>Risk and decision</h3><p className="flow-warn"><b>Vendor renewal decision</b><br/>Due 27 Sep · Procurement dependency.</p><button onClick={()=>setNotice('Escalation marked for leadership decision.')}>Escalate for decision</button></article></div></section>
 const calendar=<section className="flow-card"><header><div><small>COMMON ORGANISATION CALENDAR</small><h2>September 2026</h2></div><button className="primary" onClick={()=>setNotice('New event will be enabled with the calendar master release.')}>Add event</button></header><div className="flow-table"><article><div><b>Monthly leadership review</b><small>Organisation · Agenda and previous MoM linked</small></div><span>26 Sep · 10:00</span><em>Leadership</em><i className="in-progress">Scheduled</i><button onClick={()=>setTab('Meetings')}>Open</button></article><article><div><b>IT department review</b><small>Information Technology · Goal status and risks</small></div><span>24 Sep · 15:00</span><em>Department</em><i className="not-started">Scheduled</i><button onClick={()=>setTab('Leadership review')}>Open</button></article><article><div><b>Asset refresh milestone</b><small>Infrastructure programme · Linked ITMS records</small></div><span>30 Sep · 12:00</span><em>Project</em><i className="awaiting-review">Upcoming</i><button onClick={()=>setNotice('Project calendar link opened.')}>View</button></article></div></section>
 const content=tab==='Reports'?<ReportsPanel open={setTab}/>:tab==='Calendar'?calendar:tab==='My Work'?<><section className="metrics"><article><span>My open work</span><b>{tasks.length}</b></article><article><span>Priority due</span><b>{tasks.filter(x=>x.priority==='High').length}</b></article><article><span>Blocked</span><b>{tasks.filter(x=>x.stage==='Blocked').length}</b></article><article><span>Next meeting</span><b>10:00</b></article></section><section className="flow-card"><header><div><small>MY ACTIONS</small><h2>Work requiring attention</h2></div><button>All work ▾</button></header>{list}</section></>:tab==='Team board'?<><section className="board-heading"><div><small>TEAM EXECUTION</small><h2>Operations delivery board</h2><p>Routine team work, clearly separated from leadership-review commitments.</p></div><button className="primary" onClick={()=>setNotice('New team action will be enabled after the team master is published.')}><Icon name="plus" size={17}/>Add work</button></section>{board}</>:tab==='Meetings'?meeting:tab==='Leadership review'?leadership:<section className="coming"><Icon name="dashboard" size={34}/><h2>{tab} foundation</h2><p>This governed workspace is registered and will be enabled in its next build stage.</p></section>
 const displayContent=tab==='My Work'?<FlowMyWork identityName={identityName} tasks={tasks} onCreate={()=>setTab('Actions')} onOpen={setTab} onUpdate={update}/>:tab==='Department workspace'?<FlowDepartmentWorkspace identityEmail={identityEmail} isLeader={isLeader} onNotice={setNotice} onOpen={setTab}/>:tab==='Actions'?<FlowActionRegister identityEmail={identityEmail} isLeader={isLeader} onNotice={setNotice}/>:tab==='Team board'?<FlowTeamBoard identityEmail={identityEmail} isLeader={isLeader} onNotice={setNotice} onCreate={()=>setTab('Actions')}/>:tab==='Leadership review'?<FlowLeadershipReview onOpen={setTab} onRemark={()=>setNotice('Leadership remark saved to the controlled action trail.')}/>:tab==='Meetings'?<FlowMeetings onOpen={setTab} onAction={()=>setTab('Actions')}/>:tab==='Calendar'?<FlowCalendar onOpen={setTab} onCreate={()=>setNotice('Calendar events will be enabled after the calendar master is published.')}/>:tab==='Reports'?<FlowExecutiveReports onOpen={setTab} onExport={()=>setNotice('Report export will be enabled with the governed reporting release.')}/>:tab==='Organisation'?<FlowOrganisationVisibilityChart identityEmail={identityEmail} isAdministrator={isAdministrator} onMap={()=>setTab('Reporting map')}/>:tab==='Reporting map'?<FlowReportingMap canManage={isLeader} onSaved={setNotice}/>:tab==='Control Centre'?<FlowControlCentre onAction={()=>setNotice('Control Centre updates will be enabled after the Flow governance master is published.')}/>:content
 if(tab==='Data Library')return <div className="flow"><header className="top"><div><img src="/brand/glassco-logo-transparent.png" alt="Glassco"/>CONNECT · <b>FLOW</b></div><span>GLASSCO WORKSPACE</span><small className="flow-user">{identityEmail}</small><button onClick={onExit}><Icon name="dashboard" size={17}/>All applications</button></header><div className="layout"><aside><h2>Glassco Flow</h2><small>WORK AND GOVERNANCE</small><nav>{tabs.map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}><Icon name="dashboard" size={18}/>{x}</button>)}</nav><footer>Controlled workspace<br/><small>Connected, not duplicated</small></footer></aside><main>{notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}<FlowDataLibrary onUpload={()=>setNotice('Document upload will be enabled after secure storage is configured.')} onOpen={setTab}/></main></div></div>
 if(tab==='Data Library')return <div className="flow"><header className="top"><div><img src="/brand/glassco-logo-transparent.png" alt="Glassco"/>CONNECT · <b>FLOW</b></div><span>GLASSCO WORKSPACE</span><button onClick={onExit}><Icon name="dashboard" size={17}/>All applications</button></header><main><header className="heading"><div><small>GOVERNED DATA LIBRARY</small><h1>Documents and evidence</h1><p>Controlled originals, grouped by department, period, meeting and project.</p></div><button className="primary" onClick={()=>setNotice('Upload will be enabled after secure document storage is configured.')}><Icon name="plus" size={17}/>Add document</button></header>{notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}<section className="flow-card"><header><div><small>LIBRARY VIEW</small><h2>September 2026 · Information Technology</h2></div><button onClick={()=>setTab('My Work')}>Return to My Work</button></header><div className="flow-table"><article><div><b>Leadership review deck</b><small>Meeting · September 2026 · PPTX · Version 2</small></div><span>26 Sep</span><em>Leadership</em><i className="in-progress">Approved</i><button>Open</button></article><article><div><b>Infrastructure resilience report</b><small>Department · September 2026 · PDF · Version 1</small></div><span>24 Sep</span><em>Department</em><i className="awaiting-review">Review</i><button>Open</button></article><article><div><b>Asset refresh evidence pack</b><small>Project · ITMS link · XLSX · Version 3</small></div><span>30 Sep</span><em>Project</em><i className="not-started">Draft</i><button>Open</button></article></div></section></main></div>
 return <div className="flow"><header className="top"><div><img src="/brand/glassco-logo-transparent.png" alt="Glassco"/>CONNECT · <b>FLOW</b></div><span>GLASSCO WORKSPACE</span><small className="flow-user">{identityEmail}</small><button onClick={onExit}><Icon name="dashboard" size={17}/>All applications</button></header><div className="layout"><aside><h2>Glassco Flow</h2><small>WORK AND GOVERNANCE</small><nav>{tabs.map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}><Icon name="dashboard" size={18}/>{x}</button>)}</nav><footer>Controlled workspace<br/><small>Connected, not duplicated</small></footer></aside><main>{tab!=='My Work'&&<header className="heading"><div><small>GLASSCO FLOW · {tab.toUpperCase()}</small><h1>{tab}</h1><p>{tab==='Meetings'?'Prepare, run and close governed meetings with no loss of accountability.':'Plan, review and progress governed work.'}</p></div></header>}{notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}{displayContent}</main></div></div>
}
