import Icon from '../../components/Icon'
import './FlowCalendar.css'
const events=[
 {day:24,month:'Sep',title:'IT department review',time:'3:00 PM',type:'Department',owner:'Information Technology',target:'Leadership review'},
 {day:26,month:'Sep',title:'Monthly leadership review',time:'10:00 AM',type:'Organisation',owner:'Executive Office',target:'Meetings'},
 {day:28,month:'Sep',title:'Facilities safety action review',time:'11:30 AM',type:'Department',owner:'Facilities Management',target:'Team board'},
 {day:30,month:'Sep',title:'Asset refresh milestone',time:'12:00 PM',type:'Project',owner:'IT Infrastructure',target:'Team board'},
]
export default function FlowCalendar({onOpen,onCreate}:{onOpen:(section:'Meetings'|'Leadership review'|'Team board')=>void;onCreate:()=>void}){
 return <div className="flow-calendar"><section className="flow-calendar-head"><div><span>COMMON ORGANISATION CALENDAR</span><h1>September 2026</h1><p>One governed view of organisation, department and project commitments.</p></div><div><button>Today</button><button className="flow-calendar-primary" onClick={onCreate}><Icon name="plus" size={17}/> Add event</button></div></section><section className="flow-calendar-summary"><article><i className="org"/><span><b>Organisation</b><small>2 events</small></span></article><article><i className="dept"/><span><b>Department</b><small>6 events</small></span></article><article><i className="project"/><span><b>Project</b><small>4 milestones</small></span></article><article><i className="due"/><span><b>Due this week</b><small>3 commitments</small></span></article></section><section className="flow-month"><header><div><button><Icon name="chevron" size={14}/></button><b>September 2026</b><button className="next"><Icon name="chevron" size={14}/></button></div><div className="flow-calendar-filters"><button className="selected">All events</button><button>Organisation</button><button>Department</button><button>Project</button></div></header><div className="flow-weekdays">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(day=><span key={day}>{day}</span>)}</div><div className="flow-days">{Array.from({length:35},(_,index)=>{const date=index-0;const current=date>=0&&date<30;const content=date===23?['IT department review','dept']:date===25?['Monthly leadership review','org']:date===27?['Facilities safety review','dept']:date===29?['Asset refresh milestone','project']:null;return <article key={index} className={!current?'muted':''}><b>{current?date+1:index<0?28+index:''}</b>{content&&<span className={content[1]}>{content[0]}</span>}</article>})}</div></section><section className="flow-upcoming"><header><div><span>UPCOMING COMMITMENTS</span><h2>Next seven days</h2></div><button onClick={()=>onOpen('Meetings')}>Open meeting board <Icon name="arrow" size={14}/></button></header><div>{events.map(event=><article key={event.title}><time><b>{event.day}</b><small>{event.month}</small></time><div><b>{event.title}</b><small>{event.time} · {event.owner}</small></div><em className={event.type.toLowerCase()}>{event.type}</em><button onClick={()=>onOpen(event.target as 'Meetings'|'Leadership review'|'Team board')}>Open <Icon name="arrow" size={14}/></button></article>)}</div></section></div>
}
