import { useMemo, useState } from 'react'
import Icon from '../../components/Icon'
import { useLocalStore } from '../../lib/localStore'
import './FlowOrganisationChart.css'
type Department={id:string;name:string;status?:string}
type User={id:string;name:string;email?:string;departmentId?:string;status?:string;designation?:string;reportsToId?:string;managerId?:string}
export default function FlowOrganisationVisibilityChart({identityEmail,isAdministrator,onMap}:{identityEmail:string;isAdministrator:boolean;onMap:()=>void}){
 const [users]=useLocalStore<User[]>('itms.users.v1',[]);const [departments]=useLocalStore<Department[]>('itms.departments.v1',[]);const [departmentId,setDepartmentId]=useState('all');const active=users.filter(user=>user.status!=='Inactive'),viewer=active.find(user=>user.email?.toLowerCase()===identityEmail.toLowerCase()),managerId=(person:User)=>person.reportsToId||person.managerId||'';
 const branchIds=useMemo(()=>{const ids=new Set<string>();if(!viewer)return ids;const add=(id:string)=>{if(ids.has(id))return;ids.add(id);active.filter(user=>managerId(user)===id).forEach(user=>add(user.id))};add(viewer.id);return ids},[viewer?.id,active]);const permitted=isAdministrator?active:viewer?active.filter(user=>branchIds.has(user.id)):[];const people=permitted.filter(user=>!isAdministrator||departmentId==='all'||user.departmentId===departmentId);const idSet=new Set(people.map(item=>item.id)),roots=people.filter(person=>!managerId(person)||!idSet.has(managerId(person))),children=(id:string)=>people.filter(person=>managerId(person)===id);const dept=(id?:string)=>departments.find(item=>item.id===id)?.name||'Not mapped';const initials=(name:string)=>name.split(' ').map(value=>value[0]).join('').slice(0,2).toUpperCase();
 function Person({person,depth=0}:{person:User;depth?:number}){const team=children(person.id);return <li><article><i>{initials(person.name)}</i><div><b>{person.name}</b><small>{person.designation||'Employee'} · {dept(person.departmentId)}</small></div><span>{team.length?`${team.length} direct report${team.length===1?'':'s'}`:'Team member'}</span></article>{team.length>0&&depth<4&&<ul>{team.map(child=><Person key={child.id} person={child} depth={depth+1}/>)}</ul>}</li>}
 return <div className="flow-orgchart"><section className="flow-orgchart-head"><div><span>LIVE ORGANISATION HIERARCHY · ITMS USER MASTER</span><h1>{isAdministrator?'Organisation chart':'My reporting branch'}</h1><p>{isAdministrator?'Built from the approved reporting relationships in the central User Master.':'Your view contains only your approved reporting branch.'}</p></div>{isAdministrator&&<button onClick={onMap}><Icon name="allocation" size={17}/> Manage reporting lines</button>}</section><section className="flow-orgchart-tools">{isAdministrator&&<label>Department<select value={departmentId} onChange={event=>setDepartmentId(event.target.value)}><option value="all">Whole organisation</option>{departments.filter(item=>item.status!=='Inactive').map(department=><option value={department.id} key={department.id}>{department.name}</option>)}</select></label>}<div><Icon name="masters" size={18}/><span><b>{people.length}</b> visible people</span></div><div><Icon name="allocation" size={18}/><span><b>{roots.length}</b> hierarchy root{roots.length===1?'':'s'}</span></div><span>{isAdministrator?'Full organisation view':'Department-lead view'}</span></section><section className="flow-orgchart-body"><header><div><span>HIERARCHY VIEW</span><h2>{isAdministrator?(departmentId==='all'?'Organisation structure':dept(departmentId)):(viewer?`${viewer.name}'s team`:'No linked employee record')}</h2></div>{isAdministrator&&<button onClick={onMap}>Map exception <Icon name="arrow" size={14}/></button>}</header>{people.length?<div className="flow-orgtree-wrap"><ul className="flow-orgtree">{roots.map(person=><Person key={person.id} person={person}/>)}</ul></div>:<div className="flow-orgchart-empty"><Icon name="masters" size={28}/><b>{viewer?'No mapped team members are visible yet.':'Your signed-in account is not linked to an active ITMS employee record.'}</b><span>{viewer?'Use Reporting map to complete the next relationship.':'Ask an administrator to link this Workspace account in ITMS Access & Roles.'}</span></div>}</section><section className="flow-orgchart-insight"><Icon name="assurance" size={21}/><div><b>{isAdministrator?'Full view is controlled by app administrator access.':'Your reporting branch is protected.'}</b><span>{isAdministrator?'Department filters are available only to administrators.':'Other departments remain hidden unless explicitly shared through Flow.'}</span></div>{isAdministrator&&<button onClick={onMap}>Review unmapped people</button>}</section></div>
}
