import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { confirmPasswordReset, verifyPasswordResetCode } from 'firebase/auth'
import { firebaseAuth } from '../../lib/firebase'
import Icon from '../../components/Icon'
import './PasswordActionPage.css'

export default function PasswordActionPage(){
  const params=useMemo(()=>new URLSearchParams(window.location.search),[]);const code=params.get('oobCode')??''
  const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [show,setShow]=useState(false);const [state,setState]=useState<'checking'|'ready'|'saving'|'complete'|'invalid'>('checking');const [error,setError]=useState('')
  useEffect(()=>{if(!firebaseAuth||!code){setState('invalid');return}void verifyPasswordResetCode(firebaseAuth,code).then(value=>{setEmail(value);setState('ready')}).catch(()=>setState('invalid'))},[code])
  async function submit(event:FormEvent){event.preventDefault();setError('');if(password.length<8){setError('Use at least 8 characters.');return}if(password!==confirm){setError('Passwords do not match.');return}if(!firebaseAuth)return;setState('saving');try{await confirmPasswordReset(firebaseAuth,code,password);setState('complete')}catch{setState('ready');setError('This reset link has expired or was already used. Request a new link and try again.')}}
  return <main className="password-action-page"><section className="password-action-brand"><img src="/brand/glassco-logo-transparent.png" alt="Glassco — A Glass Apart"/><span>GLASSCO WORKSPACE</span></section><section className="password-action-card"><div className="password-action-icon"><Icon name={state==='complete'?'check':'assurance'} size={25}/></div>{state==='checking'&&<><span className="eyebrow">SECURE ACCOUNT ACTION</span><h1>Checking reset link</h1><p>Please wait while Glassco Workspace verifies this request.</p></>}{state==='invalid'&&<><span className="eyebrow">LINK NOT AVAILABLE</span><h1>Request a new reset link</h1><p>This password-reset link is invalid, expired or has already been used.</p><a href="/">Return to Glassco Workspace</a></>}{state==='complete'&&<><span className="eyebrow">PASSWORD UPDATED</span><h1>Your password is secure</h1><p>The password for <strong>{email}</strong> has been changed successfully.</p><a href="/">Continue to sign in</a></>}{(state==='ready'||state==='saving')&&<><span className="eyebrow">SECURE COMPANY ACCESS</span><h1>Reset your password</h1><p>Set a new password for <strong>{email}</strong>.</p><form onSubmit={submit}><label>New password<div><input autoFocus type={show?'text':'password'} autoComplete="new-password" value={password} onChange={event=>setPassword(event.target.value)} required/><button type="button" onClick={()=>setShow(value=>!value)}>{show?'Hide':'Show'}</button></div><small>Minimum 8 characters; use a unique company password.</small></label><label>Confirm new password<input type={show?'text':'password'} autoComplete="new-password" value={confirm} onChange={event=>setConfirm(event.target.value)} required/></label>{error&&<div className="password-action-error">{error}</div>}<button className="password-action-submit" disabled={state==='saving'}>{state==='saving'?'Saving securely…':'Update password'}</button></form></>}</section><footer>Controlled access · Glassco Laboratory Equipments Pvt. Ltd. · Department of IT</footer></main>
}
