import { useMemo, useState, type FormEvent } from 'react'
import DataTable from '../../components/DataTable'
import { deriveCustody, type CustodyMovement } from '../../lib/custodyLifecycle'
import { useLocalStore } from '../../lib/localStore'
import './UserAssetProfile.css'
import type { MaintenanceRecord } from '../maintenance/MaintenanceWorkspace'
type User = { id: string; employeeCode: string; name: string; email: string; phone: string; departmentId: string; locationId: string; groupId: string; status: string }
type Basic = { id: string; code: string; name: string }
type Asset = { id: string; assetId: string; typeId: string; modelId: string; serialNumber: string; stockStatus: string }
type Model = { id: string; brand: string; name: string }
type AssetType = { id: string; code: string; name: string; status: string }
type Allocation = { id: string; code: string; userId: string; assetIds: string[]; replacementAssetId?: string; allocationKind?: string; allocationDate: string; state: string; requestedAt: string; itHeadApprovedAt: string }
type AssetIncident = { id: string; code: string; userId: string; assetId: string; type: 'Repair' | 'Damaged' | 'Breakage' | 'Lost' | 'Stolen' | 'Other'; severity: 'Low' | 'Medium' | 'High' | 'Critical'; eventDate: string; notes: string; status: 'Open' | 'Closed'; reportedAt: string; reportedBy: string; closedAt: string }
const today = () => new Date().toISOString().slice(0, 10)
export default function UserAssetProfile({ user, onClose }: { user: User; onClose: () => void }) {
  const [departments] = useLocalStore<Basic[]>('itms.departments.v1', []); const [locations] = useLocalStore<Basic[]>('itms.locations.v1', []); const [groups] = useLocalStore<Basic[]>('itms.user-groups.v1', [])
  const [assets, setAssets] = useLocalStore<Asset[]>('itms.assets.v1', []); const [models] = useLocalStore<Model[]>('itms.asset-models.v1', []); const [allocations] = useLocalStore<Allocation[]>('itms.allocations.v1', []); const [movements] = useLocalStore<CustodyMovement[]>('itms.custody-movements.v1', []); const [incidents, setIncidents] = useLocalStore<AssetIncident[]>('itms.asset-incidents.v1', [])
  const [types] = useLocalStore<AssetType[]>('itms.asset-types.v1', []); const [incidentGroupId, setIncidentGroupId] = useState('')
  const [maintenance] = useLocalStore<MaintenanceRecord[]>('itms.asset-maintenance.v1', [])
  const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState({ assetId: '', type: 'Repair' as AssetIncident['type'], severity: 'Medium' as AssetIncident['severity'], eventDate: today(), notes: '' })
  const custody = useMemo(() => deriveCustody(allocations, movements, assets), [allocations, movements, assets]); const currentAssets = assets.filter((asset) => custody.get(asset.id)?.userId === user.id)
  const historicalIds = new Set([...allocations.filter((item) => item.userId === user.id).flatMap((item) => [...item.assetIds, ...(item.replacementAssetId ? [item.replacementAssetId] : [])]), ...movements.filter((item) => item.fromUserId === user.id || item.toUserId === user.id).map((item) => item.assetId)])
  const selectableAssets = assets.filter((asset) => historicalIds.has(asset.id) || currentAssets.some((item) => item.id === asset.id)); const userIncidents = incidents.filter((item) => item.userId === user.id)
  function assetLabel(id: string) { const asset = assets.find((item) => item.id === id); const model = models.find((item) => item.id === asset?.modelId); return `${asset?.assetId ?? 'Unavailable'} · ${model ? `${model.brand} ${model.name}` : 'Model unavailable'}` }
  const history = [...allocations.filter((item) => item.userId === user.id).map((item) => ({ id: `a-${item.id}`, at: item.itHeadApprovedAt || item.requestedAt, event: item.allocationKind ?? 'Allocation', reference: item.code, assets: item.assetIds.map(assetLabel).join(' | '), status: item.state })), ...movements.filter((item) => item.fromUserId === user.id || item.toUserId === user.id).map((item) => ({ id: `m-${item.id}`, at: item.itHeadApprovedAt || item.requestedAt, event: item.kind === 'Transfer' ? (item.toUserId === user.id ? 'Transfer received' : 'Transfer released') : 'Return / revoke', reference: item.code, assets: assetLabel(item.assetId), status: item.state }))].sort((a, b) => b.at.localeCompare(a.at))
  function logIncident(event: FormEvent) { event.preventDefault(); const record: AssetIncident = { id: crypto.randomUUID(), code: `ASE-${new Date().getFullYear()}-${String(incidents.length + 1).padStart(4, '0')}`, userId: user.id, ...form, status: 'Open', reportedAt: new Date().toISOString(), reportedBy: 'dev@glasscolabs.com', closedAt: '' }; setIncidents((current) => [...current, record]); setAssets((current) => current.map((asset) => asset.id === record.assetId ? { ...asset, stockStatus: record.type === 'Lost' || record.type === 'Stolen' ? 'Missing - investigation' : ['Repair', 'Damaged', 'Breakage'].includes(record.type) ? 'Under repair' : asset.stockStatus } : asset)); setForm({ assetId: '', type: 'Repair', severity: 'Medium', eventDate: today(), notes: '' }); setFormOpen(false) }
  function closeIncident(id: string) { setIncidents((current) => current.map((item) => item.id === id ? { ...item, status: 'Closed', closedAt: new Date().toISOString() } : item)) }
  return <section className="master-panel user-profile"><div className="user-profile-header"><div><span className="eyebrow">USER IT ASSET PROFILE</span><h2>{user.employeeCode} · {user.name}</h2><p>{departments.find((item) => item.id === user.departmentId)?.name} · {locations.find((item) => item.id === user.locationId)?.name} · {groups.find((item) => item.id === user.groupId)?.name}</p><small>{user.email} · {user.phone} · User status: {user.status}</small></div><div><button type="button" className="secondary-action" onClick={onClose}>Back to User Master</button><button type="button" className="primary-action" onClick={() => setFormOpen(!formOpen)}>＋ Log asset event</button></div></div>
  {formOpen && <form className="master-form operation-form" onSubmit={logIncident}><label>Item group / category<select required value={incidentGroupId} onChange={(event) => { setIncidentGroupId(event.target.value); setForm({ ...form, assetId: '' }) }}><option value="">Select item group first</option>{types.filter((type) => selectableAssets.some((asset) => asset.typeId === type.id)).map((type) => <option value={type.id} key={type.id}>{type.code} · {type.name}</option>)}</select></label><label>Related asset<select required disabled={!incidentGroupId} value={form.assetId} onChange={(event) => setForm({ ...form, assetId: event.target.value })}><option value="">{incidentGroupId ? 'Select current or historical asset' : 'Select item group first'}</option>{selectableAssets.filter((asset) => asset.typeId === incidentGroupId).map((asset) => <option value={asset.id} key={asset.id}>{assetLabel(asset.id)}</option>)}</select></label><label>Event type<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value as AssetIncident['type'] })}><option>Repair</option><option>Damaged</option><option>Breakage</option><option>Lost</option><option>Stolen</option><option>Other</option></select></label><label>Severity<select value={form.severity} onChange={(event) => setForm({ ...form, severity: event.target.value as AssetIncident['severity'] })}><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></label><label>Event date<input required type="date" value={form.eventDate} onChange={(event) => setForm({ ...form, eventDate: event.target.value })} /></label><label className="wide-field">Description and escalation note<textarea required value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label><div className="form-actions"><button type="button" onClick={() => setFormOpen(false)}>Cancel</button><button className="primary-action" type="submit">Record event</button></div></form>}
  <div className="master-summary"><div><span>Current assets</span><strong>{currentAssets.length}</strong></div><div><span>Historical assets</span><strong>{historicalIds.size}</strong></div><div><span>Open escalations</span><strong>{userIncidents.filter((item) => item.status === 'Open').length}</strong></div></div>
  <section className="profile-section"><h3>Currently allocated</h3><DataTable rows={currentAssets} rowKey={(item) => item.id} columns={[{ key: 'asset', label: 'Asset ID', sticky: true, width: '180px', render: (item) => <strong>{item.assetId}</strong> }, { key: 'model', label: 'Brand / model', width: '250px', render: (item) => assetLabel(item.id).split(' · ').slice(1).join(' · ') }, { key: 'serial', label: 'Serial', width: '180px', render: (item) => item.serialNumber || 'Not applicable' }, { key: 'since', label: 'Custody since', width: '140px', render: (item) => custody.get(item.id)?.since }, { key: 'status', label: 'Asset status', width: '190px', render: (item) => item.stockStatus }]} empty={<div className="empty-state"><strong>No current asset custody</strong><p>This employee does not currently hold an IT asset.</p></div>} /></section>
  <section className="profile-section"><h3>Allocation and custody history</h3><DataTable rows={history} rowKey={(item) => item.id} columns={[{ key: 'date', label: 'Date', sticky: true, width: '190px', render: (item) => new Date(item.at).toLocaleString('en-IN') }, { key: 'event', label: 'Event', width: '180px', render: (item) => item.event }, { key: 'reference', label: 'Reference', width: '170px', render: (item) => item.reference }, { key: 'assets', label: 'Assets', width: '480px', render: (item) => item.assets }, { key: 'status', label: 'Status', width: '170px', render: (item) => item.status }]} empty={<div className="empty-state"><strong>No allocation history</strong><p>No governed custody transaction has been recorded.</p></div>} /></section>
  <section className="profile-section"><h3>Repair, loss, damage and escalation history</h3><DataTable rows={[...userIncidents].reverse()} rowKey={(item) => item.id} columns={[{ key: 'code', label: 'Reference', sticky: true, width: '170px', render: (item) => <><strong>{item.code}</strong><small>{item.type}</small></> }, { key: 'asset', label: 'Asset', width: '250px', render: (item) => assetLabel(item.assetId) }, { key: 'date', label: 'Event date', width: '130px', render: (item) => item.eventDate }, { key: 'severity', label: 'Severity', width: '110px', render: (item) => item.severity }, { key: 'notes', label: 'Details', width: '420px', render: (item) => item.notes }, { key: 'status', label: 'Status', width: '110px', render: (item) => item.status }, { key: 'action', label: 'Action', width: '120px', render: (item) => item.status === 'Open' ? <button className="table-action" type="button" onClick={() => closeIncident(item.id)}>Close</button> : 'Closed' }]} empty={<div className="empty-state"><strong>No repair or escalation history</strong><p>Loss, theft, damage, breakage and repair events will appear here.</p></div>} /></section>
  <section className="profile-section"><h3>Asset maintenance and inspection history</h3><DataTable rows={maintenance.filter((item) => historicalIds.has(item.assetId)).sort((a, b) => (b.completedAt || b.createdAt).localeCompare(a.completedAt || a.createdAt))} rowKey={(item) => item.id} columns={[{ key: 'code', label: 'Reference', sticky: true, width: '170px', render: (item) => <><strong>{item.code}</strong><small>{item.kind}</small></> }, { key: 'asset', label: 'Asset', width: '260px', render: (item) => assetLabel(item.assetId) }, { key: 'activity', label: 'Activity', width: '280px', render: (item) => item.activity }, { key: 'date', label: 'Service / due date', width: '140px', render: (item) => item.performedDate || item.dueDate }, { key: 'outcome', label: 'Outcome / status', width: '180px', render: (item) => item.outcome || item.state }, { key: 'details', label: 'Findings', width: '420px', render: (item) => item.findings || item.notes }]} empty={<div className="empty-state"><strong>No maintenance history</strong><p>Scheduled and completed service records for this employee’s assets will appear here.</p></div>} /></section></section>
}
