import { useMemo, useState } from 'react'
import { useLocalStore } from '../../lib/localStore'
import Icon from '../../components/Icon'
import type { MaintenanceRecord } from '../maintenance/MaintenanceWorkspace'
import type { DisposalRecord } from '../assurance/AssuranceWorkspace'
import type { RetirementRecord } from '../retirement/RetirementWorkspace'
import './NotificationCenter.css'

type Allocation={id:string;code:string;state:string;requestedAt:string}
type Lifecycle={id:string;code:string;kind:string;state:string;createdAt:string}
type Incident={id:string;code:string;type:string;status:string;reportedAt:string}
type Asset={id:string;assetId:string;modelId:string;purchaseDate:string}
type Model={id:string;brand:string;name:string;warrantyMonths:string}
type Notice={id:string;title:string;detail:string;date:string;severity:'Information'|'Attention'|'Urgent';module:string;emailSubject:string}
type Delivery={id:string;noticeId:string;recipient:string;status:string;preparedAt:string}
type NotificationRule={id:string;event:string;recipient:string;leadDays:number;escalationDays:number;enabled:boolean;updatedAt:string}
const today=()=>new Date().toISOString().slice(0,10)
const CURRENT_DATE=today()
const addDays=(date:string,days:number)=>{const value=new Date(`${date}T00:00:00`);value.setDate(value.getDate()+days);return value.toISOString().slice(0,10)}
const addMonths=(date:string,months:number)=>{const value=new Date(`${date}T00:00:00`);value.setMonth(value.getMonth()+months);return value.toISOString().slice(0,10)}

export default function NotificationCenter({onNavigate}:{onNavigate:(module:string)=>void}){
  const [open,setOpen]=useState(false);const [historyOpen,setHistoryOpen]=useState(false);const [readIds,setReadIds]=useLocalStore<string[]>('itms.notification-read.v1',[]);const [deliveries,setDeliveries]=useLocalStore<Delivery[]>('itms.notification-deliveries.v1',[]);const [rules]=useLocalStore<NotificationRule[]>('itms.notification-rules.v1',[])
  const [allocations]=useLocalStore<Allocation[]>('itms.allocations.v1',[]);const [maintenance]=useLocalStore<MaintenanceRecord[]>('itms.asset-maintenance.v1',[]);const [disposals]=useLocalStore<DisposalRecord[]>('itms.asset-disposals.v1',[]);const [retirements]=useLocalStore<RetirementRecord[]>('itms.asset-retirements.v1',[]);const [lifecycle]=useLocalStore<Lifecycle[]>('itms.employee-lifecycle.v1',[]);const [incidents]=useLocalStore<Incident[]>('itms.asset-incidents.v1',[]);const [assets]=useLocalStore<Asset[]>('itms.assets.v1',[]);const [models]=useLocalStore<Model[]>('itms.asset-models.v1',[])
  const notices=useMemo<Notice[]>(()=>{
    const rows:Notice[]=[]
    allocations.filter((item)=>item.state.startsWith('Pending')).forEach((item)=>rows.push({id:`allocation-${item.id}-${item.state}`,title:`${item.code} requires approval`,detail:item.state,date:item.requestedAt,severity:'Attention',module:'Allocation & Custody',emailSubject:`ITMS approval required: ${item.code}`}))
    maintenance.filter((item)=>item.state==='Scheduled'&&item.dueDate<=addDays(CURRENT_DATE,30)).forEach((item)=>rows.push({id:`maintenance-${item.id}-${item.dueDate}`,title:`${item.code} ${item.dueDate<CURRENT_DATE?'is overdue':'is due soon'}`,detail:`${item.activity} · due ${item.dueDate}`,date:`${item.dueDate}T00:00:00`,severity:item.dueDate<CURRENT_DATE?'Urgent':'Attention',module:'Maintenance & Inspection',emailSubject:`ITMS maintenance ${item.dueDate<CURRENT_DATE?'overdue':'due'}: ${item.code}`}))
    disposals.filter((item)=>item.state.startsWith('Pending')).forEach((item)=>rows.push({id:`disposal-${item.id}-${item.state}`,title:`${item.code} requires disposal approval`,detail:item.state,date:item.managerAt||item.requestedAt,severity:'Attention',module:'Assurance & Controls',emailSubject:`ITMS disposal approval required: ${item.code}`}))
    retirements.filter((item)=>!['Completed','Cancelled'].includes(item.state)).forEach((item)=>rows.push({id:`retirement-${item.id}-${item.state}`,title:`${item.code} requires retirement action`,detail:`${item.route} · ${item.assetIds?.length||Number(Boolean(item.assetId))} assets · ${item.state}`,date:item.headAt||item.managerAt||item.requestedAt,severity:item.state==='Approved - awaiting handover'?'Urgent':'Attention',module:'Asset Retirement & Circularity',emailSubject:`ITMS retirement action required: ${item.code}`}))
    lifecycle.filter((item)=>item.state!=='Completed').forEach((item)=>rows.push({id:`lifecycle-${item.id}-${item.state}`,title:`${item.code} awaiting sign-off`,detail:`${item.kind} · ${item.state}`,date:item.createdAt,severity:'Attention',module:'Allocation & Custody',emailSubject:`ITMS ${item.kind} sign-off: ${item.code}`}))
    incidents.filter((item)=>item.status==='Open').forEach((item)=>rows.push({id:`incident-${item.id}`,title:`${item.code} remains open`,detail:`Asset event · ${item.type}`,date:item.reportedAt,severity:['Lost','Stolen'].includes(item.type)?'Urgent':'Attention',module:'Shared Masters',emailSubject:`ITMS open asset event: ${item.code}`}))
    assets.forEach((asset)=>{const model=models.find((item)=>item.id===asset.modelId);const months=Number(model?.warrantyMonths||0);if(!months)return;const expiry=addMonths(asset.purchaseDate,months);if(expiry>=CURRENT_DATE&&expiry<=addDays(CURRENT_DATE,90))rows.push({id:`warranty-${asset.id}-${expiry}`,title:`${asset.assetId} warranty expires soon`,detail:`${model?.brand} ${model?.name} · ${expiry}`,date:`${expiry}T00:00:00`,severity:'Information',module:'Asset Inventory',emailSubject:`ITMS warranty expiry: ${asset.assetId}`})})
    return rows.sort((a,b)=>b.date.localeCompare(a.date))
  },[allocations,assets,disposals,incidents,lifecycle,maintenance,models,retirements])
  const unread=notices.filter((item)=>!readIds.includes(item.id)).length
  function markRead(id:string){setReadIds((current)=>current.includes(id)?current:[...current,id])}
  function visit(notice:Notice){markRead(notice.id);setOpen(false);onNavigate(notice.module)}
  function prepareEmail(notice:Notice){markRead(notice.id);const event=notice.id.startsWith('warranty-')?'Warranty expiry':notice.id.startsWith('maintenance-')?'Maintenance due':notice.id.startsWith('lifecycle-')?'Employee offboarding':notice.id.startsWith('incident-')?'Open repair':'Pending approval';const recipient=rules.find((rule)=>rule.enabled&&rule.event===event)?.recipient||'dev@glasscolabs.com';const body=`Glassco Connect ITMS notification%0D%0A%0D%0A${encodeURIComponent(notice.title)}%0D%0A${encodeURIComponent(notice.detail)}%0D%0A%0D%0APlease verify against the live controlled ITMS record.`;setDeliveries((current)=>[...current,{id:crypto.randomUUID(),noticeId:notice.id,recipient,status:'Prepared in email client',preparedAt:new Date().toISOString()}]);window.location.href=`mailto:${recipient}?subject=${encodeURIComponent(notice.emailSubject)}&body=${body}`}
  return <div className="notification-centre"><button type="button" className="notification-trigger" aria-label={`${unread} unread notifications`} onClick={()=>setOpen(!open)}><Icon name="bell" size={20}/><span>Alerts</span>{unread>0&&<b>{unread>99?'99+':unread}</b>}</button>{open&&<section className="notification-panel"><header><div><strong>ITMS notifications</strong><small>{unread} unread · {notices.length} active</small></div><button type="button" onClick={()=>setOpen(false)}><Icon name="close" size={18}/></button></header><nav><button type="button" className={!historyOpen?'active':''} onClick={()=>setHistoryOpen(false)}>Active alerts</button><button type="button" className={historyOpen?'active':''} onClick={()=>setHistoryOpen(true)}>Email history</button></nav>{!historyOpen?<div className="notification-list">{notices.map((notice)=><article className={readIds.includes(notice.id)?'read':''} key={notice.id}><i className={notice.severity.toLowerCase()}></i><div><strong>{notice.title}</strong><span>{notice.detail}</span><small>{notice.severity} · {notice.date.slice(0,10)}</small></div><div><button type="button" onClick={()=>visit(notice)}>Open</button><button type="button" onClick={()=>prepareEmail(notice)}>Email</button></div></article>)}{!notices.length&&<p className="notification-empty">No active ITMS alerts.</p>}</div>:<div className="notification-list">{[...deliveries].reverse().map((item)=><article key={item.id}><i className="information"></i><div><strong>{notices.find((notice)=>notice.id===item.noticeId)?.title||'Historical notification'}</strong><span>{item.recipient}</span><small>{item.status} · {new Date(item.preparedAt).toLocaleString('en-IN')}</small></div></article>)}{!deliveries.length&&<p className="notification-empty">No emails prepared yet.</p>}</div>}<footer><button type="button" onClick={()=>setReadIds(notices.map((item)=>item.id))}>Mark all read</button><small>Email uses the local device email client; no paid sending service is enabled.</small></footer></section>}</div>
}
