import { useCallback, useMemo, useState, type FormEvent } from 'react'
import DataTable from '../../components/DataTable'
import Icon from '../../components/Icon'
import { useLocalStore } from '../../lib/localStore'
import './OperationsCentre.css'

type Tab='Global search'|'Approval inbox'|'Warranty'|'Stock verification'|'Controlled export'|'Notification rules'|'Data quality'
type Basic={id:string;code:string;name:string;email?:string;contact?:string}
type User={id:string;employeeCode:string;name:string;email:string;departmentId:string;locationId:string;groupId:string;status:string}
type Asset={id:string;assetId:string;typeId:string;modelId:string;serialNumber:string;locationId:string;configId:string;purchaseDate:string;cost:number;condition:string;stockStatus:string}
type Model={id:string;code:string;name:string;brand:string;typeId:string;warrantyMonths:string}
type Allocation={id:string;code:string;userId:string;assetIds:string[];state:string;requestedAt:string}
type Maintenance={id:string;code:string;assetId:string;activity:string;vendorId:string;state:string;dueDate:string;createdAt:string;completedAt:string}
type Incident={id:string;code:string;assetId:string;userId:string;type:string;status:string;reportedAt:string;notes:string}
type Lifecycle={id:string;code:string;kind:string;userId:string;assetIds:string[];state:string;createdAt:string}
type Disposal={id:string;code:string;assetId:string;state:string;requestedAt:string;managerAt:string}
type Retirement={id:string;code:string;assetIds:string[];assetId?:string;route:string;state:string;requestedAt:string;managerAt:string}
type Verification={id:string;code:string;assetId:string;result:string;verifiedDate:string;createdAt:string}
type WarrantyClaim={id:string;code:string;assetId:string;vendorId:string;reportedDate:string;rmaReference:string;claimStatus:'Draft'|'Submitted'|'Accepted'|'Rejected'|'Resolved';replacementOutcome:string;closedAt:string;updatedAt:string}
type NotificationRule={id:string;event:string;recipient:string;leadDays:number;escalationDays:number;enabled:boolean;updatedAt:string}
type SearchRow={id:string;kind:string;reference:string;title:string;detail:string;module:string}
type ApprovalRow={id:string;kind:string;reference:string;state:string;submitted:string;module:string}
type QualityIssue={id:string;severity:'Critical'|'Warning';kind:string;reference:string;issue:string;module:string}
const today=()=>new Date().toISOString().slice(0,10)
const addMonths=(date:string,months:number)=>{const value=new Date(`${date}T00:00:00`);if(Number.isNaN(value.getTime()))return'';value.setMonth(value.getMonth()+months);return value.toISOString().slice(0,10)}
const csvCell=(value:unknown)=>`"${String(value??'').replaceAll('"','""')}"`
function download(name:string,content:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)}

export default function OperationsCentre({onNavigate}:{onNavigate:(module:string,focus?:string)=>void}){
  const [tab,setTab]=useState<Tab>('Global search');const [query,setQuery]=useState('');const [message,setMessage]=useState('');const [claimOpen,setClaimOpen]=useState(false)
  const [users]=useLocalStore<User[]>('itms.users.v1',[]);const [departments]=useLocalStore<Basic[]>('itms.departments.v1',[]);const [locations]=useLocalStore<Basic[]>('itms.locations.v1',[]);const [userGroups]=useLocalStore<Basic[]>('itms.user-groups.v1',[]);const [vendors]=useLocalStore<Basic[]>('itms.vendors.v1',[]);const [types]=useLocalStore<Basic[]>('itms.asset-types.v1',[]);const [models]=useLocalStore<Model[]>('itms.asset-models.v1',[]);const [profiles]=useLocalStore<Basic[]>('itms.config-profiles.v1',[]);const [assets]=useLocalStore<Asset[]>('itms.assets.v1',[]);const [allocations]=useLocalStore<Allocation[]>('itms.allocations.v1',[]);const [maintenance]=useLocalStore<Maintenance[]>('itms.asset-maintenance.v1',[]);const [incidents]=useLocalStore<Incident[]>('itms.asset-incidents.v1',[]);const [lifecycle]=useLocalStore<Lifecycle[]>('itms.employee-lifecycle.v1',[]);const [disposals]=useLocalStore<Disposal[]>('itms.asset-disposals.v1',[]);const [retirements]=useLocalStore<Retirement[]>('itms.asset-retirements.v1',[]);const [verifications]=useLocalStore<Verification[]>('itms.asset-verifications.v1',[]);const [claims,setClaims]=useLocalStore<WarrantyClaim[]>('itms.warranty-claims.v1',[]);const [rules,setRules]=useLocalStore<NotificationRule[]>('itms.notification-rules.v1',[])
  const [claim,setClaim]=useState({assetId:'',vendorId:'',reportedDate:today(),rmaReference:'',claimStatus:'Draft' as WarrantyClaim['claimStatus'],replacementOutcome:''})
  void profiles
  const assetLabel=useCallback((id:string)=>{const asset=assets.find(item=>item.id===id),model=models.find(item=>item.id===asset?.modelId);return asset?`${asset.assetId} · ${model?.brand??''} ${model?.name??'Unknown model'}`:'Unavailable asset'},[assets,models])
  const userLabel=useCallback((id:string)=>{const user=users.find(item=>item.id===id);return user?`${user.employeeCode} · ${user.name}`:'Unavailable user'},[users])
  const go=(module:string,focus:string)=>{localStorage.setItem('itms.navigation-focus.v1',JSON.stringify({module,focus,at:new Date().toISOString()}));onNavigate(module,focus)}
  const searchRows=useMemo<SearchRow[]>(()=>[
    ...assets.map(item=>({id:`asset-${item.id}`,kind:'Asset',reference:item.assetId,title:assetLabel(item.id),detail:`Serial ${item.serialNumber||'N/A'} · ${item.stockStatus}`,module:'Asset Inventory'})),
    ...users.map(item=>({id:`user-${item.id}`,kind:'Employee',reference:item.employeeCode,title:item.name,detail:`${item.email} · ${departments.find(value=>value.id===item.departmentId)?.name??'Department unavailable'}`,module:'Shared Masters'})),
    ...vendors.map(item=>({id:`vendor-${item.id}`,kind:'Vendor',reference:item.code,title:item.name,detail:item.email||item.contact||'No contact recorded',module:'Asset Inventory'})),
    ...allocations.map(item=>({id:`allocation-${item.id}`,kind:'Allocation',reference:item.code,title:userLabel(item.userId),detail:`${item.assetIds.length} assets · ${item.state}`,module:'Allocation & Custody'})),
    ...maintenance.map(item=>({id:`maintenance-${item.id}`,kind:'Maintenance / repair',reference:item.code,title:assetLabel(item.assetId),detail:`${item.activity} · ${item.state}`,module:'Maintenance & Inspection'})),
    ...incidents.map(item=>({id:`incident-${item.id}`,kind:'Asset incident',reference:item.code,title:assetLabel(item.assetId),detail:`${item.type} · ${item.status}`,module:'Shared Masters'})),
    ...lifecycle.map(item=>({id:`lifecycle-${item.id}`,kind:`${item.kind} lifecycle`,reference:item.code,title:userLabel(item.userId),detail:`${item.assetIds.length} assets · ${item.state}`,module:'Allocation & Custody'})),
  ],[assets,users,vendors,allocations,maintenance,incidents,lifecycle,departments,assetLabel,userLabel])
  const filteredSearch=useMemo(()=>{const value=query.trim().toLowerCase();return value.length<2?[]:searchRows.filter(item=>`${item.kind} ${item.reference} ${item.title} ${item.detail}`.toLowerCase().includes(value)).slice(0,100)},[query,searchRows])
  const approvals=useMemo<ApprovalRow[]>(()=>[
    ...allocations.filter(item=>item.state.startsWith('Pending')).map(item=>({id:`a-${item.id}`,kind:'Asset allocation',reference:item.code,state:item.state,submitted:item.requestedAt,module:'Allocation & Custody'})),
    ...disposals.filter(item=>item.state.startsWith('Pending')).map(item=>({id:`d-${item.id}`,kind:'Disposal / write-off',reference:item.code,state:item.state,submitted:item.managerAt||item.requestedAt,module:'Assurance & Controls'})),
    ...retirements.filter(item=>item.state.startsWith('Pending')).map(item=>({id:`r-${item.id}`,kind:item.route,reference:item.code,state:item.state,submitted:item.managerAt||item.requestedAt,module:'Asset Retirement & Circularity'})),
  ].sort((a,b)=>a.submitted.localeCompare(b.submitted)),[allocations,disposals,retirements])
  const warranties=useMemo(()=>assets.map(asset=>{const model=models.find(item=>item.id===asset.modelId);const expiry=addMonths(asset.purchaseDate,Number(model?.warrantyMonths||0));const claim=claims.find(item=>item.assetId===asset.id&&!['Rejected','Resolved'].includes(item.claimStatus));return{...asset,model,expiry,claim}}).filter(item=>Number(item.model?.warrantyMonths||0)>0).sort((a,b)=>a.expiry.localeCompare(b.expiry)),[assets,models,claims])
  const quality=useMemo<QualityIssue[]>(()=>{const rows:QualityIssue[]=[];const serials=new Map<string,Asset[]>();assets.forEach(asset=>{if(asset.serialNumber){const key=asset.serialNumber.trim().toLowerCase();serials.set(key,[...(serials.get(key)??[]),asset])}if(!models.some(item=>item.id===asset.modelId))rows.push({id:`model-${asset.id}`,severity:'Critical',kind:'Orphan asset',reference:asset.assetId,issue:'Model reference is unavailable',module:'Asset Inventory'});if(!types.some(item=>item.id===asset.typeId))rows.push({id:`type-${asset.id}`,severity:'Critical',kind:'Orphan asset',reference:asset.assetId,issue:'Item group reference is unavailable',module:'Asset Inventory'});if(!locations.some(item=>item.id===asset.locationId))rows.push({id:`location-${asset.id}`,severity:'Critical',kind:'Orphan asset',reference:asset.assetId,issue:'Location reference is unavailable',module:'Asset Inventory'});if(!asset.configId)rows.push({id:`config-${asset.id}`,severity:'Warning',kind:'Incomplete asset',reference:asset.assetId,issue:'Configuration profile is not assigned',module:'Asset Inventory'});const model=models.find(item=>item.id===asset.modelId);if(model&&addMonths(asset.purchaseDate,Number(model.warrantyMonths||0))<today())rows.push({id:`warranty-${asset.id}`,severity:'Warning',kind:'Expired warranty',reference:asset.assetId,issue:'Warranty has expired',module:'Operations Centre'})});serials.forEach(group=>{if(group.length>1)group.forEach(asset=>rows.push({id:`serial-${asset.id}`,severity:'Critical',kind:'Duplicate serial',reference:asset.assetId,issue:`Serial ${asset.serialNumber} is used by ${group.length} assets`,module:'Asset Inventory'}))});users.forEach(user=>{if(!departments.some(item=>item.id===user.departmentId)||!locations.some(item=>item.id===user.locationId)||!userGroups.some(item=>item.id===user.groupId))rows.push({id:`user-${user.id}`,severity:'Critical',kind:'Unmapped employee',reference:user.employeeCode,issue:'Department, location or user group is unavailable',module:'Shared Masters'})});allocations.filter(item=>item.state==='Active custody').forEach(item=>item.assetIds.forEach(assetId=>{if(!assets.some(asset=>asset.id===assetId))rows.push({id:`custody-${item.id}-${assetId}`,severity:'Critical',kind:'Broken custody',reference:item.code,issue:'Allocation references an unavailable asset',module:'Allocation & Custody'})}));return rows},[assets,models,types,locations,users,departments,userGroups,allocations])
  function saveClaim(event:FormEvent){event.preventDefault();const now=new Date().toISOString();const record:WarrantyClaim={id:crypto.randomUUID(),code:`WAR-${new Date().getFullYear()}-${String(claims.length+1).padStart(4,'0')}`,assetId:claim.assetId,vendorId:claim.vendorId,reportedDate:claim.reportedDate,rmaReference:claim.rmaReference.trim(),claimStatus:claim.claimStatus,replacementOutcome:claim.replacementOutcome.trim(),closedAt:['Rejected','Resolved'].includes(claim.claimStatus)?now:'',updatedAt:now};setClaims(current=>[...current,record]);setClaimOpen(false);setClaim({assetId:'',vendorId:'',reportedDate:today(),rmaReference:'',claimStatus:'Draft',replacementOutcome:''});setMessage(`${record.code} warranty claim recorded.`)}
  function addRule(){setRules(current=>[...current,{id:crypto.randomUUID(),event:'Warranty expiry',recipient:'dev@glasscolabs.com',leadDays:30,escalationDays:7,enabled:true,updatedAt:new Date().toISOString()}])}
  function exportPackage(){const data:Record<string,unknown>={};for(let index=0;index<localStorage.length;index++){const key=localStorage.key(index);if(key?.startsWith('itms.')){try{data[key]=JSON.parse(localStorage.getItem(key)??'null')}catch{data[key]=localStorage.getItem(key)}}}const envelope={format:'Glassco Connect ITMS controlled export',version:1,generatedAt:new Date().toISOString(),generatedBy:'dev@glasscolabs.com',recordStores:Object.keys(data).length,data};download(`ITMS-controlled-export-${today()}.json`,JSON.stringify(envelope,null,2),'application/json;charset=utf-8');setMessage('Complete controlled JSON export generated from all ITMS record stores.')}
  function exportIndex(){const rows=['Store,Records',...Array.from({length:localStorage.length},(_,index)=>localStorage.key(index)).filter((key):key is string=>Boolean(key?.startsWith('itms.'))).map(key=>{try{const value=JSON.parse(localStorage.getItem(key)??'[]');return`${csvCell(key)},${Array.isArray(value)?value.length:1}`}catch{return`${csvCell(key)},1`}})];download(`ITMS-export-index-${today()}.csv`,rows.join('\r\n'),'text/csv;charset=utf-8')}
  return <><section className="page-heading"><div><span className="eyebrow">GCCP-ITMS-BUILD-20</span><h1>ITMS Operations Centre</h1><p>Search, approvals, warranty, verification, export, notifications and data-quality control.</p></div><span className="phase">PHASE 1 CONTROL GATE</span></section><nav className="workspace-tabs operations-tabs">{(['Global search','Approval inbox','Warranty','Stock verification','Controlled export','Notification rules','Data quality'] as Tab[]).map(item=><button type="button" className={tab===item?'selected':''} onClick={()=>setTab(item)} key={item}>{item}{item==='Approval inbox'&&approvals.length>0?<b>{approvals.length}</b>:item==='Data quality'&&quality.length>0?<b>{quality.length}</b>:null}</button>)}</nav>{message&&<div className="success-message"><Icon name="check" size={17}/>{message}</div>}
  {tab==='Global search'&&<section className="master-panel"><div className="operation-heading"><div><span className="eyebrow">CROSS-MODULE DISCOVERY</span><h2>Find any controlled ITMS record</h2></div></div><div className="global-search-box"><Icon name="reports" size={22}/><input autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder="Asset ID, employee, serial number, allocation, repair, vendor or lifecycle reference"/><span>{filteredSearch.length} results</span></div><DataTable rows={filteredSearch} rowKey={item=>item.id} columns={[{key:'reference',label:'Reference',sticky:true,width:'180px',render:item=><strong>{item.reference}</strong>},{key:'kind',label:'Record type',width:'190px',render:item=>item.kind},{key:'title',label:'Record',width:'320px',render:item=>item.title},{key:'detail',label:'Current context',width:'380px',render:item=>item.detail},{key:'action',label:'Action',width:'130px',render:item=><button type="button" className="table-action" onClick={()=>go(item.module,item.reference)}>Open</button>}]} empty={<div className="empty-state"><Icon name="reports" size={32}/><strong>{query.length<2?'Enter at least two characters':'No matching records'}</strong></div>}/></section>}
  {tab==='Approval inbox'&&<section className="master-panel"><div className="operation-heading"><div><span className="eyebrow">CONSOLIDATED DUAL CONTROL</span><h2>Manager and IT Head approval inbox</h2><p>Decisions remain in the authoritative source workflow.</p></div></div><div className="master-summary"><div><span>Total pending</span><strong>{approvals.length}</strong></div><div><span>Asset Manager</span><strong>{approvals.filter(item=>item.state.includes('Asset Manager')).length}</strong></div><div><span>IT Head</span><strong>{approvals.filter(item=>item.state.includes('IT Head')).length}</strong></div></div><DataTable rows={approvals} rowKey={item=>item.id} columns={[{key:'reference',label:'Reference',sticky:true,width:'180px',render:item=><strong>{item.reference}</strong>},{key:'kind',label:'Workflow',width:'260px',render:item=>item.kind},{key:'state',label:'Approval stage',width:'220px',render:item=><span className="status inactive">{item.state}</span>},{key:'submitted',label:'Submitted',width:'180px',render:item=>new Date(item.submitted).toLocaleString('en-IN')},{key:'action',label:'Decision',width:'180px',render:item=><button type="button" className="table-action" onClick={()=>go(item.module,item.reference)}>Open source record</button>}]} empty={<div className="empty-state"><Icon name="check" size={32}/><strong>No approvals pending</strong></div>}/></section>}
  {tab==='Warranty'&&<section className="master-panel"><div className="operation-heading"><div><span className="eyebrow">WARRANTY & RMA CONTROL</span><h2>Expiry calendar and claim register</h2></div><button type="button" className="primary-action" onClick={()=>setClaimOpen(!claimOpen)}><Icon name="plus" size={17}/>New claim</button></div>{claimOpen&&<form className="master-form operation-form" onSubmit={saveClaim}><label>Asset<select required value={claim.assetId} onChange={event=>setClaim({...claim,assetId:event.target.value})}><option value="">Select asset</option>{warranties.map(item=><option value={item.id} key={item.id}>{assetLabel(item.id)} · expires {item.expiry}</option>)}</select></label><label>Vendor<select value={claim.vendorId} onChange={event=>setClaim({...claim,vendorId:event.target.value})}><option value="">Not assigned</option>{vendors.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Reported date<input required type="date" value={claim.reportedDate} onChange={event=>setClaim({...claim,reportedDate:event.target.value})}/></label><label>RMA / ticket reference<input value={claim.rmaReference} onChange={event=>setClaim({...claim,rmaReference:event.target.value})}/></label><label>Claim status<select value={claim.claimStatus} onChange={event=>setClaim({...claim,claimStatus:event.target.value as WarrantyClaim['claimStatus']})}><option>Draft</option><option>Submitted</option><option>Accepted</option><option>Rejected</option><option>Resolved</option></select></label><label className="wide-field">Replacement / repair outcome<input value={claim.replacementOutcome} onChange={event=>setClaim({...claim,replacementOutcome:event.target.value})}/></label><div className="form-actions"><button type="button" onClick={()=>setClaimOpen(false)}>Cancel</button><button type="submit" className="primary-action">Save claim</button></div></form>}<DataTable rows={warranties} rowKey={item=>item.id} columns={[{key:'asset',label:'Asset',sticky:true,width:'260px',render:item=><strong>{assetLabel(item.id)}</strong>},{key:'purchase',label:'Purchase date',width:'130px',render:item=>item.purchaseDate},{key:'expiry',label:'Warranty expiry',width:'150px',render:item=>item.expiry},{key:'status',label:'Warranty state',width:'150px',render:item=><span className={`status ${item.expiry>=today()?'active':'inactive'}`}>{item.expiry>=today()?'Covered':'Expired'}</span>},{key:'claim',label:'Open claim / RMA',width:'260px',render:item=>item.claim?`${item.claim.code} · ${item.claim.claimStatus} · ${item.claim.rmaReference||'No RMA'}`:'No open claim'},{key:'action',label:'Action',width:'130px',render:item=><button type="button" className="table-action" onClick={()=>go('Asset Inventory',item.assetId)}>Open asset</button>}]} empty={<div className="empty-state"><strong>No warranty-bearing assets</strong></div>}/></section>}
  {tab==='Stock verification'&&<section className="master-panel verification-launch"><div><Icon name="assurance" size={42}/><span className="eyebrow">MOBILE-FRIENDLY COUNT & RECONCILIATION</span><h2>Physical stock verification</h2><p>Scan or select assets, record missing/damaged/custody mismatch results, and reconcile exceptions in the governed Assurance workspace.</p><div><b>{assets.length}</b><span>registered assets</span><b>{verifications.length}</b><span>verification records</span><b>{verifications.filter(item=>item.result!=='Verified').length}</b><span>exceptions</span></div><button className="primary-action" type="button" onClick={()=>go('Assurance & Controls','Physical verification')}>Open stock verification</button></div></section>}
  {tab==='Controlled export'&&<section className="master-panel export-centre"><div className="operation-heading"><div><span className="eyebrow">RECOVERY & AUDIT PACKAGE</span><h2>Controlled full-system export</h2><p>Exports every ITMS local record store, relationship and audit trail.</p></div></div><div className="export-cards"><article><Icon name="package" size={30}/><strong>Complete JSON recovery package</strong><p>Machine-readable backup preserving store names, internal identifiers and linked records.</p><button type="button" className="primary-action" onClick={exportPackage}>Download full package</button></article><article><Icon name="reports" size={30}/><strong>CSV control index</strong><p>Human-readable inventory of record stores and record counts for reconciliation.</p><button type="button" className="secondary-action" onClick={exportIndex}>Download control index</button></article></div><div className="access-warning">Protect exported files as confidential company records. Test restoration before relying on an export as a backup.</div></section>}
  {tab==='Notification rules'&&<section className="master-panel"><div className="operation-heading"><div><span className="eyebrow">REMINDER & ESCALATION GOVERNANCE</span><h2>Notification rules</h2><p>Local email preparation remains manual until an approved delivery service is connected.</p></div><button type="button" className="primary-action" onClick={addRule}><Icon name="plus" size={17}/>Add rule</button></div><DataTable rows={rules} rowKey={item=>item.id} columns={[{key:'event',label:'Event',sticky:true,width:'220px',render:item=><select value={item.event} onChange={event=>setRules(current=>current.map(value=>value.id===item.id?{...value,event:event.target.value,updatedAt:new Date().toISOString()}:value))}><option>Warranty expiry</option><option>Maintenance due</option><option>Pending approval</option><option>Employee offboarding</option><option>Open repair</option></select>},{key:'recipient',label:'Recipient',width:'260px',render:item=><input value={item.recipient} onChange={event=>setRules(current=>current.map(value=>value.id===item.id?{...value,recipient:event.target.value,updatedAt:new Date().toISOString()}:value))}/>},{key:'lead',label:'Lead days',width:'120px',render:item=><input type="number" min="0" value={item.leadDays} onChange={event=>setRules(current=>current.map(value=>value.id===item.id?{...value,leadDays:Number(event.target.value),updatedAt:new Date().toISOString()}:value))}/>},{key:'escalation',label:'Escalate after',width:'140px',render:item=><input type="number" min="0" value={item.escalationDays} onChange={event=>setRules(current=>current.map(value=>value.id===item.id?{...value,escalationDays:Number(event.target.value),updatedAt:new Date().toISOString()}:value))}/>},{key:'state',label:'State',width:'120px',render:item=><button className="table-action" type="button" onClick={()=>setRules(current=>current.map(value=>value.id===item.id?{...value,enabled:!value.enabled,updatedAt:new Date().toISOString()}:value))}>{item.enabled?'Enabled':'Disabled'}</button>}]} empty={<div className="empty-state"><strong>No notification rules configured</strong></div>}/></section>}
  {tab==='Data quality'&&<section className="master-panel"><div className="operation-heading"><div><span className="eyebrow">REFERENTIAL INTEGRITY</span><h2>Data-quality dashboard</h2><p>Duplicate, orphaned, expired and incomplete records requiring correction.</p></div></div><div className="master-summary"><div><span>Total findings</span><strong>{quality.length}</strong></div><div><span>Critical</span><strong>{quality.filter(item=>item.severity==='Critical').length}</strong></div><div><span>Warnings</span><strong>{quality.filter(item=>item.severity==='Warning').length}</strong></div></div><DataTable rows={quality} rowKey={item=>item.id} columns={[{key:'reference',label:'Reference',sticky:true,width:'180px',render:item=><strong>{item.reference}</strong>},{key:'severity',label:'Severity',width:'130px',render:item=><span className={`quality-severity ${item.severity.toLowerCase()}`}>{item.severity}</span>},{key:'kind',label:'Finding type',width:'220px',render:item=>item.kind},{key:'issue',label:'Issue',width:'440px',render:item=>item.issue},{key:'action',label:'Action',width:'130px',render:item=><button type="button" className="table-action" onClick={()=>go(item.module,item.reference)}>Correct</button>}]} empty={<div className="empty-state"><Icon name="check" size={32}/><strong>No data-quality findings</strong></div>}/></section>}
  </>
}
