import { useMemo, useState, type FormEvent } from 'react'
import DataTable from '../../components/DataTable'
import Icon from '../../components/Icon'
import { deriveCustody, type CustodyMovement } from '../../lib/custodyLifecycle'
import { useLocalStore } from '../../lib/localStore'
import './RetirementWorkspace.css'

type Asset = { id:string; assetId:string; typeId:string; modelId:string; serialNumber:string; stockStatus:string; condition:string; cost:number; locationId:string }
type Basic = { id:string; code:string; name:string }
type Model = { id:string; brand:string; name:string }
type Allocation = { id:string; code:string; userId:string; assetIds:string[]; allocationDate:string; state:string; requestedAt:string }
export type RetirementRecord = { id:string; code:string; route:'Scrap & recycling'|'Donation / CSR / giveaway'; assetIds:string[]; assetId?:string; previousStatuses:Record<string,string>; previousStatus?:string; reason:string; dataSanitised:boolean; partyName:string; partyAddress:string; partyContact:string; reference:string; estimatedValue:number; handoverDate:string; requestedBy:string; requestedAt:string; managerAt:string; headAt:string; completedAt:string; state:'Pending Asset Manager'|'Pending IT Head'|'Approved - awaiting handover'|'Completed'|'Cancelled' }

const today=()=>new Date().toISOString().slice(0,10)
export default function RetirementWorkspace(){
  const [assets,setAssets]=useLocalStore<Asset[]>('itms.assets.v1',[]);const [types]=useLocalStore<Basic[]>('itms.asset-types.v1',[]);const [models]=useLocalStore<Model[]>('itms.asset-models.v1',[]);const [allocations]=useLocalStore<Allocation[]>('itms.allocations.v1',[]);const [movements]=useLocalStore<CustodyMovement[]>('itms.custody-movements.v1',[]);const [records,setRecords]=useLocalStore<RetirementRecord[]>('itms.asset-retirements.v1',[])
  const [tab,setTab]=useState<'Dashboard'|'Requests'|'Scrap & recycling'|'Donation / CSR / giveaway'|'History'>('Dashboard');const [open,setOpen]=useState(false);const [groupIds,setGroupIds]=useState<string[]>([]);const [assetIds,setAssetIds]=useState<string[]>([]);const [printId,setPrintId]=useState('');const [message,setMessage]=useState('');const [form,setForm]=useState({route:'Scrap & recycling' as RetirementRecord['route'],reason:'',dataSanitised:false,partyName:'',partyAddress:'',partyContact:'',reference:'',estimatedValue:'0',handoverDate:today()})
  const recordAssetIds=(r:RetirementRecord)=>r.assetIds?.length?r.assetIds:r.assetId?[r.assetId]:[];const custody=useMemo(()=>deriveCustody(allocations,movements,assets),[allocations,assets,movements]);const activeAssetIds=new Set(records.filter(r=>!['Completed','Cancelled'].includes(r.state)).flatMap(recordAssetIds));const eligible=assets.filter(a=>!custody.has(a.id)&&!activeAssetIds.has(a.id)&&!a.stockStatus.includes('Disposed')&&!a.stockStatus.includes('Donated')&&!a.stockStatus.includes('Recycled'))
  const assetLabel=(id:string)=>{const a=assets.find(x=>x.id===id);const m=models.find(x=>x.id===a?.modelId);return a?`${a.assetId} · ${m?.brand??''} ${m?.name??''} · ${a.serialNumber||'No serial'}`:'Unavailable asset'}
  function reset(){setOpen(false);setGroupIds([]);setAssetIds([]);setForm({route:'Scrap & recycling',reason:'',dataSanitised:false,partyName:'',partyAddress:'',partyContact:'',reference:'',estimatedValue:'0',handoverDate:today()})}
  function toggleGroup(id:string){setGroupIds(c=>c.includes(id)?c.filter(x=>x!==id):[...c,id]);setAssetIds(c=>c.filter(assetId=>{const asset=assets.find(a=>a.id===assetId);return asset&&asset.typeId!==id}))}
  function toggleAsset(id:string){setAssetIds(c=>c.includes(id)?c.filter(x=>x!==id):[...c,id])}
  function submit(e:FormEvent){e.preventDefault();if(!assetIds.length)return;const previousStatuses=Object.fromEntries(assetIds.map(id=>[id,assets.find(a=>a.id===id)?.stockStatus??'In stock']));const record:RetirementRecord={id:crypto.randomUUID(),code:`RET-${new Date().getFullYear()}-${String(records.length+1).padStart(4,'0')}`,assetIds:[...assetIds],previousStatuses,requestedBy:'dev@glasscolabs.com',requestedAt:new Date().toISOString(),managerAt:'',headAt:'',completedAt:'',state:'Pending Asset Manager',...form,estimatedValue:Number(form.estimatedValue||0)};setRecords(c=>[...c,record]);setAssets(c=>c.map(a=>assetIds.includes(a.id)?{...a,stockStatus:'Retirement approval pending'}:a));setMessage(`${record.code} submitted with ${assetIds.length} assets reserved from allocation.`);reset()}
  function advance(id:string){const r=records.find(x=>x.id===id);if(!r)return;const now=new Date().toISOString();if(r.state==='Pending Asset Manager'){setRecords(c=>c.map(x=>x.id===id?{...x,state:'Pending IT Head',managerAt:now}:x));setMessage('IT Asset Manager approval recorded.')}else if(r.state==='Pending IT Head'){setRecords(c=>c.map(x=>x.id===id?{...x,state:'Approved - awaiting handover',headAt:now}:x));setMessage('IT Head approval recorded; physical handover remains due.')}else if(r.state==='Approved - awaiting handover'){const ids=recordAssetIds(r);setRecords(c=>c.map(x=>x.id===id?{...x,state:'Completed',completedAt:now}:x));setAssets(c=>c.map(a=>ids.includes(a.id)?{...a,stockStatus:r.route==='Scrap & recycling'?'Recycled / scrapped':'Donated / transferred',condition:'Retired'}:a));setMessage(`${ids.length} asset lifecycle records permanently closed after handover.`)}}
  function cancel(id:string){const r=records.find(x=>x.id===id);if(!r||r.state==='Completed')return;const ids=recordAssetIds(r);setRecords(c=>c.map(x=>x.id===id?{...x,state:'Cancelled'}:x));setAssets(c=>c.map(a=>ids.includes(a.id)?{...a,stockStatus:r.previousStatuses?.[a.id]??r.previousStatus??'In stock'}:a));setMessage('Request cancelled; all assets returned to their prior lifecycle states.')}
  const visible=records.filter(r=>tab==='Scrap & recycling'?r.route==='Scrap & recycling':tab==='Donation / CSR / giveaway'?r.route==='Donation / CSR / giveaway':tab==='History'?['Completed','Cancelled'].includes(r.state):true);const printed=records.find(r=>r.id===printId)
  return <><section className="page-heading"><div><span className="eyebrow">GCCP-ITMS-BUILD-16</span><h1>Asset Retirement &amp; Circularity</h1><p>Govern recycling, donation and final custody transfer without breaking asset history.</p></div><span className="phase">DUAL APPROVAL</span></section><section className="master-panel retirement-workspace"><div className="master-toolbar"><div className="master-tabs">{(['Dashboard','Requests','Scrap & recycling','Donation / CSR / giveaway','History'] as const).map(x=><button type="button" className={tab===x?'selected':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><button className="primary-action" type="button" onClick={()=>setOpen(!open)}><Icon name="plus" size={18}/>New retirement request</button></div>
  {open&&<form className="master-form operation-form" onSubmit={submit}><label>Disposition route<select value={form.route} onChange={e=>setForm({...form,route:e.target.value as RetirementRecord['route']})}><option>Scrap &amp; recycling</option><option>Donation / CSR / giveaway</option></select></label><fieldset className="retirement-picker wide-field"><legend>1. Select one or more item groups</legend><div>{types.filter(t=>eligible.some(a=>a.typeId===t.id)).map(t=><label key={t.id}><input type="checkbox" checked={groupIds.includes(t.id)} onChange={()=>toggleGroup(t.id)}/>{t.code} · {t.name}<small>{eligible.filter(a=>a.typeId===t.id).length} available</small></label>)}</div></fieldset>{groupIds.length>0&&<fieldset className="retirement-picker asset-picker wide-field"><legend>2. Select assets across chosen groups</legend><div>{eligible.filter(a=>groupIds.includes(a.typeId)).map(a=><label key={a.id}><input type="checkbox" checked={assetIds.includes(a.id)} onChange={()=>toggleAsset(a.id)}/><span>{assetLabel(a.id)}</span></label>)}</div><footer><strong>{assetIds.length} asset{assetIds.length===1?'':'s'} selected</strong><button type="button" onClick={()=>setAssetIds(eligible.filter(a=>groupIds.includes(a.typeId)).map(a=>a.id))}>Select all shown</button><button type="button" onClick={()=>setAssetIds([])}>Clear</button></footer></fieldset>}{assetIds.length>0&&<><label>Recycler / recipient name<input required value={form.partyName} onChange={e=>setForm({...form,partyName:e.target.value})}/></label><label>Contact<input required value={form.partyContact} onChange={e=>setForm({...form,partyContact:e.target.value})}/></label><label>Handover date<input required type="date" value={form.handoverDate} onChange={e=>setForm({...form,handoverDate:e.target.value})}/></label><label>Challan / CSR / activity reference<input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></label><label>Recovery / transfer value (INR)<input min="0" type="number" value={form.estimatedValue} onChange={e=>setForm({...form,estimatedValue:e.target.value})}/></label><label className="checkbox-field"><input type="checkbox" checked={form.dataSanitised} onChange={e=>setForm({...form,dataSanitised:e.target.checked})}/>Data sanitisation / non-applicability confirmed</label><label className="wide-field">Recycler / recipient address<textarea required value={form.partyAddress} onChange={e=>setForm({...form,partyAddress:e.target.value})}/></label><label className="wide-field">Technical justification and condition<textarea required value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><div className="form-actions"><button type="button" onClick={reset}>Cancel</button><button className="primary-action" type="submit">Submit {assetIds.length} assets for dual approval</button></div></>}</form>}
  {message&&<div className="success-message"><Icon name="check" size={18}/>{message}</div>}<div className="master-summary retirement-summary"><div><span>Pending approval</span><strong>{records.filter(r=>r.state.startsWith('Pending')).length}</strong></div><div><span>Awaiting handover</span><strong>{records.filter(r=>r.state==='Approved - awaiting handover').length}</strong></div><div><span>Recycled</span><strong>{records.filter(r=>r.state==='Completed'&&r.route==='Scrap & recycling').length}</strong></div><div><span>Donated / transferred</span><strong>{records.filter(r=>r.state==='Completed'&&r.route!=='Scrap & recycling').length}</strong></div></div>
  {tab==='Dashboard'?<div className="retirement-dashboard"><article><Icon name="assurance" size={28}/><strong>Controlled final disposition</strong><p>Assets remain reserved during approval and close only after documented physical handover.</p></article><article><Icon name="history" size={28}/><strong>Immutable lifecycle context</strong><p>Original identity, value, approval stamps, recipient and declaration remain searchable.</p></article><article><Icon name="reports" size={28}/><strong>Declaration-ready records</strong><p>Generate recycling or donation declarations with accountable signature blocks.</p></article></div>:<DataTable rows={[...visible].reverse()} rowKey={r=>r.id} columns={[{key:'code',label:'Batch reference',sticky:true,width:'170px',render:r=><strong>{r.code}</strong>},{key:'asset',label:'Asset schedule',width:'420px',render:r=><div className="batch-assets"><strong>{recordAssetIds(r).length} asset{recordAssetIds(r).length===1?'':'s'}</strong>{recordAssetIds(r).map(id=><small key={id}>{assetLabel(id)}</small>)}</div>},{key:'route',label:'Route',width:'210px',render:r=>r.route},{key:'party',label:'Recycler / recipient',width:'240px',render:r=>r.partyName},{key:'handover',label:'Handover date',width:'140px',render:r=>r.handoverDate},{key:'state',label:'Status',width:'220px',render:r=><span className={`status ${r.state==='Completed'?'active':'inactive'}`}>{r.state}</span>},{key:'actions',label:'Actions',width:'330px',render:r=><div className="table-actions">{!['Completed','Cancelled'].includes(r.state)&&<button className="table-action" type="button" onClick={()=>advance(r.id)}>{r.state==='Pending Asset Manager'?'Manager approve':r.state==='Pending IT Head'?'IT Head approve':'Complete handover'}</button>}{r.state!=='Completed'&&r.state!=='Cancelled'&&<button className="table-action" type="button" onClick={()=>cancel(r.id)}>Cancel</button>}<button className="table-action" type="button" onClick={()=>{setPrintId(r.id);setTimeout(()=>window.print(),80)}}>Declaration PDF</button></div>}]} empty={<div className="empty-state"><span><Icon name="assurance" size={32}/></span><strong>No retirement records</strong><p>Create a controlled recycling or donation request.</p></div>}/>}</section>
  {printed&&<section className="retirement-declaration print-only"><header><strong>GLASSCO</strong><span>CONNECT · ITMS</span><b>{printed.route==='Scrap & recycling'?'ASSET SCRAP & RECYCLING DECLARATION':'IT ASSET DONATION & CUSTODY TRANSFER DECLARATION'}</b></header><h1>{printed.code}</h1><p>This controlled record documents the authorised final disposition of the IT assets listed below. It is not a tax, CSR or statutory compliance certificate.</p><section className="print-asset-schedule"><h2>Controlled asset schedule ({recordAssetIds(printed).length})</h2>{recordAssetIds(printed).map((id,index)=><div key={id}><b>{index+1}</b><span>{assetLabel(id)}</span></div>)}</section><dl><div><dt>Route</dt><dd>{printed.route}</dd></div><div><dt>Recycler / recipient</dt><dd>{printed.partyName}<br/>{printed.partyAddress}<br/>{printed.partyContact}</dd></div><div><dt>Handover date</dt><dd>{printed.handoverDate}</dd></div><div><dt>Reference</dt><dd>{printed.reference||'Not recorded'}</dd></div><div><dt>Data sanitisation</dt><dd>{printed.dataSanitised?'Confirmed / not applicable':'Not confirmed'}</dd></div><div><dt>Reason and condition</dt><dd>{printed.reason}</dd></div><div><dt>Approval state</dt><dd>{printed.state}</dd></div></dl><footer><span>IT Asset Manager<br/><i>Signature / date</i></span><span>IT Head<br/><i>Signature / date</i></span><span>Recycler / recipient<br/><i>Signature / seal / date</i></span></footer></section>}</>
}
