import { useMemo, useState } from 'react'
import { useLocalStore } from '../../lib/localStore'
import type { AssetTypeLike, SpareCompatibility } from './assetSpecifications'

type Model={id:string;typeId:string;code:string;name:string;brand:string}
const isSpare=(type:AssetTypeLike)=>/spare|part|ram|storage|cartridge/.test(`${type.code} ${type.name}`.toLowerCase())

export default function SpareCompatibilityMapping(){
 const [types]=useLocalStore<AssetTypeLike[]>('itms.asset-types.v1',[])
 const [models]=useLocalStore<Model[]>('itms.asset-models.v1',[])
 const [rules,setRules]=useLocalStore<SpareCompatibility[]>('itms.spare-compatibility.v1',[])
 const [spareTypeId,setSpareTypeId]=useState('');const [targetTypes,setTargetTypes]=useState<string[]>([]);const [targetModels,setTargetModels]=useState<string[]>([]);const [note,setNote]=useState('')
 const spareTypes=types.filter(isSpare);const selected=spareTypes.find(type=>type.id===spareTypeId);const compatibleModels=useMemo(()=>models.filter(model=>targetTypes.includes(model.typeId)),[models,targetTypes])
 function toggle(list:string[],id:string,setter:(next:string[])=>void){setter(list.includes(id)?list.filter(value=>value!==id):[...list,id])}
 function save(){if(!selected||(!targetTypes.length&&!targetModels.length))return;const now=new Date().toISOString();setRules(current=>[...current.filter(rule=>rule.spareTypeId!==selected.id),{id:`compat-${selected.id}`,spareTypeId:selected.id,compatibleTypeIds:targetTypes,compatibleModelIds:targetModels,note:note.trim(),updatedAt:now}]);setNote('')}
 return <section className="master-panel compatibility-panel"><header className="panel-heading"><div><span className="eyebrow">SPARE PART GOVERNANCE</span><h2>Compatibility mapping</h2><p>Define which asset categories and models a spare part can support. This replaces free-text compatibility as the governed reference.</p></div></header><div className="compatibility-form"><label>Spare part category<select value={spareTypeId} onChange={event=>{setSpareTypeId(event.target.value);setTargetTypes([]);setTargetModels([])}}><option value="">Select spare part category</option>{spareTypes.map(type=><option key={type.id} value={type.id}>{type.code} · {type.name}</option>)}</select></label>{selected&&<><fieldset><legend>Compatible asset categories</legend>{types.filter(type=>type.id!==selected.id&&!isSpare(type)).map(type=><label key={type.id}><input type="checkbox" checked={targetTypes.includes(type.id)} onChange={()=>toggle(targetTypes,type.id,setTargetTypes)}/>{type.code} · {type.name}</label>)}</fieldset><fieldset><legend>Compatible models</legend>{compatibleModels.length?compatibleModels.map(model=><label key={model.id}><input type="checkbox" checked={targetModels.includes(model.id)} onChange={()=>toggle(targetModels,model.id,setTargetModels)}/>{model.brand} · {model.name}</label>):<span>Select a compatible category first.</span>}</fieldset><label>Compatibility note<textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Optional limitation or revision note"/></label><button className="primary-action" type="button" onClick={save}>Save compatibility</button></>}</div><div className="compatibility-list">{rules.map(rule=>{const spare=types.find(type=>type.id===rule.spareTypeId);return <article key={rule.id}><strong>{spare?.code} · {spare?.name}</strong><span>{rule.compatibleTypeIds.map(id=>types.find(type=>type.id===id)?.name).filter(Boolean).join(', ')||'No category'}{rule.compatibleModelIds.length?` · ${rule.compatibleModelIds.map(id=>models.find(model=>model.id===id)?.name).filter(Boolean).join(', ')}`:''}</span><small>{rule.note||'No additional note'} · Updated {new Date(rule.updatedAt).toLocaleDateString('en-IN')}</small></article>})}{!rules.length&&<p>No governed spare compatibility mappings saved.</p>}</div></section>
}
